/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.Multiquadratic.Prime.Radicands
public import TauCeti.NumberTheory.Multiquadratic.Subfield.Count

/-!
# Quadratic subfields of `ℚ(√p₁, …, √pₙ)`

This file specializes the field-generic quadratic-subfield count
`TauCeti.NumberTheory.Multiquadratic.SubfieldCount.card_quadratic_intermediateField_adjoin_range`
to fields `ℚ(√p₁, …, √pₙ)` generated by square roots of a finite family of distinct primes,
matching the prime-radicand lattice and degree APIs in
`TauCeti.NumberTheory.Multiquadratic.Prime.Subfield.Lattice` and
`TauCeti.NumberTheory.Multiquadratic.Prime.Subfield.Degree`. The prime-specific square-root
equation and square-class independence inputs come from
`TauCeti.NumberTheory.Multiquadratic.Prime.Radicands`.

## Main results

* `TauCeti.Multiquadratic.card_quadratic_intermediateField_adjoin_sqrt_primes`: for a finite
  family of distinct primes, `ℚ(√p₁, …, √pₙ)` has exactly `2 ^ |ι| - 1` intermediate fields of
  degree `2` over `ℚ`.
-/

public section

open IntermediateField

namespace TauCeti.Multiquadratic

variable {ι : Type*}

/-- **The number of quadratic subfields of `ℚ(√p₁, …, √pₙ)` is `2ⁿ - 1`.** For a finite family of
distinct primes `p : ι → ℕ`, the multiquadratic field `ℚ(√p₁, …, √pₙ)`, of degree `2 ^ |ι|` over
`ℚ`, has exactly `2 ^ |ι| - 1` intermediate fields of degree `2` over `ℚ`. This is the
prime-radicand specialization of `card_quadratic_intermediateField_adjoin_range`. -/
theorem card_quadratic_intermediateField_adjoin_sqrt_primes [Finite ι] (p : ι → ℕ)
    (hp : ∀ i, (p i).Prime) (hinj : Function.Injective p) :
    Nat.card {F : IntermediateField ℚ (adjoin ℚ (Set.range fun i => (Real.sqrt (p i) : ℝ))) //
        Module.finrank ℚ F = 2} = 2 ^ Nat.card ι - 1 :=
  card_quadratic_intermediateField_adjoin_range (fun i => sq_sqrt_natCast (p i))
    (not_isSquare_prod_primes_of_injective p hp hinj)

end TauCeti.Multiquadratic
