/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.NumberTheory.NumberField.Units.DirichletTheorem

/-!
# Dirichlet's unit theorem in structural form

Mathlib's `NumberField.Units.exist_unique_eq_mul_prod` states that every unit of `𝓞 F` has a
unique decomposition as a root of unity times a product of powers of the fundamental system.
This file packages that unique decomposition as a multiplicative equivalence

`(𝓞 F)ˣ ≃* torsion F × Multiplicative (Fin (rank F) → ℤ)`,

exhibiting the unit group as the product of its (finite cyclic) torsion subgroup and a free
abelian group of Dirichlet rank. This structural form is what downstream counting arguments
consume — for instance the exact number of unit square classes in
`TauCeti.NumberTheory.NumberField.Units.ElementaryTwoQuotient`.

## Main results

* `TauCeti.NumberField.unitsMulEquivTorsionProdMultiplicative`: the unit group as the product of
  its torsion subgroup and the free abelian group on the fundamental system.
-/

public section

open scoped NumberField

open Module NumberField NumberField.Units

namespace TauCeti.NumberField

variable (F : Type*) [Field F] [NumberField F]

/-- The homomorphism realizing a pair (root of unity, exponent vector) as a unit, the underlying
map of `TauCeti.NumberField.unitsMulEquivTorsionProdMultiplicative`. Kept private; the public
interface is the equivalence. -/
private noncomputable def torsionProdMultiplicativeToUnits :
    torsion F × Multiplicative (Fin (rank F) → ℤ) →* (𝓞 F)ˣ :=
  ((torsion F).subtype).coprod <|
    MonoidHom.mk' (fun e => ∏ i, fundSystem F i ^ Multiplicative.toAdd e i) fun a b => by
      simp only [toAdd_mul, Pi.add_apply, zpow_add, Finset.prod_mul_distrib]

private theorem torsionProdMultiplicativeToUnits_apply
    (ζ : torsion F) (e : Multiplicative (Fin (rank F) → ℤ)) :
    torsionProdMultiplicativeToUnits F (ζ, e) =
      (ζ : (𝓞 F)ˣ) * ∏ i, fundSystem F i ^ Multiplicative.toAdd e i := by
  simp [torsionProdMultiplicativeToUnits, MonoidHom.coprod_apply]

/-- Dirichlet's unit theorem in its unique-decomposition form says exactly that realizing a pair
(root of unity, exponent vector) as a unit is bijective. -/
private theorem torsionProdMultiplicativeToUnits_bijective :
    Function.Bijective (torsionProdMultiplicativeToUnits F) := by
  constructor
  · rintro ⟨ζ, e⟩ ⟨ζ', e'⟩ h
    obtain ⟨p, -, huniq⟩ :=
      exist_unique_eq_mul_prod F (torsionProdMultiplicativeToUnits F (ζ, e))
    have h1 : (ζ, Multiplicative.toAdd e) = p :=
      huniq (ζ, Multiplicative.toAdd e) (torsionProdMultiplicativeToUnits_apply F ζ e)
    have h2 : (ζ', Multiplicative.toAdd e') = p :=
      huniq (ζ', Multiplicative.toAdd e')
        (h.trans (torsionProdMultiplicativeToUnits_apply F ζ' e'))
    obtain ⟨hζ, he⟩ := Prod.mk.inj (h1.trans h2.symm)
    exact Prod.ext hζ (Multiplicative.toAdd.injective he)
  · intro x
    obtain ⟨⟨ζ, v⟩, hx, -⟩ := exist_unique_eq_mul_prod F x
    exact ⟨(ζ, Multiplicative.ofAdd v), hx.symm⟩

/-- **Dirichlet's unit theorem, structural form.** The unit group of the ring of integers of a
number field is the product of its torsion subgroup and the free abelian group generated by the
fundamental system: a unit corresponds to its unique decomposition as a root of unity times a
product of powers of fundamental units (`NumberField.Units.exist_unique_eq_mul_prod`). -/
noncomputable def unitsMulEquivTorsionProdMultiplicative :
    (𝓞 F)ˣ ≃* torsion F × Multiplicative (Fin (rank F) → ℤ) :=
  (MulEquiv.ofBijective _ (torsionProdMultiplicativeToUnits_bijective F)).symm

/-- The inverse of `TauCeti.NumberField.unitsMulEquivTorsionProdMultiplicative` sends a pair to
the root of unity times the product of powers of fundamental units. -/
@[simp] theorem unitsMulEquivTorsionProdMultiplicative_symm_apply
    (ζ : torsion F) (e : Multiplicative (Fin (rank F) → ℤ)) :
    (unitsMulEquivTorsionProdMultiplicative F).symm (ζ, e) =
      (ζ : (𝓞 F)ˣ) * ∏ i, fundSystem F i ^ Multiplicative.toAdd e i := by
  rw [unitsMulEquivTorsionProdMultiplicative, MulEquiv.symm_symm]
  exact torsionProdMultiplicativeToUnits_apply F ζ e

/-- The forward map of `TauCeti.NumberField.unitsMulEquivTorsionProdMultiplicative` reads off the
Dirichlet decomposition: a unit presented as a root of unity `ζ` times a product of powers of the
fundamental system is sent to the pair `(ζ, e)`. -/
@[simp] theorem unitsMulEquivTorsionProdMultiplicative_apply
    (ζ : torsion F) (e : Fin (rank F) → ℤ) :
    unitsMulEquivTorsionProdMultiplicative F
        ((ζ : (𝓞 F)ˣ) * ∏ i, fundSystem F i ^ e i) = (ζ, Multiplicative.ofAdd e) := by
  rw [unitsMulEquivTorsionProdMultiplicative, MulEquiv.symm_apply_eq, MulEquiv.ofBijective_apply,
    torsionProdMultiplicativeToUnits_apply]
  simp

end TauCeti.NumberField
