/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.GroupTheory.Presentation.GroupPresentation

/-!
# A transcribed presentation of the second Fischer group

This file carries the `Fi₂₃` row of the sporadic presentation data required by milestone S1 of
`TauCetiRoadmap/CFSGStatement/README.md`. It records presentation `GPLTable.Fi23.1` from Roderik
Lindenbergh's Group Presentations Library as a `TauCeti.GroupPresentation`, together with the exact
source, generator convention, transcription notes, expected counts, and decidable checks on the
transcription.

The presentation uses the Coxeter graph

```text
a --3-- b --3-- c --3-- d --3-- e --3-- f --3-- g --3-- j
                              |
                              3
                              |
                              h --3-- i
```

where all ten generators are involutions and every omitted edge has label `2`. The source encodes
this graph by the two paths `a3b3c3d3e3f3g3j,d3h3i`. It then appends

```text
(d c b d e f d h i)^10,  (a b c d e f h)^9.
```

Thus the graph contributes ten square relations, nine label-three relations, and thirty-six
omitted-edge relations. With the two appended words, the presentation has `57` relators and its
compiled words have `371` signed letters. The theorems below check those figures and cyclic
reduction from the transcribed data.

The library identifies this record as a presentation of `Fi₂₃` originating in Praeger--Soicher,
whose construction uses low-rank representations and graphs for sporadic groups. As an independent
transcription check, GAP 4.15.1 enumerates `31671` cosets of the subgroup generated by `a` through
`i`; the source identifies that subgroup as `2·Fi₂₂`, and `31671` is its index in `Fi₂₃`. This
computation is provenance rather than a Lean theorem: this file asserts no order, finiteness,
simplicity, or identification result. A separate source-to-Lean read-through remains part of the
S1 review artifact required by the roadmap.

## Main definition

* `TauCeti.Sporadic.fi23Presentation`: the GPL finite presentation of the Fischer group `Fi₂₃`.

## References

* R. Lindenbergh, *Group Presentations Library*, version 1.0, record `GPLTable.Fi23.1`,
  <https://doris.tudelft.nl/~rlindenbergh/GPL/gpl.g>.
* C. E. Praeger and L. H. Soicher, *Low Rank Representations and Graphs for Sporadic Groups*,
  Cambridge University Press, 1997, Chapter 4, doi:10.1017/CBO9780511526039.005.
-/

public section

namespace TauCeti.Sporadic

private abbrev a : Relator (Fin 10) := .gen 0

private abbrev b : Relator (Fin 10) := .gen 1

private abbrev c : Relator (Fin 10) := .gen 2

private abbrev d : Relator (Fin 10) := .gen 3

private abbrev e : Relator (Fin 10) := .gen 4

private abbrev f : Relator (Fin 10) := .gen 5

private abbrev g : Relator (Fin 10) := .gen 6

private abbrev h : Relator (Fin 10) := .gen 7

private abbrev i : Relator (Fin 10) := .gen 8

private abbrev j : Relator (Fin 10) := .gen 9

@[inherit_doc Relator.mul]
local infixl:70 " ⬝ " => Relator.mul

/-- The ten involution relations and the nine labeled-edge relations decoded from the two Coxeter
paths `a3b3c3d3e3f3g3j` and `d3h3i` in `GPLTable.Fi23.1`. -/
private def fi23NodeAndEdgeRelators : List (Relator (Fin 10)) :=
  [ .pow a 2,
    .pow b 2,
    .pow c 2,
    .pow d 2,
    .pow e 2,
    .pow f 2,
    .pow g 2,
    .pow h 2,
    .pow i 2,
    .pow j 2,
    .pow (a ⬝ b) 3,
    .pow (b ⬝ c) 3,
    .pow (c ⬝ d) 3,
    .pow (d ⬝ e) 3,
    .pow (e ⬝ f) 3,
    .pow (f ⬝ g) 3,
    .pow (g ⬝ j) 3,
    .pow (d ⬝ h) 3,
    .pow (h ⬝ i) 3 ]

/-- The thirty-six omitted-edge relations decoded from the two Coxeter paths in
`GPLTable.Fi23.1`. Each omitted edge has label two. -/
private def fi23NonedgeRelators : List (Relator (Fin 10)) :=
  [ .pow (a ⬝ c) 2,
    .pow (a ⬝ d) 2,
    .pow (a ⬝ e) 2,
    .pow (a ⬝ f) 2,
    .pow (a ⬝ g) 2,
    .pow (a ⬝ h) 2,
    .pow (a ⬝ i) 2,
    .pow (a ⬝ j) 2,
    .pow (b ⬝ d) 2,
    .pow (b ⬝ e) 2,
    .pow (b ⬝ f) 2,
    .pow (b ⬝ g) 2,
    .pow (b ⬝ h) 2,
    .pow (b ⬝ i) 2,
    .pow (b ⬝ j) 2,
    .pow (c ⬝ e) 2,
    .pow (c ⬝ f) 2,
    .pow (c ⬝ g) 2,
    .pow (c ⬝ h) 2,
    .pow (c ⬝ i) 2,
    .pow (c ⬝ j) 2,
    .pow (d ⬝ f) 2,
    .pow (d ⬝ g) 2,
    .pow (d ⬝ i) 2,
    .pow (d ⬝ j) 2,
    .pow (e ⬝ g) 2,
    .pow (e ⬝ h) 2,
    .pow (e ⬝ i) 2,
    .pow (e ⬝ j) 2,
    .pow (f ⬝ h) 2,
    .pow (f ⬝ i) 2,
    .pow (f ⬝ j) 2,
    .pow (g ⬝ h) 2,
    .pow (g ⬝ i) 2,
    .pow (h ⬝ j) 2,
    .pow (i ⬝ j) 2 ]

/-- The two words following the Coxeter paths in `GPLTable.Fi23.1`. -/
private def fi23AdditionalRelators : List (Relator (Fin 10)) :=
  [ .pow (d ⬝ c ⬝ b ⬝ d ⬝ e ⬝ f ⬝ d ⬝ h ⬝ i) 10,
    .pow (a ⬝ b ⬝ c ⬝ d ⬝ e ⬝ f ⬝ h) 9 ]

/-- The Group Presentations Library finite presentation `GPLTable.Fi23.1` of the Fischer group
`Fi₂₃` on generators `a`, `b`, `c`, `d`, `e`, `f`, `g`, `h`, `i`, and `j`.

The source describes this as a full presentation of the abstract group and identifies its origin
as Praeger--Soicher. No structural property of the presented group is asserted here: this
definition records only the cited generators and relations. -/
def fi23Presentation : GroupPresentation where
  generatorNames := ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j"]
  source := "R. Lindenbergh, Group Presentations Library, version 1.0; presentation attributed \
    there to C. E. Praeger and L. H. Soicher, Low Rank Representations and Graphs for Sporadic \
    Groups, Cambridge University Press, 1997"
  sourceLocator := "GPLTable.Fi23.1 in \
    https://doris.tudelft.nl/~rlindenbergh/GPL/gpl.g; Praeger--Soicher, Chapter 4, \
    doi:10.1017/CBO9780511526039.005"
  generatorConvention := "Generators have source order a,b,c,d,e,f,g,h,i,j, so indices 0 through \
    9 have those names. A Coxeter path declares each node to be an involution, a labeled edge \
    x-m-y declares (x*y)^m = 1, and an omitted edge declares (x*y)^2 = 1. Products are read left \
    to right."
  transcriptionNotes := "Expand the paths a3b3c3d3e3f3g3j and d3h3i to ten square relations, \
    nine labeled-edge relations, and thirty-six omitted-edge relations. Append the two words in \
    presdef[3]. The expected relator count and total length are derived from this exact expansion. \
    GAP 4.15.1 enumerates 31671 cosets of the subgroup generated by a through i, which the source \
    labels 2.Fi22. A separate source-to-Lean read-through remains an S1 review obligation."
  expectedGeneratorCount := 10
  expectedRelatorCount := 57
  transcribed := fi23NodeAndEdgeRelators ++ fi23NonedgeRelators ++ fi23AdditionalRelators

/-- The generator and relator counts recorded for `Fi₂₃` agree with the transcribed data. -/
theorem fi23Presentation_matchesMetadata : fi23Presentation.matchesMetadata := by
  decide

/-- The compiled relators of the `Fi₂₃` presentation contain `371` signed letters in total. -/
theorem fi23Presentation_totalLength : fi23Presentation.totalLength = 371 := by
  simp [GroupPresentation.totalLength_def, GroupPresentation.relators_def, fi23Presentation,
    fi23NodeAndEdgeRelators, fi23NonedgeRelators, fi23AdditionalRelators]

/-- Every compiled relator of the `Fi₂₃` presentation is cyclically reduced. -/
theorem fi23Presentation_relatorsCyclicallyReduced :
    fi23Presentation.relatorsCyclicallyReduced := by
  simp [GroupPresentation.relatorsCyclicallyReduced_iff, GroupPresentation.relators_def,
    fi23Presentation, fi23NodeAndEdgeRelators, fi23NonedgeRelators, fi23AdditionalRelators,
    FreeGroup.IsCyclicallyReduced]

end TauCeti.Sporadic
