/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.Multiquadratic.CandidateGenusField.Complement.Ramification
public import TauCeti.NumberTheory.Multiquadratic.CandidateGenusField.Discriminant
public import TauCeti.NumberTheory.Multiquadratic.CandidateGenusField.Relative.Quadratic
public import TauCeti.NumberTheory.RamificationInertia.Tower
import TauCeti.NumberTheory.Multiquadratic.Quadratic.Ramification
import Mathlib.LinearAlgebra.Dimension.Localization
import Mathlib.RingTheory.Ideal.NatInt

/-!
# The candidate genus field is unramified over `ℚ(√d)` at the finite places

For a squarefree integer `d`, `candidateGenusField hd` is the compositum of the quadratic fields
attached to the prime discriminants dividing `fundamentalDiscriminant d`, and
`candidateGenusFieldBase hd` is the copy of `K = ℚ(√d)` inside it. This file proves that, for such
a `d` that is moreover not a rational square, every prime of `𝓞 K` is unramified in the candidate
genus field: it is an unramified extension of `ℚ(√d)` at all finite places. This is the defining
property of the genus field at the finite places, and the half of the genus-field identification
the roadmap flags as the trap, since it is exactly where ramification at `2` and at the primes
dividing `d` has to be controlled.

The proof splits on the rational prime `p` below the given prime of `𝓞 K`.

* If `p` does not divide `fundamentalDiscriminant d` then `p` is unramified in the candidate genus
  field already over `ℚ` (`isUnramifiedIn_candidateGenusField_iff`), so nothing can ramify above
  it.
* If `p` does divide `fundamentalDiscriminant d`, it is the prime `primeDiscriminantPrime P`
  belonging to one chosen prime-discriminant factor `P`. Then `p` is totally ramified in the
  quadratic base — its ramification index there is `2` — while the complementary compositum
  generated by all the *other* prime-discriminant roots is unramified at `p`
  (`isUnramifiedIn_candidateGenusFieldComplement_omittedPrime`) and has the candidate genus field
  as a quadratic extension. The transverse cancellation lemma
  `TauCeti.RamificationInertia.isUnramifiedIn_of_finrank_le_of_under_ramificationIdx_eq_one` then
  bounds the absolute ramification index upstairs by `2` as well, so the relative ramification
  index is `1`.

An imaginary `d` is in particular not a rational square (`not_isSquare_of_neg`), and the base is
then totally complex, hence unramified at the infinite places too
(`isUnramifiedAtInfinitePlaces_candidateGenusField`), so for `d < 0` the two results together give
unramifiedness at *every* place: the candidate genus field of an imaginary quadratic field is an
everywhere-unramified abelian extension of it, so it lies inside the Hilbert class field. What
remains for the genus-field identification is maximality — that it is the largest such extension
abelian over `ℚ` — and the isomorphism `Gal(K_gen/K) ≅ Cl(K)/Cl(K)²`.

The description of the genus field as the prime-discriminant compositum is classical; see
D. A. Cox, *Primes of the Form x² + ny²*, and F. Lemmermeyer, *Reciprocity Laws*.

## Main results

* `TauCeti.Multiquadratic.isUnramifiedIn_candidateGenusField_of_liesOver`: for squarefree `d` that
  is not a rational square, a prime of `𝓞 ℚ(√d)` lying over a given rational prime is unramified
  in the candidate genus field.
* `TauCeti.Multiquadratic.isUnramifiedIn_candidateGenusField`: under the same hypotheses, every
  prime of `𝓞 ℚ(√d)` is.
-/

public section

open NumberField

open scoped NumberField

namespace TauCeti.Multiquadratic

variable {d : ℤ}

/-- **The candidate genus field is unramified over `ℚ(√d)` at a prime over `p`.** Let `d` be
squarefree and not a rational square, let `p` be a rational prime, and let `𝔭` be a prime of the
ring of integers of the embedded base `ℚ(√d)` lying over `p`. Then `𝔭` is unramified in the ring
of integers of `candidateGenusField hd`. -/
theorem isUnramifiedIn_candidateGenusField_of_liesOver (hd : Squarefree d)
    (hnsq : ¬ IsSquare ((d : ℤ) : ℚ)) {p : ℕ} (hp : p.Prime)
    (𝔭 : Ideal (𝓞 (candidateGenusFieldBase hd))) [𝔭.IsPrime]
    [𝔭.LiesOver (Ideal.span {(p : ℤ)})] :
    Algebra.IsUnramifiedIn (𝓞 (candidateGenusField hd)) 𝔭 := by
  classical
  obtain ⟨hs, -, hprod⟩ := genusPrimeDiscriminants_spec hd
  by_cases hdvd : (p : ℤ) ∣ fundamentalDiscriminant d
  · -- `p` ramifies in the base; it belongs to a chosen prime-discriminant factor `P`.
    obtain ⟨P, hP, hpP⟩ : ∃ P ∈ genusPrimeDiscriminants hd, p = primeDiscriminantPrime P := by
      rw [← hprod] at hdvd
      obtain ⟨P, hP, hpP⟩ := ((Nat.prime_iff_prime_int.mp hp).dvd_finsetProd_iff _).mp hdvd
      exact ⟨P, hP, (natCast_dvd_primeDiscriminant_iff (hs P hP) hp).mp hpP⟩
    -- The base is totally ramified at `p`: the absolute ramification index there is `2`.
    have he : 𝔭.ramificationIdx ℤ = 2 :=
      ramificationIdx_eq_two_of_dvd_fundamentalDiscriminant
        (minpoly_candidateGenusFieldBaseGen hd hnsq)
        (adjoin_candidateGenusFieldBaseGen_eq_top hd) hd hp hdvd
    -- Cancel that ramification against the transverse complementary compositum.
    refine TauCeti.RamificationInertia.isUnramifiedIn_of_finrank_le_of_under_ramificationIdx_eq_one
      (R := ℤ) (U := 𝓞 (candidateGenusFieldComplement hd ⟨P, hP⟩)) 𝔭 ?_ ?_
    · rw [he, ← IsFractionRing.finrank_eq (𝓞 (candidateGenusFieldComplement hd ⟨P, hP⟩))
        (candidateGenusFieldComplement hd ⟨P, hP⟩) (𝓞 (candidateGenusField hd))
        (candidateGenusField hd)]
      exact (finrank_candidateGenusField_over_candidateGenusFieldComplement hd ⟨P, hP⟩).le
    · intro r _ hr
      have : r.LiesOver 𝔭 := hr
      have hrp : r.LiesOver (Ideal.span {(p : ℤ)}) := Ideal.LiesOver.trans r 𝔭 _
      have hur : (r.under (𝓞 (candidateGenusFieldComplement hd ⟨P, hP⟩))).LiesOver
          (Ideal.span {(p : ℤ)}) := ⟨by rw [Ideal.under_under]; exact hrp.over⟩
      have hunr := isUnramifiedIn_candidateGenusFieldComplement_omittedPrime hd ⟨P, hP⟩
      rw [← hpP] at hunr
      exact hunr.ramificationIdx_eq_one hur
  · -- `p` is unramified in the candidate genus field already over `ℚ`.
    refine TauCeti.RamificationInertia.isUnramifiedIn_of_forall_ramificationIdx_le (R := ℤ) 𝔭 ?_
    intro r _ hr
    have : r.LiesOver 𝔭 := hr
    have hrp : r.LiesOver (Ideal.span {(p : ℤ)}) := Ideal.LiesOver.trans r 𝔭 _
    rw [((isUnramifiedIn_candidateGenusField_iff hd hp).mpr hdvd).ramificationIdx_eq_one hrp]
    exact 𝔭.ramificationIdx_pos ℤ

/-- **The candidate genus field is unramified over `ℚ(√d)` at every finite place.** For squarefree
`d` that is not a rational square, every prime of the ring of integers of the embedded base
`ℚ(√d)` is unramified in the ring of integers of `candidateGenusField hd`.

This is the finite-place half of the genus-field property of `candidateGenusField hd`. -/
theorem isUnramifiedIn_candidateGenusField (hd : Squarefree d) (hnsq : ¬ IsSquare ((d : ℤ) : ℚ))
    (𝔭 : Ideal (𝓞 (candidateGenusFieldBase hd))) [𝔭.IsPrime] :
    Algebra.IsUnramifiedIn (𝓞 (candidateGenusField hd)) 𝔭 := by
  have hunder : (Ideal.under ℤ 𝔭).IsPrime := inferInstance
  rcases Ideal.isPrime_int_iff.mp hunder with hbot | ⟨p, hp, hspan⟩
  · -- A prime of `𝓞 K` contracting to `⊥` is itself `⊥`, where there is nothing to ramify.
    have h𝔭 : 𝔭 = ⊥ := by
      by_contra hne
      exact Ideal.IsIntegral.comap_ne_bot (R := ℤ) hne hbot
    subst h𝔭
    exact Algebra.isUnramifiedIn_bot
  · have : 𝔭.LiesOver (Ideal.span {(p : ℤ)}) := ⟨hspan.symm⟩
    exact isUnramifiedIn_candidateGenusField_of_liesOver hd hnsq hp 𝔭

end TauCeti.Multiquadratic
