/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.WeilDivisor.Basic
public import Mathlib.Algebra.Group.Subgroup.Lattice
import Mathlib.Algebra.Group.Finsupp
import Mathlib.Tactic.Abel

/-!
# Point differences generate the degree-zero divisor group

For a fixed base point `x₀`, this file proves that the degree-zero Weil divisors are exactly the
integer combinations of the point differences `[x] - [x₀]`, and records the underlying closed
form: every divisor `D` satisfies

`D - (degree D) • [x₀] = Σ_x D(x) • ([x] - [x₀])`,

so a divisor of degree zero is `Σ_x D(x) • ([x] - [x₀])`. Taking the subgroup generated by the
point differences, this says

`degreeZeroSubgroup X = AddSubgroup.closure { [x] - [x₀] | x }`.

The weighted analogue, using the degree-corrected point divisors `[x] - w(x) • [x₀]` of
`WeilDivisor.weightedPointBaseDifference`, holds whenever the base point has weight one:

`weightedDegreeZeroSubgroup w = AddSubgroup.closure { [x] - w(x) • [x₀] | x }`.

The weighted statements are the general form; the unweighted API is derived from it by specializing
to the constant weight `w = fun _ => 1`, where `weightedPointBaseDifference` collapses to
`pointDifference` and `weightedDegree` to `degree`.

This is the formal-divisor shadow of the geometric fact that, over a field with a chosen rational
point `x₀`, the Abel-Jacobi map on symmetric powers surjects onto `Pic⁰`: a degree-zero divisor
class is a sum of the classes of `[x] - [x₀]`. It is the combinatorial input to that surjectivity,
available at the free Weil-divisor level before line bundles, principal divisors, the Picard
scheme, or the Jacobian variety exist.

This advances `TauCetiRoadmap/JacobianChallenge/README.md`, Layer A, "Divisors on a curve: Weil
divisors `⊕_x ℤ`", "Degree", and "`Pic⁰ X = ker deg` (as an abstract group)", and feeds the
Layer D/F Abel-map prerequisite `D ↦ 𝒪_X(D - d·x₀)`. No external mathematics is vendored; the
proofs reuse Tau Ceti's `WeilDivisor` API and Mathlib's finitely-supported induction and subgroup
`closure` machinery.
-/

public section

namespace TauCeti

namespace AlgebraicGeometry

namespace WeilDivisor

variable {X : Type*}

noncomputable section

/-! ### Weighted version -/

/-- The weighted closed form: subtracting `(weightedDegree w D) • [x₀]` from `D` expresses it as
the finite sum of the degree-corrected point divisors `D(x) • ([x] - w(x) • [x₀])`. -/
@[simp]
lemma sum_zsmul_weightedPointBaseDifference (w : X → ℤ) (x₀ : X) (D : WeilDivisor X) :
    (D.sum fun x n => n • weightedPointBaseDifference w x₀ x) =
      D - weightedDegree w D • ofPoint x₀ := by
  induction D using Finsupp.induction_linear with
  | zero => simp
  | add f g hf hg =>
    rw [Finsupp.sum_add_index' (fun a => by simp) (fun a b₁ b₂ => add_smul b₁ b₂ _),
      hf, hg, weightedDegree_add, add_smul]
    abel
  | single a b =>
    rw [Finsupp.sum_single_index (by simp), weightedPointBaseDifference_eq_ofPoint_sub_zsmul,
      single_eq_zsmul_ofPoint, map_zsmul, weightedDegree_ofPoint, smul_eq_mul, mul_smul,
      smul_sub]

/-- A divisor of weighted degree zero is the finite integer combination
`Σ_x D(x) • ([x] - w(x) • [x₀])` of degree-corrected point divisors based at `x₀`. -/
lemma eq_sum_zsmul_weightedPointBaseDifference (w : X → ℤ) {D : WeilDivisor X}
    (hD : weightedDegree w D = 0) (x₀ : X) :
    D = D.sum fun x n => n • weightedPointBaseDifference w x₀ x := by
  rw [sum_zsmul_weightedPointBaseDifference, hD, zero_smul, sub_zero]

/-- The degree-corrected representative `D - (weightedDegree w D) • [x₀]` lies in the subgroup
generated by the degree-corrected point divisors: it is the finite sum of the generators
`D(x) • ([x] - w(x) • [x₀])`, each of which is a multiple of a generator. -/
private lemma sub_weightedDegree_zsmul_ofPoint_mem_closure (w : X → ℤ) (x₀ : X)
    (D : WeilDivisor X) :
    D - weightedDegree w D • ofPoint x₀ ∈
      AddSubgroup.closure (Set.range fun x => weightedPointBaseDifference w x₀ x) := by
  rw [← sum_zsmul_weightedPointBaseDifference w x₀ D]
  simp only [Finsupp.sum]
  refine sum_mem fun x _ => ?_
  refine zsmul_mem ?_ (D x)
  exact AddSubgroup.subset_closure ⟨x, rfl⟩

/-- **The weighted degree-zero divisors are generated by the degree-corrected point divisors
`[x] - w(x) • [x₀]`.**  When the base point has weight one (the residue-field degree of a
`k`-rational point is one), the weighted degree-zero subgroup is generated by all the
`weightedPointBaseDifference w x₀ x`.  The weight-one hypothesis is what puts the generators inside
the subgroup; without it the generators need not have weighted degree zero. -/
theorem weightedDegreeZeroSubgroup_eq_closure_weightedPointBaseDifference
    (w : X → ℤ) {x₀ : X} (hx₀ : w x₀ = 1) :
    weightedDegreeZeroSubgroup w =
      AddSubgroup.closure (Set.range fun x => weightedPointBaseDifference w x₀ x) := by
  apply le_antisymm
  · intro D hD
    have h := sub_weightedDegree_zsmul_ofPoint_mem_closure w x₀ D
    rwa [(mem_weightedDegreeZeroSubgroup w D).mp hD, zero_smul, sub_zero] at h
  · rw [AddSubgroup.closure_le]
    rintro _ ⟨x, rfl⟩
    exact weightedPointBaseDifference_mem_weightedDegreeZeroSubgroup hx₀ x

/-! ### Unweighted version

The unweighted statements are the constant-weight `w = fun _ => 1` specialization of the weighted
API above, where `weightedPointBaseDifference (fun _ => 1) x₀ x = pointDifference x x₀` and
`weightedDegree (fun _ => 1) = degree`. -/

/-- The closed form for the base-point correction: subtracting `(degree D) • [x₀]` from `D`
expresses it as the finite sum of `D(x) • ([x] - [x₀])`.  Because the coefficients of `D` sum to
`degree D`, the base-point contributions collapse to a single `(degree D) • [x₀]` term. -/
@[simp]
lemma sum_zsmul_pointDifference (x₀ : X) (D : WeilDivisor X) :
    (D.sum fun x n => n • pointDifference x x₀) = D - degree D • ofPoint x₀ := by
  rw [← weightedDegree_one_eq_degree, ← sum_zsmul_weightedPointBaseDifference (fun _ => 1) x₀ D]
  refine Finsupp.sum_congr fun x _ => ?_
  rw [weightedPointBaseDifference_eq_pointDifference]

/-- A divisor of degree zero is the finite integer combination `Σ_x D(x) • ([x] - [x₀])` of point
differences based at `x₀`.  This is the closed form of the Abel-Jacobi expansion of a degree-zero
divisor. -/
lemma eq_sum_zsmul_pointDifference {D : WeilDivisor X} (hD : degree D = 0) (x₀ : X) :
    D = D.sum fun x n => n • pointDifference x x₀ := by
  rw [sum_zsmul_pointDifference, hD, zero_smul, sub_zero]

/-- At the constant weight `1`, the weighted degree-zero subgroup is the unweighted one. -/
private lemma weightedDegreeZeroSubgroup_one :
    weightedDegreeZeroSubgroup (fun _ : X => (1 : ℤ)) = degreeZeroSubgroup X := by
  ext D
  rw [mem_weightedDegreeZeroSubgroup, mem_degreeZeroSubgroup, weightedDegree_one_eq_degree]

/-- **The degree-zero divisors are generated by the point differences `[x] - [x₀]`.**  For any base
point `x₀`, the unweighted degree-zero subgroup is the subgroup generated by all point differences
based at `x₀`.  This is the formal-divisor form of Abel-Jacobi surjectivity onto the degree-zero
Picard group. -/
theorem degreeZeroSubgroup_eq_closure_pointDifference (x₀ : X) :
    degreeZeroSubgroup X = AddSubgroup.closure (Set.range fun x => pointDifference x x₀) := by
  have h := weightedDegreeZeroSubgroup_eq_closure_weightedPointBaseDifference
    (fun _ : X => (1 : ℤ)) (x₀ := x₀) rfl
  rw [weightedDegreeZeroSubgroup_one] at h
  simpa only [weightedPointBaseDifference_eq_pointDifference] using h

end

end WeilDivisor

end AlgebraicGeometry

end TauCeti
