/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Analysis.SpecialFunctions.Exponential
public import Mathlib.Topology.Algebra.ContinuousMonoidHom
public import Mathlib.Topology.ContinuousMap.Units
public import TauCeti.Analysis.Normed.Algebra.Basic

/-!
# Banach-algebra exponentials as units

The exponential of an element of a complete normed rational algebra is invertible, with inverse
the exponential of its negation. This file packages that fact as a units-valued map
`TauCeti.expUnit : R → Rˣ`. For real algebras, it also bundles the exponential along a line as a
continuous one-parameter subgroup.

This is the Banach-algebra model for the exponential map of a Lie group. The later abstract
construction should recover `expUnit` when specialized to the Lie group `Rˣ`.

## Main definitions

* `TauCeti.expUnit`: `NormedSpace.exp x`, regarded as a unit of the algebra.
* `TauCeti.expUnitHom`: the continuous one-parameter subgroup generated by `x`.

## Main results

* `TauCeti.expUnit_coe`: coercing `expUnit x` back to the algebra gives `NormedSpace.exp x`.
* `TauCeti.continuous_expUnit`: the units-valued exponential is continuous.
* `TauCeti.expUnit_add_of_commute`: the exponential addition law as an equality of units.
* `TauCeti.expUnit_zero`, `TauCeti.expUnit_neg`: the identity and inverse laws.
* `TauCeti.expUnit_add_smul`: the one-parameter subgroup law as an equality of units.

## References

* [Lie groups and the Lie algebra correspondence roadmap](https://github.com/TauCetiProject/TauCetiRoadmap/blob/main/TauCetiRoadmap/RepresentationTheory/LieGroups/README.md),
  Deliverable A, Layer 0, "The matrix and circle shadows".
-/

public section

namespace TauCeti

open NormedSpace

section Rat

variable {R : Type*} [NormedRing R] [NormedAlgebra ℚ R] [CompleteSpace R]

/-- The exponential of an element of a complete normed rational algebra, regarded as a unit.

Invertibility follows from `NormedSpace.isUnit_exp`; `TauCeti.expUnit_neg` below identifies its
inverse with the unit represented by `NormedSpace.exp (-x)`. -/
noncomputable def expUnit (x : R) : Rˣ :=
  (isUnit_exp x).unit

/-- Coercing `expUnit x` to the algebra recovers `NormedSpace.exp x`. -/
@[simp]
theorem expUnit_coe (x : R) : (expUnit x : R) = exp x :=
  (isUnit_exp x).unit_spec

/-- The Banach-algebra exponential is continuous as a map into the group of units. -/
theorem continuous_expUnit : Continuous (expUnit : R → Rˣ) := by
  let f : C(R, R) := ⟨NormedSpace.exp, NormedSpace.exp_continuous⟩
  exact ContinuousMap.continuous_isUnit_unit (f := f) fun x => NormedSpace.isUnit_exp x

/-- The exponential addition law for commuting elements, lifted to the group of units. -/
theorem expUnit_add_of_commute {x y : R} (hxy : Commute x y) :
    expUnit (x + y) = expUnit x * expUnit y := by
  apply Units.ext
  simpa only [expUnit_coe, Units.val_mul] using exp_add_of_commute hxy

/-- The exponential of zero is the identity unit. -/
@[simp]
theorem expUnit_zero : expUnit (0 : R) = 1 := by
  apply Units.ext
  simp

/-- The exponential of a negation is the inverse unit. -/
@[simp]
theorem expUnit_neg (x : R) : expUnit (-x) = (expUnit x)⁻¹ := by
  apply Units.ext
  rw [← Ring.inverse_unit]
  simpa only [expUnit_coe] using (Ring.inverse_exp x).symm

end Rat

section Real

variable {R : Type*} [NormedRing R] [NormedAlgebra ℝ R] [CompleteSpace R]

attribute [local instance] TauCeti.normedAlgebraRatOfReal

/-- The one-parameter subgroup law lifted from the algebra to its group of units. -/
@[simp]
theorem expUnit_add_smul (x : R) (s t : ℝ) :
    expUnit ((s + t) • x) = expUnit (s • x) * expUnit (t • x) := by
  rw [add_smul]
  exact expUnit_add_of_commute (((Commute.refl x).smul_left s).smul_right t)

/-- The Banach-algebra exponential along the line through `x`, bundled as a continuous
homomorphism from the additive real line (written multiplicatively) to `Rˣ`. -/
noncomputable def expUnitHom (x : R) : ContinuousMonoidHom (Multiplicative ℝ) Rˣ where
  toFun t := expUnit (Multiplicative.toAdd t • x)
  map_one' := by simp
  map_mul' s t := expUnit_add_smul x (Multiplicative.toAdd s) (Multiplicative.toAdd t)
  continuous_toFun :=
    continuous_expUnit.comp (continuous_toAdd.smul continuous_const)

/-- Evaluating `expUnitHom x` at time `t` gives `expUnit (t • x)`. -/
@[simp]
theorem expUnitHom_apply (x : R) (t : ℝ) :
    expUnitHom x (Multiplicative.ofAdd t) = expUnit (t • x) :=
  (rfl)

end Real

end TauCeti
