/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Geometry.Lie.Exponential.Basic
public import TauCeti.Geometry.Lie.Exponential.OneParameter

/-!
# Compatibility between abstract and Banach-algebra exponentials

The abstract Lie-group exponential recovers the Banach-algebra exponential on `Rˣ`. Under the
canonical identification of its Lie algebra with `R`, the abstract one-parameter subgroup is
`TauCeti.expUnitHom`, and its time-one value is `TauCeti.expUnit`.

The tangent-space compatibility holds for every complete normed real algebra. The final
derivation-based statements additionally assume finite-dimensionality, as required by the
derivation--tangent-space equivalence used to define the abstract exponential.

## Main results

* `mulInvariantOneParameterSubgroup_eq_expUnitHom`: the tangent-space constructions coincide.
* `oneParameterSubgroup_eq_expUnitHom`: the derivation-based subgroups coincide.
* `lieExp_eq_expUnit`: the abstract and Banach-algebra exponentials coincide.

## References

* [Lie groups and the Lie algebra correspondence roadmap](https://github.com/TauCetiProject/TauCetiRoadmap/blob/main/TauCetiRoadmap/RepresentationTheory/LieGroups/README.md),
  Deliverable A, Layer 0, "The matrix and circle shadows".
-/

public section

open Manifold
open scoped ContDiff Manifold

noncomputable section

attribute [local instance] TauCeti.normedAlgebraRatOfReal

section Complete

variable {R : Type*} [NormedRing R] [NormedAlgebra ℝ R] [CompleteSpace R]

/-- The canonical invariant subgroup on `Rˣ` generated by `x` has initial velocity `x` in the
ambient algebra. -/
theorem hasDerivAt_mulInvariantOneParameterSubgroup_val_zero (x : R) :
    HasDerivAt
      (fun t : ℝ =>
        (mulInvariantOneParameterSubgroup
          (I := 𝓘(ℝ, R)) (G := Rˣ) (x : GroupLieAlgebra 𝓘(ℝ, R) Rˣ)
          (Multiplicative.ofAdd t) : R)) x 0 := by
  let v : GroupLieAlgebra 𝓘(ℝ, R) Rˣ := x
  have hfun :
      (fun t : ℝ =>
        (mulInvariantOneParameterSubgroup v (Multiplicative.ofAdd t) : R)) =
        fun t : ℝ =>
          (mulInvariantIntegralCurve (I := 𝓘(ℝ, R)) (G := Rˣ) v (1 : Rˣ) t : R) := by
    funext t
    exact congrArg Units.val
      (mulInvariantOneParameterSubgroup_apply (I := 𝓘(ℝ, R)) (G := Rˣ) v t)
  have hd := hasDerivAt_extChartAt_mulInvariantIntegralCurve_zero
    (I := 𝓘(ℝ, R)) (G := Rˣ) x
  have hchart :
      (extChartAt 𝓘(ℝ, R) (1 : Rˣ)) ∘
          mulInvariantIntegralCurve (I := 𝓘(ℝ, R)) (G := Rˣ) v 1 =
        fun t => (mulInvariantIntegralCurve
          (I := 𝓘(ℝ, R)) (G := Rˣ) v 1 t : R) := by
    funext t
    simp only [extChartAt_coe, Function.comp_apply, Units.chartAt_apply,
      modelWithCornersSelf_coe, id]
  rw [hchart] at hd
  dsimp only [v] at hd
  rw [hfun]
  exact hd

/-- Under the tangent-space identification of `Lie(Rˣ)` with `R`, the canonical invariant subgroup
is the Banach-algebra exponential subgroup. -/
@[simp]
theorem mulInvariantOneParameterSubgroup_eq_expUnitHom (x : R) :
    mulInvariantOneParameterSubgroup
      (I := 𝓘(ℝ, R)) (G := Rˣ) (x : GroupLieAlgebra 𝓘(ℝ, R) Rˣ) =
      TauCeti.expUnitHom x := by
  apply TauCeti.continuousMonoidHom_eq_expUnitHom_of_hasDerivAt _ x
  exact hasDerivAt_mulInvariantOneParameterSubgroup_val_zero x

end Complete

section FiniteDimensional

variable {R : Type*} [NormedRing R] [NormedAlgebra ℝ R] [FiniteDimensional ℝ R]

noncomputable local instance finiteDimensionalCompleteSpace : CompleteSpace R :=
  FiniteDimensional.complete ℝ R

/-- The canonical identification of the Lie algebra of `Rˣ` with the ambient real algebra. -/
noncomputable def unitsLieAlgebraEquiv :
    LeftInvariantDerivation 𝓘(ℝ, R) Rˣ ≃ₗ[ℝ] R :=
  leftInvariantDerivationEquivGroupLieAlgebra (I := 𝓘(ℝ, R)) (G := Rˣ)
    BoundarylessManifold.isInteriorPoint

/-- The units Lie-algebra equivalence is the general derivation--tangent equivalence specialized
to the boundaryless manifold `Rˣ`. -/
@[simp]
theorem unitsLieAlgebraEquiv_apply (X : LeftInvariantDerivation 𝓘(ℝ, R) Rˣ) :
    unitsLieAlgebraEquiv X =
      leftInvariantDerivationEquivGroupLieAlgebra (I := 𝓘(ℝ, R)) (G := Rˣ)
        BoundarylessManifold.isInteriorPoint X := by
  rw [unitsLieAlgebraEquiv]
  rfl

/-- The abstract one-parameter subgroup on `Rˣ` is the Banach-algebra exponential subgroup. -/
@[simp]
theorem oneParameterSubgroup_eq_expUnitHom (X : LeftInvariantDerivation 𝓘(ℝ, R) Rˣ) :
    oneParameterSubgroup X =
      TauCeti.expUnitHom (R := R) (unitsLieAlgebraEquiv X) := by
  rw [oneParameterSubgroup_eq_mulInvariantOneParameterSubgroup]
  exact mulInvariantOneParameterSubgroup_eq_expUnitHom (unitsLieAlgebraEquiv X)

/-- The abstract Lie-group exponential on `Rˣ` is the Banach-algebra exponential packaged as a
unit. -/
@[simp]
theorem lieExp_eq_expUnit (X : LeftInvariantDerivation 𝓘(ℝ, R) Rˣ) :
    lieExp X = TauCeti.expUnit (R := R) (unitsLieAlgebraEquiv X) := by
  have h := congrArg (fun φ : ContinuousMonoidHom (Multiplicative ℝ) Rˣ =>
    φ (Multiplicative.ofAdd 1)) (oneParameterSubgroup_eq_expUnitHom X)
  simpa only [oneParameterSubgroup_apply, one_smul, TauCeti.expUnitHom_apply] using h

end FiniteDimensional
