/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RingTheory.ClassGroup.ExtendedHom
public import TauCeti.RingTheory.ClassGroup.HeightOneSpectrum
public import TauCeti.GroupTheory.QuotientGroup.KerEquiv
public import TauCeti.RingTheory.DedekindDomain.SInteger.Factorization

/-!
# The class group of the `S`-integers

For a Dedekind domain `R` with fraction field `K` and a set `S` of height one primes, the class
group of the ring `𝒪_S` of `S`-integers is the class group of `R` modulo the classes of the primes
in `S`:

`IsDedekindDomain.integerClassGroupEquiv : ClassGroup 𝒪_S ≃* ClassGroup R ⧸ ⟨[v] : v ∈ S⟩`.

## Main definitions

* `IsDedekindDomain.integerClassGroupEquiv`: the isomorphism above.

## Main results

* `IsDedekindDomain.finite_integer_classGroup`: `Cl(𝒪_S)` is finite whenever `Cl(R)` is.
* `IsDedekindDomain.integer_extendedHom_mk0_idealUnder`: the class of `I` is extended from the
  class of
  its contraction — the explicit preimage witnessing surjectivity, so a consumer holding a concrete
  `I` need not go through `Exists.choose`.
* `IsDedekindDomain.integerClassGroupEquiv_symm_mk`, `..._extendedHom` and `..._mk0`: how the
  isomorphism evaluates, on a class extended from `Cl(R)` and on a concrete `ClassGroup.mk0`.

The proof is the first isomorphism theorem applied to extension of ideals `Cl(R) → Cl(𝒪_S)`:

* `IsDedekindDomain.integer_extendedHom_surjective`: extension is surjective, because every ideal
  of `𝒪_S` is extended from `R` (`integer_map_comap_eq`);
* `IsDedekindDomain.ker_integer_extendedHom`: its kernel is generated by the classes of the primes
  in `S`. One inclusion is that a prime of `S` extends to `⊤` (`integer_map_asIdeal_eq_top`); the
  other compares multiplicities off `S`, which is what
  `IsDedekindDomain.integer_count_coeIdeal_map` and
  `IsDedekindDomain.integer_count_spanSingleton` supply — they are in
  `TauCeti/RingTheory/DedekindDomain/SInteger/Factorization.lean`, since neither mentions the class
  group — and then applies `ClassGroup.mk0_mem_closure_of_count_eq`.

`IsDedekindDomain.finite_integer_classGroup` is the consequence the arithmetic wants: `Cl(𝒪_S)` is
finite whenever `Cl(R)` is, being a quotient of it. That is one of the two finiteness inputs to
weak Mordell–Weil (the other being the `S`-unit theorem), so this advances
`TauCetiRoadmap/EllipticCurves/README.md` §Layer 6 (Mordell–Weil), whose Kummer argument needs
`E(K)/2E(K)` finite.

Adapted from Michael Stoll's elliptic-curves formalisation
(`github.com/MichaelStollBayreuth/EllipticCurves`, `EllipticCurves/Mathlib/SIntegers.lean` at the
roadmap's pin `66889eada51a`, Apache 2.0, by Michael Stoll). Following this repository's
convention for adapted material, the upstream authorship is credited here rather than in the
copyright header. Stoll's unprefixed names are given the `integer` prefix that
`TauCeti/RingTheory/DedekindDomain/SInteger/` already uses.
-/

public section

open IsDedekindDomain FractionalIdeal
open scoped nonZeroDivisors

namespace IsDedekindDomain

variable {R : Type*} [CommRing R] [IsDedekindDomain R] (K : Type*) [Field K] [Algebra R K]
  [IsFractionRing R K] (S : Set (HeightOneSpectrum R))

/-- **The explicit preimage under extension:** the class of `I` is extended from the class of the
contraction of `I` to `R`. Every ideal of `𝒪_S` is generated by its contraction
(`integer_map_comap_eq`), so extending the contraction returns `I`.

This is the content of `integer_extendedHom_surjective`, stated rather than hidden inside an
existential: a consumer holding a concrete `I` can name its preimage instead of recovering it from
`Exists.choose`. -/
lemma integer_extendedHom_mk0_idealUnder (I : (Ideal (S.integer K))⁰) :
    ClassGroup.extendedHom R (S.integer K) (ClassGroup.mk0 (integerIdealUnder K S I)) =
      ClassGroup.mk0 I := by
  rw [ClassGroup.extendedHom_mk0]
  exact congrArg _ (Subtype.ext (integer_map_comap_eq K S _))

/-- Extension of ideals `Cl(R) → Cl(𝒪_S)` is surjective. -/
lemma integer_extendedHom_surjective :
    Function.Surjective (ClassGroup.extendedHom R (S.integer K)) := by
  intro c
  obtain ⟨I, rfl⟩ := ClassGroup.mk0_surjective c
  exact ⟨_, integer_extendedHom_mk0_idealUnder K S I⟩

/-- The class group of `𝒪_S` is finite as soon as that of `R` is, being a quotient of it. This is
one of the two finiteness inputs to weak Mordell–Weil. -/
instance finite_integer_classGroup [Finite (ClassGroup R)] : Finite (ClassGroup (S.integer K)) :=
  .of_surjective _ (integer_extendedHom_surjective K S)

/-- The classes of the primes in `S` lie in the kernel of extension: such primes extend to `⊤`. -/
private lemma closure_le_ker_integer_extendedHom :
    Subgroup.closure (HeightOneSpectrum.classGroupMk '' S) ≤
      (ClassGroup.extendedHom R (S.integer K)).ker := by
  rw [Subgroup.closure_le]
  rintro _ ⟨v, hv, rfl⟩
  rw [SetLike.mem_coe, MonoidHom.mem_ker, HeightOneSpectrum.classGroupMk_eq_mk0,
    ClassGroup.extendedHom_mk0]
  refine (ClassGroup.mk0_eq_one_iff _).mpr ?_
  simpa only [integer_map_asIdeal_eq_top K S hv] using top_isPrincipal

/-- The kernel of extension of ideal classes to `𝒪_S` is contained in the subgroup generated by
the classes of the primes in `S`. -/
private lemma ker_integer_extendedHom_le :
    (ClassGroup.extendedHom R (S.integer K)).ker ≤
      Subgroup.closure (HeightOneSpectrum.classGroupMk '' S) := by
  intro c hc
  obtain ⟨J, rfl⟩ := ClassGroup.mk0_surjective c
  rw [MonoidHom.mem_ker, ClassGroup.extendedHom_mk0, ← ClassGroup.mk_mk0 K,
    ClassGroup.mk_eq_one_iff_exists] at hc
  obtain ⟨x, hx⟩ := hc
  have hxval : spanSingleton (S.integer K)⁰ (x : K) =
      ((Ideal.map (algebraMap R (S.integer K)) (J : Ideal R) : Ideal (S.integer K)) :
        FractionalIdeal (S.integer K)⁰ K) := by
    have h := congrArg Units.val hx
    rwa [coe_toPrincipalIdeal, FractionalIdeal.coe_mk0] at h
  refine ClassGroup.mk0_mem_closure_of_count_eq K (x := x) fun v hv ↦ ?_
  rw [← integer_count_coeIdeal_map K S hv, ← hxval,
    integer_count_spanSingleton K S hv]

/-- The kernel of extension is exactly the subgroup generated by the classes of the primes in
`S`. -/
lemma ker_integer_extendedHom :
    (ClassGroup.extendedHom R (S.integer K)).ker =
      Subgroup.closure (HeightOneSpectrum.classGroupMk '' S) :=
  le_antisymm (ker_integer_extendedHom_le K S) (closure_le_ker_integer_extendedHom K S)

/-- **The class group of the `S`-integers.** `Cl(𝒪_S)` is `Cl(R)` modulo the classes of the primes
in `S`: the first isomorphism theorem applied to extension of ideals. -/
noncomputable def integerClassGroupEquiv :
    ClassGroup (S.integer K) ≃*
      ClassGroup R ⧸ Subgroup.closure (HeightOneSpectrum.classGroupMk '' S) :=
  (QuotientGroup.quotientKerEquivOfSurjective _ (integer_extendedHom_surjective K S)).symm.trans
    (QuotientGroup.quotientMulEquivOfEq (ker_integer_extendedHom K S))

/-- `integerClassGroupEquiv` in the stated direction: the class extended from `c : Cl(R)` maps to
the class of `c` in the quotient. -/
@[simp] lemma integerClassGroupEquiv_extendedHom (c : ClassGroup R) :
    integerClassGroupEquiv K S (ClassGroup.extendedHom R (S.integer K) c) =
      QuotientGroup.mk c := by
  have hinner : (QuotientGroup.quotientKerEquivOfSurjective
      (ClassGroup.extendedHom R (S.integer K)) (integer_extendedHom_surjective K S)).symm
        (ClassGroup.extendedHom R (S.integer K) c) = QuotientGroup.mk c :=
    (MulEquiv.symm_apply_eq _).mpr
      (TauCeti.QuotientGroup.quotientKerEquivOfSurjective_apply_mk _ _ c).symm
  simp only [integerClassGroupEquiv, MulEquiv.trans_apply, hinner,
    QuotientGroup.quotientMulEquivOfEq_mk]

/-- `integerClassGroupEquiv` inverts extension: the class of `c` in the quotient corresponds to the
class extended from `c : Cl(R)`. The `symm` counterpart of `integerClassGroupEquiv_extendedHom`. -/
@[simp] lemma integerClassGroupEquiv_symm_mk (c : ClassGroup R) :
    (integerClassGroupEquiv K S).symm (QuotientGroup.mk c) =
      ClassGroup.extendedHom R (S.integer K) c :=
  (MulEquiv.symm_apply_eq _).mpr (integerClassGroupEquiv_extendedHom K S c).symm

/-- `integerClassGroupEquiv` evaluated on a concrete ideal: the class of `I` corresponds to the
class of the contraction of `I` to `R`. This is the evaluation to use when the argument is
literally a `ClassGroup.mk0`; `integerClassGroupEquiv_extendedHom` is the one phrased through
extension. -/
@[simp] lemma integerClassGroupEquiv_mk0 (I : (Ideal (S.integer K))⁰) :
    integerClassGroupEquiv K S (ClassGroup.mk0 I) =
      QuotientGroup.mk (ClassGroup.mk0 (integerIdealUnder K S I)) := by
  rw [← integer_extendedHom_mk0_idealUnder K S I, integerClassGroupEquiv_extendedHom]

end IsDedekindDomain

end
