/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.Multiquadratic.CandidateGenusField.Degree
public import TauCeti.NumberTheory.Multiquadratic.Prime.Discriminant.GaloisGroup

/-!
# Galois group of the candidate genus field

For a squarefree integer `d`, `candidateGenusField hd` is generated over `ℚ` by the chosen square
roots of the radicands of the prime discriminants in `genusPrimeDiscriminants hd`. This file proves
that the resulting extension is abelian Galois and identifies its Galois group with

`Multiplicative ({P // P ∈ genusPrimeDiscriminants hd} → ZMod 2)`.

The isomorphism records the sign by which an automorphism acts on each chosen root. The
prime-discriminant factorization contains at most one even prime discriminant, so the radicands
are square-class independent and all sign patterns occur. In particular, the Galois group has
order `2 ^ (genusPrimeDiscriminants hd).card`.

This supplies the Galois and abelian parts of the multiquadratic description of the candidate
genus field. Identifying this candidate with the maximal extension satisfying the genus-field
ramification conditions, and identifying its relative Galois group with `Cl/Cl²`, remain later
work.

The prime-discriminant description of the genus field is classical; see D. A. Cox,
*Primes of the Form x² + ny²*, and F. Lemmermeyer, *Reciprocity Laws*.

## Main results

* `TauCeti.Multiquadratic.isAbelianGalois_candidateGenusField`: the candidate genus field is an
  abelian Galois extension of `ℚ`.
* `TauCeti.Multiquadratic.galoisGroupEquivCandidateGenusField`: its Galois group is the group of
  sign patterns on the chosen prime-discriminant roots.
* `TauCeti.Multiquadratic.card_aut_candidateGenusField`: the Galois group has order `2` to the
  number of prime discriminants in the chosen factorization.
-/

public section

open IntermediateField

namespace TauCeti.Multiquadratic

/-- The candidate genus field identified with its presentation as the field generated by the
chosen prime-discriminant roots. -/
noncomputable def candidateGenusFieldEquivAdjoin {d : ℤ} (hd : Squarefree d) :
    candidateGenusField hd ≃ₐ[ℚ] adjoin ℚ (Set.range (genusFieldRoot hd)) :=
  IntermediateField.equivOfEq (candidateGenusField_def hd)

/-- Each chosen complex root squares to the rational radicand of its prime discriminant. -/
theorem genusFieldRoot_sq_algebraMap {d : ℤ} (hd : Squarefree d)
    (P : {P // P ∈ genusPrimeDiscriminants hd}) :
    genusFieldRoot hd P ^ 2 =
      algebraMap ℚ ℂ (((primeDiscriminantRadicand P.val : ℤ) : ℚ)) := by
  simp

private theorem genusPrimeDiscriminants_not_all_three_even {d : ℤ} (hd : Squarefree d) :
    ¬ ((∃ P : {P // P ∈ genusPrimeDiscriminants hd}, P.val = -4) ∧
      (∃ P : {P // P ∈ genusPrimeDiscriminants hd}, P.val = 8) ∧
        (∃ P : {P // P ∈ genusPrimeDiscriminants hd}, P.val = -8)) :=
  not_all_three_evenPrimeDiscriminants_of_forall_isEvenPrimeDiscriminant_eq
    (fun P Q hP hQ =>
      (genusPrimeDiscriminants_spec hd).2.1
        P.val P.property Q.val Q.property hP hQ)

/-- The presentation equivalence sends each candidate-genus-field generator to the corresponding
generator of the adjoin presentation. -/
@[simp] theorem candidateGenusFieldEquivAdjoin_apply_gen {d : ℤ} (hd : Squarefree d)
    (P : {P // P ∈ genusPrimeDiscriminants hd}) :
    candidateGenusFieldEquivAdjoin hd (candidateGenusFieldGen hd P) =
      gen (genusFieldRoot hd) P := by
  apply Subtype.ext
  exact candidateGenusFieldGen_val hd P

private theorem candidateGenusField_autCongr_fixes_gen_iff {d : ℤ} (hd : Squarefree d)
    (σ : candidateGenusField hd ≃ₐ[ℚ] candidateGenusField hd)
    (P : {P // P ∈ genusPrimeDiscriminants hd}) :
    (AlgEquiv.autCongr (candidateGenusFieldEquivAdjoin hd) σ)
          (gen (genusFieldRoot hd) P) = gen (genusFieldRoot hd) P ↔
      σ (candidateGenusFieldGen hd P) = candidateGenusFieldGen hd P := by
  rw [← candidateGenusFieldEquivAdjoin_apply_gen]
  simp only [AlgEquiv.autCongr_apply, AlgEquiv.trans_apply, AlgEquiv.symm_apply_apply,
    (candidateGenusFieldEquivAdjoin hd).injective.eq_iff]

/-- The sign pattern of an automorphism of the candidate genus field, obtained by transporting
the automorphism to the presentation generated by `genusFieldRoot` and recording its action on
each chosen root. -/
noncomputable def candidateGenusFieldSignPattern {d : ℤ} (hd : Squarefree d)
    (σ : candidateGenusField hd ≃ₐ[ℚ] candidateGenusField hd) :
    {P // P ∈ genusPrimeDiscriminants hd} → ZMod 2 :=
  signPattern (genusFieldRoot hd)
    (AlgEquiv.autCongr (candidateGenusFieldEquivAdjoin hd) σ)

/-- The sign recorded at `P` is zero exactly when the automorphism fixes the corresponding
chosen generator. -/
@[simp] theorem candidateGenusFieldSignPattern_apply {d : ℤ} (hd : Squarefree d)
    (σ : candidateGenusField hd ≃ₐ[ℚ] candidateGenusField hd)
    (P : {P // P ∈ genusPrimeDiscriminants hd}) :
    candidateGenusFieldSignPattern hd σ P =
      if σ (candidateGenusFieldGen hd P) = candidateGenusFieldGen hd P then 0 else 1 := by
  simp only [candidateGenusFieldSignPattern, signPattern]
  congr 1
  exact propext (candidateGenusField_autCongr_fixes_gen_iff hd σ P)

/-- **The Galois group of the candidate genus field is the group of sign patterns.** An
automorphism is sent to the function recording whether it fixes or negates each chosen
prime-discriminant root. Square-class independence makes this map bijective. -/
noncomputable def galoisGroupEquivCandidateGenusField {d : ℤ} (hd : Squarefree d) :
    (candidateGenusField hd ≃ₐ[ℚ] candidateGenusField hd) ≃*
      Multiplicative ({P // P ∈ genusPrimeDiscriminants hd} → ZMod 2) :=
  (AlgEquiv.autCongr (candidateGenusFieldEquivAdjoin hd)).trans
    (galoisGroupEquivPrimeDiscriminantRadicands
      (fun P : {P // P ∈ genusPrimeDiscriminants hd} => P.val)
      (fun P => (genusPrimeDiscriminants_spec hd).1 P.val P.property)
      Subtype.val_injective (genusPrimeDiscriminants_not_all_three_even hd)
      (genusFieldRoot hd) (genusFieldRoot_sq_algebraMap hd))

/-- Transporting an automorphism supplied by the inverse sign-pattern equivalence back through
the adjoin presentation recovers the corresponding automorphism of that presentation. -/
private theorem candidateGenusFieldEquivAdjoin_galoisGroupEquivCandidateGenusField_symm_apply
    {d : ℤ}
    (hd : Squarefree d) (ε : {P // P ∈ genusPrimeDiscriminants hd} → ZMod 2)
    (x : candidateGenusField hd) :
    candidateGenusFieldEquivAdjoin hd
        (((galoisGroupEquivCandidateGenusField hd).symm (Multiplicative.ofAdd ε)) x) =
      ((galoisGroupEquivPrimeDiscriminantRadicands
        (fun P : {P // P ∈ genusPrimeDiscriminants hd} => P.val)
        (fun P => (genusPrimeDiscriminants_spec hd).1 P.val P.property)
        Subtype.val_injective (genusPrimeDiscriminants_not_all_three_even hd)
        (genusFieldRoot hd) (genusFieldRoot_sq_algebraMap hd)).symm
          (Multiplicative.ofAdd ε)) (candidateGenusFieldEquivAdjoin hd x) := by
  -- `galoisGroupEquivCandidateGenusField` is by definition the composite of `autCongr` along
  -- `candidateGenusFieldEquivAdjoin` with the prime-discriminant equivalence, so both sides are
  -- the same term. No rewrite reaches this goal: once the composite is unfolded, its
  -- `MulEquiv.trans` is type-correct only at default transparency, because the two `Mul` instances
  -- on the automorphism group — one coming from `candidateGenusField hd`, the other from its
  -- `adjoin` presentation — agree only by unfolding `candidateGenusField`. So `rw`/`simp` lemmas
  -- such as `MulEquiv.symm_trans_apply` fail to match, while `rfl` closes the goal.
  rfl

/-- The candidate-genus-field Galois equivalence sends an automorphism to its sign pattern on the
chosen prime-discriminant roots. -/
@[simp] theorem galoisGroupEquivCandidateGenusField_apply {d : ℤ} (hd : Squarefree d)
    (σ : candidateGenusField hd ≃ₐ[ℚ] candidateGenusField hd) :
    galoisGroupEquivCandidateGenusField hd σ =
      Multiplicative.ofAdd (candidateGenusFieldSignPattern hd σ) := by
  simp only [galoisGroupEquivCandidateGenusField, candidateGenusFieldSignPattern]
  exact galoisGroupEquivPrimeDiscriminantRadicands_apply
    (fun P : {P // P ∈ genusPrimeDiscriminants hd} => P.val)
    (fun P => (genusPrimeDiscriminants_spec hd).1 P.val P.property)
    Subtype.val_injective (genusPrimeDiscriminants_not_all_three_even hd)
    (genusFieldRoot hd) (genusFieldRoot_sq_algebraMap hd)
    (AlgEquiv.autCongr (candidateGenusFieldEquivAdjoin hd) σ)

/-- The inverse candidate-genus-field Galois equivalence realizes a sign pattern by sending each
chosen generator to `(-1)^(ε P)` times that generator. -/
@[simp] theorem galoisGroupEquivCandidateGenusField_symm_apply_gen {d : ℤ}
    (hd : Squarefree d) (ε : {P // P ∈ genusPrimeDiscriminants hd} → ZMod 2)
    (P : {P // P ∈ genusPrimeDiscriminants hd}) :
    ((galoisGroupEquivCandidateGenusField hd).symm (Multiplicative.ofAdd ε))
        (candidateGenusFieldGen hd P) = (-1) ^ (ε P).val * candidateGenusFieldGen hd P := by
  apply (candidateGenusFieldEquivAdjoin hd).injective
  rw [candidateGenusFieldEquivAdjoin_galoisGroupEquivCandidateGenusField_symm_apply, map_mul,
    map_pow, map_neg, map_one, candidateGenusFieldEquivAdjoin_apply_gen]
  exact galoisGroupEquivPrimeDiscriminantRadicands_symm_apply_gen
    (fun P : {P // P ∈ genusPrimeDiscriminants hd} => P.val)
    (fun P => (genusPrimeDiscriminants_spec hd).1 P.val P.property)
    Subtype.val_injective (genusPrimeDiscriminants_not_all_three_even hd)
    (genusFieldRoot hd) (genusFieldRoot_sq_algebraMap hd) ε P

/-- **The candidate genus field is abelian Galois over `ℚ`.** It is generated by square roots of
rational elements, so the field-generic multiquadratic abelian-Galois theorem applies. -/
noncomputable instance isAbelianGalois_candidateGenusField {d : ℤ} {hd : Squarefree d} :
    IsAbelianGalois ℚ (candidateGenusField hd) := by
  let : IsAbelianGalois ℚ (adjoin ℚ (Set.range (genusFieldRoot hd))) :=
    isAbelianGalois
      (d := fun P : {P // P ∈ genusPrimeDiscriminants hd} =>
        ((primeDiscriminantRadicand P.val : ℤ) : ℚ))
      (root := genusFieldRoot hd) (genusFieldRoot_sq_algebraMap hd)
  exact {
    toIsGalois := (candidateGenusFieldEquivAdjoin hd).transfer_galois.mpr inferInstance
    is_comm.comm σ τ := by
      apply (AlgEquiv.autCongr (candidateGenusFieldEquivAdjoin hd)).injective
      simpa only [map_mul] using
        IsMulCommutative.is_comm.comm
          (AlgEquiv.autCongr (candidateGenusFieldEquivAdjoin hd) σ)
          (AlgEquiv.autCongr (candidateGenusFieldEquivAdjoin hd) τ)
  }

/-- **Cardinality of the candidate-genus-field Galois group.** Its order is `2` to the number of
prime discriminants in the chosen factorization of `fundamentalDiscriminant d`. -/
theorem card_aut_candidateGenusField {d : ℤ} (hd : Squarefree d) :
    Nat.card (candidateGenusField hd ≃ₐ[ℚ] candidateGenusField hd) =
      2 ^ (genusPrimeDiscriminants hd).card := by
  rw [IsGalois.card_aut_eq_finrank, finrank_candidateGenusField]

end TauCeti.Multiquadratic
