/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.Multiquadratic.CandidateGenusField.Relative.Degree
public import TauCeti.NumberTheory.NumberField.InfinitePlace

/-!
# The candidate genus field of an imaginary quadratic field is totally complex

For squarefree `d < 0`, the embedded base `ℚ(√d)` inside `candidateGenusField hd` contains a square
root of the negative rational `d`, so it is totally complex — a special case of
`TauCeti.NumberField.isTotallyComplex_of_sq_ratCast_of_neg`. The candidate genus field, being an
extension of the base, is then totally complex too (`isTotallyComplex_of_algebra`).

A totally complex base has no real infinite places, so the candidate genus field is unramified at
every infinite place over its base (`IsUnramifiedAtInfinitePlaces`). This settles the archimedean
half of the genus-field identification in the imaginary case.

## Main results

* `TauCeti.Multiquadratic.isTotallyComplex_candidateGenusFieldBase`: the base `ℚ(√d)` is totally
  complex for `d < 0`.
* `TauCeti.Multiquadratic.isTotallyComplex_candidateGenusField`: so is the candidate genus field.
* `TauCeti.Multiquadratic.isUnramifiedAtInfinitePlaces_candidateGenusField`: for `d < 0` the
  candidate genus field is unramified at all infinite places over its base.
-/

public section

open NumberField NumberField.InfinitePlace

namespace TauCeti.Multiquadratic

variable {d : ℤ}

/-- **The quadratic base `ℚ(√d)` inside the candidate genus field is totally complex** for
squarefree `d < 0`: it is generated by a square root of the negative rational `d`. -/
theorem isTotallyComplex_candidateGenusFieldBase (hd : Squarefree d) (hneg : d < 0) :
    IsTotallyComplex (candidateGenusFieldBase hd) := by
  refine TauCeti.NumberField.isTotallyComplex_of_sq_ratCast_of_neg
    (x := (⟨candidateGenusFieldBaseRoot hd, candidateGenusFieldBaseRoot_mem hd⟩ :
      candidateGenusFieldBase hd)) (r := ((d : ℤ) : ℚ)) ?_ (by exact_mod_cast hneg)
  apply Subtype.ext
  push_cast
  exact_mod_cast candidateGenusFieldBaseRoot_sq hd

/-- **The candidate genus field of an imaginary quadratic field is totally complex.** For squarefree
`d < 0` it is an extension of the totally complex base `ℚ(√d)`. -/
theorem isTotallyComplex_candidateGenusField (hd : Squarefree d) (hneg : d < 0) :
    IsTotallyComplex (candidateGenusField hd) :=
  haveI := isTotallyComplex_candidateGenusFieldBase hd hneg
  isTotallyComplex_of_algebra (candidateGenusFieldBase hd) (candidateGenusField hd)

/-- **The candidate genus field is unramified at the infinite places over its base**, for squarefree
`d < 0`. The base `ℚ(√d)` is totally complex, so no infinite place of it is real and hence none
ramifies. This is the archimedean half of the genus-field identification in the imaginary case. -/
theorem isUnramifiedAtInfinitePlaces_candidateGenusField (hd : Squarefree d) (hneg : d < 0) :
    IsUnramifiedAtInfinitePlaces (candidateGenusFieldBase hd) (candidateGenusField hd) :=
  haveI := isTotallyComplex_candidateGenusFieldBase hd hneg
  TauCeti.NumberField.IsUnramifiedAtInfinitePlaces_of_isTotallyComplex

end TauCeti.Multiquadratic
