/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.GroupTheory.SpecificGroups.Dihedral

/-!
# The dihedral groups: an enumeration, and a recognition criterion

`DihedralGroup n` is finite, but `Fintype` alone does not hand back a list of its elements, since
`Finset.toList` is noncomputable. This file writes that list down, and evaluates
`DihedralGroup.exponent` — which computes the exponent of `DihedralGroup n` as `lcm n 2` — at the
two orders the worked examples of the Burnside--Dixon--Schneider character-table algorithm are run
on.

It then proves the converse-facing statement, which Mathlib does not have: a group generated by two
involutions, *neither of them the identity*, is a dihedral group, of order twice the order of their
product. Every rank-two reflection group is presented to us in that shape, and this is what
identifies it.

## Main definitions

* `TauCeti.dihedralElements`: a computable enumeration of `DihedralGroup n`.
* `TauCeti.dihedralHom`: the homomorphism `DihedralGroup n →* G` attached to two involutions whose
  product has order `n`.
* `TauCeti.dihedralGroupMulEquiv`: that homomorphism as an isomorphism, when the two involutions
  generate `G` and neither is the identity.

## Main results

* `TauCeti.mem_dihedralElements`: that enumeration exhausts the group.
* `TauCeti.exponent_dihedralGroup_three`: `DihedralGroup 3`, of order `6`, has exponent `6`.
* `TauCeti.exponent_dihedralGroup_four`: `DihedralGroup 4`, of order `8`, has exponent `4`.
* `TauCeti.dihedralHom_bijective` and `TauCeti.nonempty_dihedralGroup_mulEquiv`: **a group generated
  by two involutions other than the identity is the dihedral group of order twice the order of
  their product.**
-/

public section

namespace TauCeti

/-- The rotations `r 0, …, r (n-1)` of `DihedralGroup n`, each followed by the corresponding
reflection. For `n ≠ 0` this lists all `2 * n` elements of the group, which is
`TauCeti.mem_dihedralElements`. The body is exposed because a kernel computation over the group —
such as the class data of `TauCeti.dihedralClassData` — has to reduce it. -/
@[expose] def dihedralElements (n : ℕ) : List (DihedralGroup n) :=
  (List.range n).flatMap fun i : ℕ => [DihedralGroup.r (i : ZMod n), DihedralGroup.sr (i : ZMod n)]

/-- The enumeration `TauCeti.dihedralElements` exhausts the dihedral group. -/
theorem mem_dihedralElements {n : ℕ} [NeZero n] (g : DihedralGroup n) : g ∈ dihedralElements n := by
  have hmem : ∀ i : ZMod n, i.val ∈ List.range n := fun i => List.mem_range.mpr (ZMod.val_lt i)
  cases g with
  | r i =>
    refine List.mem_flatMap.mpr ⟨i.val, hmem i, ?_⟩
    rw [ZMod.natCast_rightInverse i]
    simp
  | sr i =>
    refine List.mem_flatMap.mpr ⟨i.val, hmem i, ?_⟩
    rw [ZMod.natCast_rightInverse i]
    simp

/-- The dihedral group of order `6`, the symmetric group on three letters, has exponent `6`. -/
@[simp]
theorem exponent_dihedralGroup_three : Monoid.exponent (DihedralGroup 3) = 6 := by
  rw [DihedralGroup.exponent]
  decide

/-- The dihedral group of order `8` has exponent `4`. -/
@[simp]
theorem exponent_dihedralGroup_four : Monoid.exponent (DihedralGroup 4) = 4 := by
  rw [DihedralGroup.exponent]
  decide

/-! ## Recognizing a dihedral group

A group generated by two involutions `s` and `t`, neither of them the identity, is dihedral: its
rotation subgroup is generated by `c = s * t`, and its reflections are the elements `s * c ^ k`.
Turning that into an isomorphism means indexing the powers of `c` by `ZMod n`, where `n` is the
order of `c`; the index `i` is read as the integer `ZMod.cast i`, and `TauCeti.dihedralHom` is the
resulting homomorphism. Taking that representative in `ℤ` rather than in `ℕ` costs nothing and
covers the modulus `n = 0`, where `ZMod 0` is `ℤ` and an element of order `0` is one of infinite
order: the criterion then recognizes the infinite dihedral group.

The work is in injectivity. On the rotations it is the definition of the order of `c`. On the
reflections it is the observation that `s * c ^ k = 1` puts `s` inside the *abelian* subgroup
generated by `c`, so that `s` both inverts and centralizes `c`; then `c` is its own inverse, and the
parity of `k` makes `s` or `t` the identity. Both hypotheses `s ≠ 1` and `t ≠ 1` are therefore
needed: for `s = 1` the group is generated by the single involution `t` while `orderOf (s * t) = 2`,
so it is not the dihedral group of order `4`. -/

section Recognition

variable {G : Type*} [Group G] {n : ℕ} {c s t : G}

/-- The power of `c` at an integer representative of an index is the power at *any* integer
representative of it, once `c` has order `n`. -/
private lemma zpow_cast_eq_zpow (hc : orderOf c = n) {i : ZMod n} {k : ℤ} (h : (k : ZMod n) = i) :
    c ^ (ZMod.cast i : ℤ) = c ^ k := by
  rw [zpow_eq_zpow_iff_modEq, hc, ← ZMod.intCast_eq_intCast_iff, ZMod.intCast_zmod_cast, h]

private lemma zpow_cast_zero (c : G) : c ^ (ZMod.cast (0 : ZMod n) : ℤ) = 1 := by
  rw [ZMod.cast_zero, zpow_zero]

private lemma zpow_cast_one (hc : orderOf c = n) : c ^ (ZMod.cast (1 : ZMod n) : ℤ) = c := by
  rw [zpow_cast_eq_zpow hc (k := 1) Int.cast_one, zpow_one]

private lemma zpow_cast_add (hc : orderOf c = n) (i j : ZMod n) :
    c ^ (ZMod.cast (i + j) : ℤ) = c ^ (ZMod.cast i : ℤ) * c ^ (ZMod.cast j : ℤ) := by
  rw [zpow_cast_eq_zpow hc (k := (ZMod.cast i : ℤ) + (ZMod.cast j : ℤ))
      (by rw [Int.cast_add, ZMod.intCast_zmod_cast, ZMod.intCast_zmod_cast]), zpow_add]

private lemma zpow_cast_neg (hc : orderOf c = n) (i : ZMod n) :
    c ^ (ZMod.cast (-i) : ℤ) = (c ^ (ZMod.cast i : ℤ))⁻¹ := by
  rw [zpow_cast_eq_zpow hc (k := -(ZMod.cast i : ℤ))
      (by rw [Int.cast_neg, ZMod.intCast_zmod_cast]), zpow_neg]

/-- A power of `c` at an index is trivial exactly at the index `0`. -/
private lemma zpow_cast_eq_one_iff (hc : orderOf c = n) {i : ZMod n} :
    c ^ (ZMod.cast i : ℤ) = 1 ↔ i = 0 := by
  rw [← zpow_zero c, zpow_eq_zpow_iff_modEq, hc, ← ZMod.intCast_eq_intCast_iff,
    ZMod.intCast_zmod_cast, Int.cast_zero]

/-- Either of the two involutions inverts their product by conjugation. -/
private lemma conj_mul_eq_inv (hs : s * s = 1) (ht : t * t = 1) :
    s * (s * t) * s⁻¹ = (s * t)⁻¹ := by
  rw [mul_inv_rev, inv_eq_of_mul_eq_one_right ht, inv_eq_of_mul_eq_one_right hs, ← mul_assoc, hs,
    one_mul]

/-- Moving one of the two involutions across a rotation inverts the rotation. -/
private lemma zpow_cast_mul_eq (hs : s * s = 1) (ht : t * t = 1) (hn : orderOf (s * t) = n)
    (i : ZMod n) :
    (s * t) ^ (ZMod.cast i : ℤ) * s = s * (s * t) ^ (ZMod.cast (-i) : ℤ) := by
  have hsi : s⁻¹ = s := inv_eq_of_mul_eq_one_right hs
  have hkey : s * (s * t) ^ (ZMod.cast i : ℤ) * s⁻¹ = ((s * t) ^ (ZMod.cast i : ℤ))⁻¹ := by
    rw [← conj_zpow, conj_mul_eq_inv hs ht, inv_zpow]
  rw [zpow_cast_neg hn, ← hkey, hsi, ← mul_assoc, ← mul_assoc, hs, one_mul]

/-- The underlying function of `TauCeti.dihedralHom`. -/
private def dihedralFun (s c : G) : DihedralGroup n → G
  | .r i => c ^ (ZMod.cast i : ℤ)
  | .sr i => s * c ^ (ZMod.cast i : ℤ)

private lemma dihedralFun_r (s c : G) (i : ZMod n) :
    dihedralFun s c (.r i) = c ^ (ZMod.cast i : ℤ) := rfl

private lemma dihedralFun_sr (s c : G) (i : ZMod n) :
    dihedralFun s c (.sr i) = s * c ^ (ZMod.cast i : ℤ) := rfl

/-- The homomorphism out of the dihedral group determined by two involutions whose product has
order `n`: a rotation `r i` goes to `(s * t) ^ i`, and a reflection `sr i` to `s * (s * t) ^ i`,
the index `i` being read as an integer by `ZMod.cast`. These two values are
`TauCeti.dihedralHom_r` and `TauCeti.dihedralHom_sr`. -/
def dihedralHom (hs : s * s = 1) (ht : t * t = 1) (hn : orderOf (s * t) = n) :
    DihedralGroup n →* G where
  toFun := dihedralFun s (s * t)
  map_one' := by rw [DihedralGroup.one_def, dihedralFun_r, zpow_cast_zero]
  map_mul' := by
    rintro (i | i) (j | j)
    · rw [DihedralGroup.r_mul_r, dihedralFun_r, dihedralFun_r, dihedralFun_r, zpow_cast_add hn]
    · rw [DihedralGroup.r_mul_sr, dihedralFun_sr, dihedralFun_r, dihedralFun_sr, ← mul_assoc,
        zpow_cast_mul_eq hs ht hn, mul_assoc, ← zpow_cast_add hn, neg_add_eq_sub]
    · rw [DihedralGroup.sr_mul_r, dihedralFun_sr, dihedralFun_sr, dihedralFun_r,
        zpow_cast_add hn, mul_assoc]
    · rw [DihedralGroup.sr_mul_sr, dihedralFun_r, dihedralFun_sr, dihedralFun_sr, ← mul_assoc,
        mul_assoc s, zpow_cast_mul_eq hs ht hn, ← mul_assoc, hs, one_mul, ← zpow_cast_add hn,
        neg_add_eq_sub]

/-- `TauCeti.dihedralHom` sends the rotation `r i` to the power `(s * t) ^ i`. -/
@[simp]
theorem dihedralHom_r (hs : s * s = 1) (ht : t * t = 1) (hn : orderOf (s * t) = n) (i : ZMod n) :
    dihedralHom hs ht hn (.r i) = (s * t) ^ (ZMod.cast i : ℤ) := by
  unfold dihedralHom
  exact dihedralFun_r s (s * t) i

/-- `TauCeti.dihedralHom` sends the reflection `sr i` to `s * (s * t) ^ i`. -/
@[simp]
theorem dihedralHom_sr (hs : s * s = 1) (ht : t * t = 1) (hn : orderOf (s * t) = n) (i : ZMod n) :
    dihedralHom hs ht hn (.sr i) = s * (s * t) ^ (ZMod.cast i : ℤ) := by
  unfold dihedralHom
  exact dihedralFun_sr s (s * t) i

/-- **A group generated by two involutions other than the identity is dihedral.** If the
involutions `s` and `t` generate `G` and neither is the identity, then `TauCeti.dihedralHom`
identifies `G` with the dihedral group of order `2 * n`, where `n` is the order of `s * t`.

Mathlib has the dihedral groups but no criterion recognizing one, so this is proved here. -/
theorem dihedralHom_bijective (hs : s * s = 1) (ht : t * t = 1) (hs1 : s ≠ 1) (ht1 : t ≠ 1)
    (hn : orderOf (s * t) = n) (hgen : Subgroup.closure ({s, t} : Set G) = ⊤) :
    Function.Bijective (dihedralHom hs ht hn) := by
  constructor
  · rw [injective_iff_map_eq_one]
    rintro (i | i) hi
    · -- A rotation in the kernel has index a multiple of the order of `s * t`, hence index zero.
      rw [dihedralHom_r, zpow_cast_eq_one_iff hn] at hi
      rw [hi, DihedralGroup.r_zero]
    · -- A reflection in the kernel would put `s` in the centralizer of `s * t`.
      rw [dihedralHom_sr] at hi
      exfalso
      have hzpow : s = (s * t) ^ (-(ZMod.cast i : ℤ)) := by
        rw [zpow_neg, eq_inv_iff_mul_eq_one]
        exact hi
      have hcomm : Commute s (s * t) := by
        have hz : Commute ((s * t) ^ (-(ZMod.cast i : ℤ))) (s * t) :=
          (Commute.refl (s * t)).zpow_left _
        rwa [← hzpow] at hz
      have hinv : (s * t)⁻¹ = s * t := by
        rw [← conj_mul_eq_inv hs ht, hcomm.eq, mul_assoc, mul_inv_cancel, mul_one]
      have hsq : (s * t) ^ (2 : ℤ) = 1 := by
        rw [zpow_two]
        nth_rewrite 1 [← hinv]
        exact inv_mul_cancel _
      rcases Int.even_or_odd (-(ZMod.cast i : ℤ)) with ⟨m, hm⟩ | ⟨m, hm⟩
      · exact hs1 (by rw [hzpow, hm, ← two_mul, zpow_mul, hsq, one_zpow])
      · refine ht1 (mul_left_cancel (a := s) ?_)
        rw [mul_one]
        nth_rewrite 2 [hzpow]
        rw [hm, zpow_add, zpow_mul, hsq, one_zpow, one_mul, zpow_one]
  · -- Surjectivity: the range is a subgroup containing both generators.
    rw [← MonoidHom.range_eq_top, eq_top_iff, ← hgen, Subgroup.closure_le]
    intro x hx
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
    rcases hx with h | h
    · refine ⟨DihedralGroup.sr 0, ?_⟩
      rw [dihedralHom_sr, zpow_cast_zero, mul_one, h]
    · refine ⟨DihedralGroup.sr 1, ?_⟩
      rw [dihedralHom_sr, zpow_cast_one hn, ← mul_assoc, hs, one_mul, h]

/-- **A group generated by two involutions other than the identity is the dihedral group of order
twice the order of their product.** The isomorphism is `TauCeti.dihedralHom`: the rotation `r i` is
the power `(s * t) ^ i`, and the reflection `sr i` is `s * (s * t) ^ i`.

It is what identifies the Weyl group of a rank-two root system in
`TauCeti.nonempty_dihedralGroup_mulEquiv_weylGroup`. -/
noncomputable def dihedralGroupMulEquiv (hs : s * s = 1) (ht : t * t = 1) (hs1 : s ≠ 1)
    (ht1 : t ≠ 1) (hn : orderOf (s * t) = n) (hgen : Subgroup.closure ({s, t} : Set G) = ⊤) :
    DihedralGroup n ≃* G :=
  MulEquiv.ofBijective (dihedralHom hs ht hn) (dihedralHom_bijective hs ht hs1 ht1 hn hgen)

/-- `TauCeti.dihedralGroupMulEquiv` is `TauCeti.dihedralHom`. -/
@[simp]
theorem dihedralGroupMulEquiv_apply (hs : s * s = 1) (ht : t * t = 1) (hs1 : s ≠ 1) (ht1 : t ≠ 1)
    (hn : orderOf (s * t) = n) (hgen : Subgroup.closure ({s, t} : Set G) = ⊤)
    (x : DihedralGroup n) :
    dihedralGroupMulEquiv hs ht hs1 ht1 hn hgen x = dihedralHom hs ht hn x := by
  exact MulEquiv.ofBijective_apply (dihedralHom hs ht hn)
    (dihedralHom_bijective hs ht hs1 ht1 hn hgen) x

/-- **A group generated by two involutions other than the identity is the dihedral group of order
twice the order of their product**, the existential form of
`TauCeti.dihedralGroupMulEquiv`. -/
theorem nonempty_dihedralGroup_mulEquiv (hs : s * s = 1) (ht : t * t = 1) (hs1 : s ≠ 1)
    (ht1 : t ≠ 1) (hn : orderOf (s * t) = n)
    (hgen : Subgroup.closure ({s, t} : Set G) = ⊤) :
    Nonempty (DihedralGroup n ≃* G) :=
  ⟨dihedralGroupMulEquiv hs ht hs1 ht1 hn hgen⟩

end Recognition

end TauCeti
