/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.Multiquadratic.MultiquadraticSplitting
-- `LegendreEvenPrimeDiscriminant` supplies the supplementary law for the radicand `2`, used
-- only inside a proof below, so it is not re-exported.
import TauCeti.NumberTheory.Multiquadratic.Legendre.EvenPrimeDiscriminant
import TauCeti.NumberTheory.NumberField.Internal.PrimeDivisibility

/-!
# Prime-radicand splitting in multiquadratic fields

The field-generic multiquadratic splitting law applies to arbitrary integer radicands. This file
records the specialization to fields generated by square roots of a finite family of distinct
rational primes. In that setting the unramified-away-from-the-radicands hypothesis becomes the
familiar condition that the splitting prime is different from `2` and from every prime in the
radicand list.

This is a Layer 1 companion to the roadmap's worked example
`[ℚ(√2, √3) : ℚ] = 4`: once the field is generated by square roots of `2` and `3`, complete
splitting of an odd prime away from `2` and `3` is equivalent to both Legendre symbols being `1`.

## Main results

* `TauCeti.NumberField.ncard_primesOver_sqrt_primes_iff`: complete splitting in
  `ℚ(√pᵢ : i)` is equivalent to `legendreSym q (pᵢ) = 1` for every `i`.
* `TauCeti.NumberField.ncard_primesOver_sqrt_two_three_iff`: the concrete
  `ℚ(√2, √3)` worked-example form.
* `TauCeti.NumberField.ncard_primesOver_sqrt_two_three_iff_mod_eight`: the same criterion
  with the `√2` condition expanded as `q ≡ 1, 7 (mod 8)`.
-/

public section

open Ideal Module NumberField

namespace TauCeti.NumberField

variable {K : Type*} [Field K] [NumberField K]

/-- A rational prime `q` different from every prime in a family `p` divides none of the
corresponding integer radicands. -/
private theorem forall_not_intCast_prime_dvd_natPrimes {ι : Type*} (p : ι → ℕ)
    (hp : ∀ i, (p i).Prime) {q : ℕ} [Fact q.Prime] (hne : ∀ i, q ≠ p i) :
    ∀ i, ¬ (q : ℤ) ∣ (p i : ℤ) :=
  fun i => Internal.not_intCast_prime_dvd_natPrime (hp i) (hne i)

/-- **Prime-radicand multiquadratic splitting law.** Let `K` be generated over `ℚ` by square
roots of a finite family of rational primes `p i`. If `q` is an odd rational prime distinct from
every `p i`, then `q` splits completely in `K` exactly when every `p i` is a quadratic residue
modulo `q`. -/
theorem ncard_primesOver_sqrt_primes_iff {ι : Type*} [Finite ι] (p : ι → ℕ)
    (hp : ∀ i, (p i).Prime) (r : ι → K) (hr : ∀ i, r i ^ 2 = algebraMap ℤ K (p i : ℤ))
    (htop : IntermediateField.adjoin ℚ (Set.range r) = ⊤)
    {q : ℕ} [Fact q.Prime] (hodd : q ≠ 2) (hne : ∀ i, q ≠ p i) :
    (primesOver (span {(q : ℤ)}) (𝓞 K)).ncard = finrank ℚ K ↔
      ∀ i, legendreSym q (p i : ℤ) = 1 :=
  ncard_primesOver_multiquadratic_iff (d := fun i => (p i : ℤ)) (r := r) hr htop hodd
    (forall_not_intCast_prime_dvd_natPrimes p hp hne)

/-- The character condition for the radicands `2` and `3`, with the `√2` condition expanded
using the supplementary law for `2`. -/
private theorem forall_legendreSym_two_three_eq_one_iff_mod_eight {q : ℕ} [Fact q.Prime]
    (htwo : q ≠ 2) : (∀ i : Fin 2, legendreSym q ((![2, 3] : Fin 2 → ℕ) i : ℤ) = 1) ↔
      (q % 8 = 1 ∨ q % 8 = 7) ∧ legendreSym q (3 : ℤ) = 1 := by
  simp only [Fin.forall_fin_two]
  simpa [Multiquadratic.evenPrimeDiscriminantRadicand_eight] using
    (Multiquadratic.legendreSym_evenPrimeDiscriminantRadicand_eight_eq_one_iff
      (q := q) htwo).and Iff.rfl

/-- **Complete splitting for `ℚ(√2, √3)`.** Let `K` be generated over `ℚ` by square roots of
`2` and `3`. A rational prime `q` different from `2` and `3` splits completely in `K` exactly
when both `2` and `3` are quadratic residues modulo `q`. -/
theorem ncard_primesOver_sqrt_two_three_iff (r : Fin 2 → K)
    (hr : ∀ i, r i ^ 2 = algebraMap ℤ K ((![2, 3] : Fin 2 → ℕ) i : ℤ))
    (htop : IntermediateField.adjoin ℚ (Set.range r) = ⊤)
    {q : ℕ} [Fact q.Prime] (htwo : q ≠ 2) (hthree : q ≠ 3) :
    (primesOver (span {(q : ℤ)}) (𝓞 K)).ncard = finrank ℚ K ↔
      legendreSym q (2 : ℤ) = 1 ∧ legendreSym q (3 : ℤ) = 1 := by
  have h := ncard_primesOver_sqrt_primes_iff (![2, 3] : Fin 2 → ℕ) (by decide) r hr htop htwo
    (fun i => by fin_cases i <;> simp [htwo, hthree])
  exact h.trans (by simp [Fin.forall_fin_two])

/-- **Complete splitting for `ℚ(√2, √3)`, with the `√2` character expanded.** Let `K` be
generated over `ℚ` by square roots of `2` and `3`. A rational prime `q` different from `2` and
`3` splits completely in `K` exactly when `q ≡ 1` or `7` modulo `8` and `3` is a quadratic
residue modulo `q`. -/
theorem ncard_primesOver_sqrt_two_three_iff_mod_eight (r : Fin 2 → K)
    (hr : ∀ i, r i ^ 2 = algebraMap ℤ K ((![2, 3] : Fin 2 → ℕ) i : ℤ))
    (htop : IntermediateField.adjoin ℚ (Set.range r) = ⊤)
    {q : ℕ} [Fact q.Prime] (htwo : q ≠ 2) (hthree : q ≠ 3) :
    (primesOver (span {(q : ℤ)}) (𝓞 K)).ncard = finrank ℚ K ↔
      (q % 8 = 1 ∨ q % 8 = 7) ∧ legendreSym q (3 : ℤ) = 1 := by
  have h := ncard_primesOver_sqrt_primes_iff (![2, 3] : Fin 2 → ℕ) (by decide) r hr htop htwo
    (fun i => by fin_cases i <;> simp [htwo, hthree])
  exact h.trans (forall_legendreSym_two_three_eq_one_iff_mod_eight htwo)

end TauCeti.NumberField
