/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Geometry.Lie.InvariantVectorField.Basic

/-!
# Right-invariant vector fields on Lie groups

Mathlib's `mulInvariantVectorField` is the left-invariant field generated by a tangent vector at
the identity. This file supplies its right-invariant counterpart and the regularity needed to
compare the two fields in the infinitesimal adjoint calculation.

This supplies a prerequisite for Deliverable A, Layer 1 of
`TauCetiRoadmap/RepresentationTheory/LieGroups/README.md`.

## Main definitions

* `mulRightInvariantVectorField`: the right-invariant field generated at the identity.

## Main results

* `mulRightInvariantVectorField_one`: the field has the prescribed value at the identity.
* `mulRightInvariantVectorField_apply`: its value is the derivative of right multiplication.
* `mulRightInvariantVectorField_add`: the construction preserves addition.
* `mulRightInvariantVectorField_smul`: the construction preserves scalar multiplication.
* `inverse_mfderiv_mul_right`: derivatives of inverse right translations are inverse maps.
* `mpullback_mulRightInvariantVectorField`: right-invariant fields are invariant under right
  translations.
* `mulRightInvariantVectorField_eq_mpullback`: the field generated by `V 1` agrees with a pullback
  of `V` at the specified point.
* `contMDiff_mulRightInvariantVectorField_modelSpace`: jointly `C^m` in the generator and group
  point when multiplication is `C^n` and `m + 1 ≤ n`.
* `contMDiff_mulRightInvariantVectorField_infty`: a right-invariant field is smooth.
* `contMDiff_mvfderiv_mulRightInvariantVectorField`: differentiating a smooth scalar function
  along a right-invariant field gives a smooth function.
* `rightInvariantDerivative`: right-invariant differentiation bundled as a smooth scalar function.

## References

* [Lie groups and the Lie algebra correspondence roadmap](https://github.com/TauCetiProject/TauCetiRoadmap/blob/main/TauCetiRoadmap/RepresentationTheory/LieGroups/README.md),
  Deliverable A, Layer 1, "The infinitesimal adjoint".
* The definition mirrors Sébastien Gouëzel's Mathlib `mulInvariantVectorField`.
* The smoothness proofs adapt `contMDiff_mulInvariantVectorField_modelSpace` and
  `contMDiff_mulInvariantVectorField_infty` from
  `TauCeti.Geometry.Lie.InvariantVectorField.Basic`; those results in turn adapt Gouëzel's proof of
  Mathlib's `contMDiff_mulInvariantVectorField`.
* The pullback results `inverse_mfderiv_mul_right`, `mpullback_mulRightInvariantVectorField`, and
  `mulRightInvariantVectorField_eq_mpullback`, together with the addition and scalar-multiplication
  statements, transpose the corresponding left-translation results in Sébastien Gouëzel's
  `Mathlib.Geometry.Manifold.GroupLieAlgebra` from left to right.
-/

public section

noncomputable section

open Bundle Manifold VectorField
open scoped ContDiff Manifold

variable {𝕜 : Type*} [NontriviallyNormedField 𝕜]
  {E : Type*} [NormedAddCommGroup E] [NormedSpace 𝕜 E]
  {H : Type*} [TopologicalSpace H] {I : ModelWithCorners 𝕜 E H}
  {G : Type*} [TopologicalSpace G] [ChartedSpace H G] [Group G]

/-- The right-invariant vector field generated by a tangent vector at the identity. At a point
`g`, it is the image of the generator under the derivative at `1` of right multiplication by
`g`. -/
def mulRightInvariantVectorField (v : GroupLieAlgebra I G) (g : G) : TangentSpace I g :=
  mfderiv I I (fun x : G => x * g) 1 v

/-- The value of a generated right-invariant vector field is the derivative of right
multiplication applied to its generator. -/
theorem mulRightInvariantVectorField_apply (v : GroupLieAlgebra I G) (g : G) :
    mulRightInvariantVectorField v g = mfderiv I I (fun x : G => x * g) 1 v :=
  (rfl)

/-- At the identity, the right-invariant vector field generated by `v` equals `v`. -/
@[simp]
theorem mulRightInvariantVectorField_one (v : GroupLieAlgebra I G) :
    mulRightInvariantVectorField v (1 : G) = v := by
  rw [mulRightInvariantVectorField]
  -- Right multiplication by `1` is the identity map, whose manifold derivative is the identity.
  rw [show (fun x : G => x * 1) = id by funext x; simp, mfderiv_id]
  exact ContinuousLinearMap.id_apply v

/-- The right-invariant vector field construction preserves addition of its generators. -/
theorem mulRightInvariantVectorField_add (v w : GroupLieAlgebra I G) :
    mulRightInvariantVectorField (v + w) =
      mulRightInvariantVectorField v + mulRightInvariantVectorField w := by
  ext g
  simp only [Pi.add_apply, mulRightInvariantVectorField_apply, map_add]
  -- `TangentSpace I g` inherits addition from the model space `E`; there is no lemma-based rewrite.
  exact Eq.refl _

/-- The right-invariant vector field construction preserves scalar multiplication. -/
theorem mulRightInvariantVectorField_smul (c : 𝕜) (v : GroupLieAlgebra I G) :
    mulRightInvariantVectorField (c • v) = c • mulRightInvariantVectorField v := by
  ext g
  simp only [Pi.smul_apply, mulRightInvariantVectorField_apply, map_smul]
  -- `TangentSpace I g` inherits scalar multiplication from `E`; there is no lemma-based rewrite.
  exact Eq.refl _

section Pullback

variable [ContMDiffMul I 1 G]

/-- The inverse of the derivative at `h` of right translation by `g` is the derivative at `h * g`
of right translation by `g⁻¹`. -/
@[simp]
theorem inverse_mfderiv_mul_right {g h : G} :
    (mfderiv I I (· * g) h).inverse = mfderiv I I (· * g⁻¹) (h * g) := by
  have A : mfderiv I I ((· * g⁻¹) ∘ (· * g)) h = ContinuousLinearMap.id 𝕜 _ := by
    have : (· * g⁻¹) ∘ (· * g) = id := by ext x; simp
    rw [this, id_eq, mfderiv_id]
  rw [mfderiv_comp (I' := I) _
    (contMDiff_mul_right.contMDiffAt.mdifferentiableAt one_ne_zero)
    (contMDiff_mul_right.contMDiffAt.mdifferentiableAt one_ne_zero)] at A
  have A' : mfderiv I I ((· * g) ∘ (· * g⁻¹)) (h * g) =
      ContinuousLinearMap.id 𝕜 _ := by
    have : (· * g) ∘ (· * g⁻¹) = id := by ext x; simp
    rw [this, id_eq, mfderiv_id]
  rw [mfderiv_comp (I' := I) _
    (contMDiff_mul_right.contMDiffAt.mdifferentiableAt one_ne_zero)
    (contMDiff_mul_right.contMDiffAt.mdifferentiableAt one_ne_zero), mul_inv_cancel_right h g] at A'
  exact ContinuousLinearMap.inverse_eq A' A

/-- Right-invariant vector fields are invariant under pullback by right translations. -/
theorem mpullback_mulRightInvariantVectorField (g : G) (v : GroupLieAlgebra I G) :
    VectorField.mpullback I I (· * g) (mulRightInvariantVectorField v) =
      mulRightInvariantVectorField v := by
  ext h
  simp only [VectorField.mpullback, inverse_mfderiv_mul_right, mulRightInvariantVectorField]
  have D : (fun x ↦ x * h) = (· * g⁻¹) ∘ (fun x ↦ x * (h * g)) := by
    ext x
    simp only [Function.comp_apply]
    group
  rw [D, mfderiv_comp (I' := I)]
  · congr 2
    simp
  · exact contMDiff_mul_right.contMDiffAt.mdifferentiableAt one_ne_zero
  · exact contMDiff_mul_right.contMDiffAt.mdifferentiableAt one_ne_zero

/-- For any field `V`, the right-invariant field generated by `V 1` agrees at `g` with the pullback
of `V` along right translation by `g⁻¹`. -/
theorem mulRightInvariantVectorField_eq_mpullback (g : G)
    (V : ∀ g : G, TangentSpace I g) :
    mulRightInvariantVectorField (V 1) g =
      VectorField.mpullback I I (· * g⁻¹) V g := by
  rw [← congrFun (mpullback_mulRightInvariantVectorField (I := I) g⁻¹ (V 1)) g]
  simp only [VectorField.mpullback]
  congr 1
  rw [show g * g⁻¹ = 1 by simp, mulRightInvariantVectorField_one]

end Pullback

/-- In model coordinates, the right-invariant vector field is jointly `C^m` in its generating
tangent vector and group point when multiplication is `C^n` and `m + 1 ≤ n`. -/
theorem contMDiff_mulRightInvariantVectorField_modelSpace {m n : ℕ∞ω}
    [ContMDiffMul I n G] (hmn : m + 1 ≤ n) :
    let _ : IsManifold I 1 G := IsManifold.of_le (le_add_self.trans hmn)
    ContMDiff (𝓘(𝕜, E).prod I) I.tangent m
      (fun p : E × G =>
        (mulRightInvariantVectorField (I := I) (G := G) p.1 p.2 : TangentBundle I G)) := by
  let _ : IsManifold I 1 G := IsManifold.of_le (le_add_self.trans hmn)
  let fg : E × G → TangentBundle I G := fun p => TotalSpace.mk' E p.2 0
  have sfg : ContMDiff (𝓘(𝕜, E).prod I) I.tangent m fg := by
    simpa only [fg] using
      contMDiff_tangentBundle_mk_zero (I := I) (M := G) (n := m) contMDiff_snd
  let fv : E × G → TangentBundle I G := fun p => TotalSpace.mk' E 1 p.1
  have sfv : ContMDiff (𝓘(𝕜, E).prod I) I.tangent m fv := by
    simpa only [fv] using
      contMDiff_tangentBundle_mk_constBase (I := I) (M := G) (n := m) contMDiff_fst (1 : G)
  let S := contMDiff_tangentMap_mul_prod_comp (I := I) (G := G) hmn fv fg sfv sfg
  apply S.congr
  intro p
  let _ : ContMDiffMul I 1 G :=
    ContMDiffMul.of_le (m := 1) (n := n) (le_add_self.trans hmn)
  rw [tangentMap_mul_prod_apply]
  simp +instances only [mulRightInvariantVectorField, map_zero, add_zero, fv, fg]
  rw [one_mul]

/-- A right-invariant vector field on a smooth Lie group is smooth. -/
theorem contMDiff_mulRightInvariantVectorField_infty
    [ContMDiffMul I ∞ G] (v : GroupLieAlgebra I G) :
    ContMDiff I I.tangent ∞
      (fun g : G => (mulRightInvariantVectorField v g : TangentBundle I G)) := by
  have h := contMDiff_mulRightInvariantVectorField_modelSpace
    (I := I) (G := G) (m := ∞) (n := ∞) (by simp)
  exact h.comp (contMDiff_const.prodMk contMDiff_id)

/-- Differentiating a smooth scalar function along a right-invariant vector field gives a smooth
scalar function. -/
theorem contMDiff_mvfderiv_mulRightInvariantVectorField
    [ContMDiffMul I ∞ G] (v : GroupLieAlgebra I G)
    (f : C^∞⟮I, G; 𝕜⟯) :
    ContMDiff I (modelWithCornersSelf 𝕜 𝕜) ∞
      (fun g ↦ mvfderiv I f g (mulRightInvariantVectorField v g)) :=
  (f.contMDiff.contMDiff_mvfderiv_apply (by simp)).comp
    (contMDiff_mulRightInvariantVectorField_infty v)

/-- Right-invariant differentiation of a smooth scalar function, bundled as a smooth scalar
function. -/
noncomputable def rightInvariantDerivative
    [ContMDiffMul I ∞ G] (v : GroupLieAlgebra I G)
    (f : C^∞⟮I, G; 𝕜⟯) : C^∞⟮I, G; 𝕜⟯ :=
  ⟨fun g => mvfderiv I f g (mulRightInvariantVectorField v g),
    contMDiff_mvfderiv_mulRightInvariantVectorField v f⟩

/-- Right-invariant differentiation acts pointwise along the corresponding vector field. -/
@[simp]
theorem rightInvariantDerivative_apply
    [ContMDiffMul I ∞ G] (v : GroupLieAlgebra I G)
    (f : C^∞⟮I, G; 𝕜⟯) (g : G) :
    rightInvariantDerivative v f g =
      mvfderiv I f g (mulRightInvariantVectorField v g) :=
  by simp only [rightInvariantDerivative, ContMDiffMap.coeFn_mk]
