/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RingTheory.Huber.Basic

/-!
# Open ideals of a Huber ring

Fix a pair of definition `(A₀, I)` for a Huber ring `A`. The neighbourhoods of zero that are
cofinal are the *images* of the powers `Iⁿ` in `A`, not the ideals they generate — an ideal span
can be much larger than the additive subgroup it is spanned by. What makes the ideal statement
work is that an *ideal* of `A` containing the image of `Iⁿ` automatically contains its span
`(I · A)ⁿ`. So an ideal of `A` is open exactly when it contains one of those powers, and since
`I · A` is finitely generated that is the same as asking `I · A` to lie in its radical.

## Main results

* `TauCeti.Huber.PairOfDefinition.extendedIdealOfDefinition_pow`: the powers of `I · A`
  (defined in `TauCeti/RingTheory/Huber/Basic.lean`) are generated by the basic neighbourhoods
  of zero.
* `TauCeti.Huber.PairOfDefinition.isOpen_iff_exists_pow_le`: an ideal of `A` is open exactly when
  it contains a power of `I · A`.
* `TauCeti.Huber.PairOfDefinition.isOpen_iff_le_radical`: an ideal of `A` is open exactly when its
  radical contains `I · A`.
* `TauCeti.Huber.IsTateRing.isOpen_iff_eq_top`: an ideal of a Tate ring is open exactly when it is
  the whole ring.

## Provenance

AINTLIB formalises this same layer and was consulted for the choice of results; the statements,
names and proofs here are independent of it. Its `HuberRings.lean` carries the extension `I · A`
as `PairOfDefinition.idealOfDefinition` — a name this development gives to the ideal of `A₀`
itself, so `extendedIdealOfDefinition` is used here instead — with `idealOfDefinition_fg` proved,
as `fg_extendedIdealOfDefinition` is, by `Ideal.FG.map`. Its
`projects/AdicSpaces/Adic spaces/OpenIdeals.lean` is headed "We prove Lemma 6.6 … of
[Wedhorn, *Adic Spaces*]" and reaches the radical criterion as
`ideal_isOpen_iff_topologicalNilradical_le_radical`, phrased through the topological nilradical
and hypothesising a finitely generated ideal of definition; the form below instead names the pair
of definition and routes the whole lemma through `Ideal.map_pow`.

## References

* [Wedhorn, *Adic Spaces*][wedhorn_adic], Lemma 6.6.
* [AINTLIB](https://github.com/CBirkbeck/AINTLIB), branch `dev/adic-spaces`,
  `projects/AdicSpaces/Adic spaces/OpenIdeals.lean` and `HuberRings.lean`.
-/

public section

namespace TauCeti.Huber

namespace PairOfDefinition

variable {A : Type*} [CommRing A] [TopologicalSpace A]

/-- The `n`-th power of `I · A` is generated by the `n`-th basic neighbourhood of zero: the
image `TauCeti.Huber.PairOfDefinition.idealImage n` of `Iⁿ` in `A`. -/
theorem extendedIdealOfDefinition_pow (P : PairOfDefinition A) (n : ℕ) :
    P.extendedIdealOfDefinition ^ n = Ideal.span (P.idealImage n : Set A) := by
  rw [P.coe_idealImage, ← Subring.coe_subtype, ← Ideal.map_span, Ideal.span_eq,
    P.extendedIdealOfDefinition_def, ← Ideal.map_pow]

variable [IsTopologicalRing A]

/-- Wedhorn Lemma 6.6: an ideal of a Huber ring is open exactly when it contains a power of the
ideal `I · A` generated by an ideal of definition. -/
theorem isOpen_iff_exists_pow_le (P : PairOfDefinition A) (a : Ideal A) :
    IsOpen (a : Set A) ↔ ∃ n : ℕ, P.extendedIdealOfDefinition ^ n ≤ a := by
  constructor
  · intro ha
    obtain ⟨n, -, hn⟩ := P.hasBasis_nhds_zero.mem_iff.mp (ha.mem_nhds a.zero_mem)
    exact ⟨n, by rw [P.extendedIdealOfDefinition_pow, Ideal.span_le]; exact hn⟩
  · rintro ⟨n, hn⟩
    rw [P.extendedIdealOfDefinition_pow, Ideal.span_le] at hn
    exact AddSubgroup.isOpen_mono (H₂ := a.toAddSubgroup) hn (P.isOpen_idealImage n)

/-- Wedhorn Lemma 6.6, radical form: an ideal of a Huber ring is open exactly when its radical
contains the ideal `I · A` generated by an ideal of definition. -/
theorem isOpen_iff_le_radical (P : PairOfDefinition A) (a : Ideal A) :
    IsOpen (a : Set A) ↔ P.extendedIdealOfDefinition ≤ a.radical := by
  rw [P.isOpen_iff_exists_pow_le a]
  exact ⟨fun ⟨n, hn⟩ _ hx ↦ ⟨n, hn (Ideal.pow_mem_pow hx n)⟩,
    fun h ↦ Ideal.exists_pow_le_of_le_radical_of_fg h P.fg_extendedIdealOfDefinition⟩

end PairOfDefinition

section Tate

variable {A : Type*} [CommRing A] [TopologicalSpace A] [IsTopologicalRing A]

/-- An open ideal in a Tate ring is the whole ring `⊤`. -/
theorem IsTateRing.eq_top_of_isOpen [IsTateRing A] {J : Ideal A}
    (hJ : IsOpen (J : Set A)) : J = ⊤ := by
  obtain ⟨ϖ, hϖ⟩ := IsTateRing.exists_isPseudoUniformizer (A := A)
  obtain ⟨n, hn⟩ := hϖ.isTopologicallyNilpotent.exists_pow_mem_of_mem_nhds (hJ.mem_nhds J.zero_mem)
  exact Ideal.eq_top_of_isUnit_mem J hn (hϖ.isUnit.pow n)

/-- In a Tate ring, an ideal is open if and only if it is the whole ring `⊤`. -/
@[simp]
theorem IsTateRing.isOpen_iff_eq_top [IsTateRing A] (J : Ideal A) :
    IsOpen (J : Set A) ↔ J = ⊤ :=
  ⟨IsTateRing.eq_top_of_isOpen, fun h ↦ h.symm ▸ isOpen_univ⟩

end Tate

end TauCeti.Huber
