/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RingTheory.DedekindDomain.Factorization
public import TauCeti.RingTheory.ClassGroup.Basic

/-!
# Ideal classes generated by a set of height one primes

Closure statements about which ideal classes a set `T` of height one primes generates: if the
`v`-adic multiplicities of a fractional ideal are controlled outside `T`, its class lies in the
subgroup generated by `{[v] : v ∈ T}`, where `[v]` is
`IsDedekindDomain.HeightOneSpectrum.classGroupMk` from `TauCeti.RingTheory.ClassGroup.Basic`.

## Main results

* `ClassGroup.mk_mem_closure_of_count_eq_zero`: if the multiplicities of a unit fractional ideal
  vanish outside `T`, its class lies in `Subgroup.closure (classGroupMk '' T)`.
* `ClassGroup.mk_mem_closure_of_count_eq`: the same when the multiplicities merely *agree* outside
  `T` with those of a principal fractional ideal `(x)`.
* `ClassGroup.mk0_mem_closure_of_count_eq`: the integral-ideal specialisation, the form the
  `S`-integer material consumes.

The factorization `I = ∏_v v ^ count v I` comes from Mathlib's
`FractionalIdeal.finprod_heightOneSpectrum_factorization'`, lifted from fractional ideals to units
along `Units.coeHom`. Nothing here mentions Weil divisors, so `RingTheory` and `NumberTheory`
consumers can reach these results without importing `TauCeti.AlgebraicGeometry`.

These are an input to what `TauCetiRoadmap/EllipticCurves/README.md` §Layer 6 needs for weak
Mordell–Weil. That argument exhibits the `S`-class group as a quotient of the class group by the
classes of `S`, and concludes it is finite; neither the `S`-class group nor that quotient is
defined here — this file supplies only the generation statements the argument rests on.

Adapted from Michael Stoll's elliptic-curves formalisation
(`github.com/MichaelStollBayreuth/EllipticCurves`, `EllipticCurves/Mathlib/FractionalIdeal.lean`
at the roadmap's pin `66889eada51a`, Apache 2.0, by Michael Stoll). Following this repository's
convention for adapted material, the upstream authorship is credited here rather than in the
copyright header.
-/

public section

open IsDedekindDomain IsDedekindDomain.HeightOneSpectrum
open scoped nonZeroDivisors

variable {R : Type*} [CommRing R] [IsDedekindDomain R]

/-- `v.asIdeal` as an invertible fractional ideal of `K`. Local to this file: it is the shape the
factorization of a unit fractional ideal takes, and it appears in no statement. -/
private noncomputable def unitOfPrime (K : Type*) [Field K] [Algebra R K] [IsFractionRing R K]
    (v : HeightOneSpectrum R) : (FractionalIdeal R⁰ K)ˣ :=
  Units.mk0 (v.asIdeal : FractionalIdeal R⁰ K) (FractionalIdeal.coeIdeal_ne_zero.mpr v.ne_bot)

variable {K : Type*} [Field K] [Algebra R K] [IsFractionRing R K]

/-- Only finitely many primes divide a unit fractional ideal, so its prime-power family has
finite multiplicative support and the factorization below is a finite product. -/
private lemma finite_mulSupport_unitOfPrime_zpow (I : (FractionalIdeal R⁰ K)ˣ) :
    (Function.mulSupport fun v : HeightOneSpectrum R =>
      unitOfPrime K v ^ FractionalIdeal.count K v (I : FractionalIdeal R⁰ K)).Finite := by
  refine (Filter.eventually_cofinite.mp
    (FractionalIdeal.finite_factors (I : FractionalIdeal R⁰ K))).subset fun v hv hc0 => ?_
  exact hv (by simp only [hc0, zpow_zero])

/-- **Unique factorization at unit level**: a unit fractional ideal is the product of the prime
powers its multiplicities record. This is Mathlib's
`FractionalIdeal.finprod_heightOneSpectrum_factorization'`, which is stated for fractional
ideals, transported to `(FractionalIdeal R⁰ K)ˣ` along `Units.coeHom`. -/
private lemma finprod_unitOfPrime_zpow_count (I : (FractionalIdeal R⁰ K)ˣ) :
    I = ∏ᶠ v : HeightOneSpectrum R,
      unitOfPrime K v ^ FractionalIdeal.count K v (I : FractionalIdeal R⁰ K) := by
  -- The `map_finprod` equation is stated rather than rewritten into, because
  -- `← Units.coeHom_apply` would also rewrite the coercion inside `count K v ↑I`.
  have hmap : ((∏ᶠ v : HeightOneSpectrum R,
        unitOfPrime K v ^ FractionalIdeal.count K v (I : FractionalIdeal R⁰ K)) :
        (FractionalIdeal R⁰ K)ˣ) =
      ∏ᶠ v : HeightOneSpectrum R,
        ((unitOfPrime K v ^ FractionalIdeal.count K v (I : FractionalIdeal R⁰ K) :
          (FractionalIdeal R⁰ K)ˣ) : FractionalIdeal R⁰ K) :=
    MonoidHom.map_finprod (Units.coeHom (FractionalIdeal R⁰ K))
      (finite_mulSupport_unitOfPrime_zpow I)
  refine Units.ext ?_
  rw [hmap]
  simp only [unitOfPrime, Units.val_zpow_eq_zpow_val, Units.val_mk0]
  exact (FractionalIdeal.finprod_heightOneSpectrum_factorization' (K := K)
    (I := (I : FractionalIdeal R⁰ K)) (Units.ne_zero I)).symm

/-- If the `v`-adic multiplicities of a unit fractional ideal vanish outside a set `T` of height
one primes, its ideal class lies in the subgroup generated by the classes of the primes in `T`. -/
lemma _root_.ClassGroup.mk_mem_closure_of_count_eq_zero {T : Set (HeightOneSpectrum R)}
    {I : (FractionalIdeal R⁰ K)ˣ}
    (h : ∀ v ∉ T, FractionalIdeal.count K v (I : FractionalIdeal R⁰ K) = 0) :
    ClassGroup.mk K I ∈ Subgroup.closure (HeightOneSpectrum.classGroupMk '' T) := by
  classical
  have hfin := finite_mulSupport_unitOfPrime_zpow (K := K) I
  rw [finprod_unitOfPrime_zpow_count I,
    finprod_eq_prod_of_mulSupport_toFinset_subset _ hfin (Finset.Subset.refl _), map_prod]
  refine Subgroup.prod_mem _ fun v hv ↦ ?_
  have hvT : v ∈ T := by
    by_contra hvn
    refine (hfin.mem_toFinset.mp hv) ?_
    simp only [h v hvn, zpow_zero]
  rw [map_zpow, unitOfPrime, ← v.classGroupMk_eq_mk K]
  exact Subgroup.zpow_mem _ (Subgroup.subset_closure (Set.mem_image_of_mem _ hvT)) _

/-- If the `v`-adic multiplicities of a unit fractional ideal agree outside a set `T` of height
one primes with those of a principal fractional ideal `(x)`, then its class lies in the subgroup
generated by the classes of the primes in `T`. -/
lemma _root_.ClassGroup.mk_mem_closure_of_count_eq (K : Type*) [Field K] [Algebra R K]
    [IsFractionRing R K] {T : Set (HeightOneSpectrum R)} {I : (FractionalIdeal R⁰ K)ˣ} (x : Kˣ)
    (h : ∀ v ∉ T, FractionalIdeal.count K v (I : FractionalIdeal R⁰ K) =
      FractionalIdeal.count K v (FractionalIdeal.spanSingleton R⁰ (x : K))) :
    ClassGroup.mk K I ∈ Subgroup.closure (HeightOneSpectrum.classGroupMk '' T) := by
  have hmk : ClassGroup.mk K I = ClassGroup.mk K (I * (toPrincipalIdeal R K x)⁻¹) := by
    rw [map_mul, map_inv, ClassGroup.mk_toPrincipalIdeal, inv_one, mul_one]
  rw [hmk]
  refine ClassGroup.mk_mem_closure_of_count_eq_zero fun v hv ↦ ?_
  rw [Units.val_mul, FractionalIdeal.count_mul K v (Units.ne_zero _) (Units.ne_zero _),
    Units.val_inv_eq_inv_val, FractionalIdeal.count_inv, coe_toPrincipalIdeal, h v hv]
  exact add_neg_cancel _

/-- The integral-ideal form of `ClassGroup.mk_mem_closure_of_count_eq`: if the multiplicities of a
nonzero ideal `J` agree outside `T` with those of a principal fractional ideal `(x)`, then the
class of `J` lies in the subgroup generated by the classes of the primes in `T`. -/
lemma _root_.ClassGroup.mk0_mem_closure_of_count_eq (K : Type*) [Field K] [Algebra R K]
    [IsFractionRing R K] {T : Set (HeightOneSpectrum R)} {J : (Ideal R)⁰} (x : Kˣ)
    (h : ∀ v ∉ T, FractionalIdeal.count K v ((J : Ideal R) : FractionalIdeal R⁰ K) =
      FractionalIdeal.count K v (FractionalIdeal.spanSingleton R⁰ (x : K))) :
    ClassGroup.mk0 J ∈ Subgroup.closure (HeightOneSpectrum.classGroupMk '' T) := by
  rw [← ClassGroup.mk_mk0 K]
  refine ClassGroup.mk_mem_closure_of_count_eq K x fun v hv ↦ ?_
  rw [FractionalIdeal.coe_mk0]
  exact h v hv

end
