/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Geometry.Lie.Exponential.Classification
public import Mathlib.Geometry.Manifold.Instances.Sphere

/-!
# Compatibility with the circle exponential

Mathlib's `Circle.exp` is a continuous one-parameter subgroup of the analytic Lie group `Circle`.
The classification of continuous one-parameter subgroups therefore supplies its unique abstract
Lie-algebra generator. We normalize the one-dimensional Lie algebra identification by sending this
generator to `1`; under that identification, the abstract Lie-group exponential is exactly
`Circle.exp`.

## Main results

* `circleExpHom`: `Circle.exp`, bundled as a continuous multiplicative homomorphism.
* `circleExpGenerator`: its unique left-invariant infinitesimal generator.
* `circleLieAlgebraEquiv`: the identification `Lie(Circle) ≃ₗ[ℝ] ℝ` normalized by that generator.
* `lieExp_circle`: under this identification, the abstract exponential is `Circle.exp`.

## References

* [Lie groups and the Lie algebra correspondence roadmap](https://github.com/TauCetiProject/TauCetiRoadmap/blob/main/TauCetiRoadmap/RepresentationTheory/LieGroups/README.md),
  Deliverable A, Layer 0, "The matrix and circle shadows".
-/

public section

open Manifold
open scoped ContDiff Manifold

noncomputable section

/-- Mathlib's circle exponential, bundled as a continuous homomorphism from the additive real line
written multiplicatively. -/
noncomputable def circleExpHom : ContinuousMonoidHom (Multiplicative ℝ) Circle where
  toMonoidHom := Circle.expHom.toMultiplicativeLeft
  continuous_toFun := Circle.exp.continuous.comp continuous_toAdd

/-- The bundled circle exponential evaluates to Mathlib's `Circle.exp`. -/
@[simp]
theorem circleExpHom_apply (t : ℝ) :
    circleExpHom (Multiplicative.ofAdd t) = Circle.exp t := (rfl)

/-- The unique abstract Lie-algebra generator of Mathlib's circle exponential. -/
noncomputable def circleExpGenerator : LeftInvariantDerivation (𝓡 1) Circle :=
  (oneParameterSubgroupEquiv (I := 𝓡 1) (G := Circle)).symm circleExpHom

/-- The abstract subgroup generated by `circleExpGenerator` is Mathlib's `Circle.exp`. -/
@[simp]
theorem oneParameterSubgroup_circleExpGenerator :
    oneParameterSubgroup circleExpGenerator = circleExpHom := by
  rw [circleExpGenerator, ← oneParameterSubgroupEquiv_apply]
  exact (oneParameterSubgroupEquiv (I := 𝓡 1) (G := Circle)).apply_symm_apply circleExpHom

/-- Exponentiating a scalar multiple of the circle generator gives `Circle.exp` at that scalar. -/
@[simp]
theorem lieExp_circleExpGenerator (t : ℝ) :
    lieExp (t • circleExpGenerator) = Circle.exp t := by
  have h := DFunLike.congr_fun oneParameterSubgroup_circleExpGenerator
    (Multiplicative.ofAdd t)
  simpa only [oneParameterSubgroup_apply, circleExpHom_apply] using h

/-- The generator of `Circle.exp` is nonzero. -/
theorem circleExpGenerator_ne_zero : circleExpGenerator ≠ 0 := by
  intro hzero
  have h := lieExp_circleExpGenerator Real.pi
  rw [hzero, smul_zero, lieExp_zero] at h
  exact Circle.exp_pi_ne_one h.symm

/-- A preliminary linear identification of the circle Lie algebra with the reals, obtained from
evaluation at the identity and the one-dimensional Euclidean model. -/
private noncomputable def circleLieAlgebraEquivModel :
    LeftInvariantDerivation (𝓡 1) Circle ≃ₗ[ℝ] ℝ :=
  (leftInvariantDerivationEquivGroupLieAlgebra (I := 𝓡 1) (G := Circle)
      BoundarylessManifold.isInteriorPoint).trans
    ((EuclideanSpace.equiv (Fin 1) ℝ).toLinearEquiv.trans
      (LinearEquiv.funUnique (Fin 1) ℝ ℝ))

private theorem circleLieAlgebraEquivModel_generator_ne_zero :
    circleLieAlgebraEquivModel circleExpGenerator ≠ 0 := by
  intro hzero
  apply circleExpGenerator_ne_zero
  apply circleLieAlgebraEquivModel.injective
  simpa only [map_zero] using hzero

/-- The canonical identification `Lie(Circle) ≃ₗ[ℝ] ℝ` for the exponential comparison, normalized
so that the generator of Mathlib's `Circle.exp` maps to `1`. -/
noncomputable def circleLieAlgebraEquiv :
    LeftInvariantDerivation (𝓡 1) Circle ≃ₗ[ℝ] ℝ :=
  circleLieAlgebraEquivModel.trans
    (Units.mulLeftLinearEquiv ℝ ℝ
      ((Units.mk0 (circleLieAlgebraEquivModel circleExpGenerator)
        circleLieAlgebraEquivModel_generator_ne_zero)⁻¹))

/-- The normalized circle Lie-algebra identification sends the exponential generator to one. -/
@[simp]
theorem circleLieAlgebraEquiv_apply_generator :
    circleLieAlgebraEquiv circleExpGenerator = 1 := by
  rw [circleLieAlgebraEquiv, LinearEquiv.trans_apply, Units.mulLeftLinearEquiv_apply]
  exact inv_mul_cancel₀ circleLieAlgebraEquivModel_generator_ne_zero

/-- Under the normalized identification `Lie(Circle) ≃ₗ[ℝ] ℝ`, the abstract Lie-group
exponential is exactly Mathlib's `Circle.exp`. -/
@[simp]
theorem lieExp_circle (t : ℝ) : lieExp (circleLieAlgebraEquiv.symm t) = Circle.exp t := by
  have hgen : circleLieAlgebraEquiv.symm 1 = circleExpGenerator := by
    exact circleLieAlgebraEquiv.symm_apply_eq.mpr circleLieAlgebraEquiv_apply_generator.symm
  calc
    lieExp (circleLieAlgebraEquiv.symm t) =
        lieExp (circleLieAlgebraEquiv.symm (t • (1 : ℝ))) := by rw [smul_eq_mul, mul_one]
    _ = lieExp (t • circleLieAlgebraEquiv.symm 1) := by rw [map_smul]
    _ = lieExp (t • circleExpGenerator) := by rw [hgen]
    _ = Circle.exp t := lieExp_circleExpGenerator t
