/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.AlgebraicGeometry.EllipticCurve.DivisionPolynomial.Basic

/-!
# A common divisor of `Ψ₂Sq(x)` and `4·Ψ₃(x)` divides `4Δ`

The headline is a divisibility transfer between Mathlib's division polynomials: for any
commutative ring, any `x`, and any `d`,

`d ∣ Ψ₂Sq(x)` and `d ∣ 4·Ψ₃(x)` together give `d ∣ 4Δ`.

Equivalently, `4Δ` lies in the ideal generated by `Ψ₂Sq(x)` and `4·Ψ₃(x)` at every `x`, and the
proof is an explicit Bézout certificate in the `b`-invariants. Its two divisibility premises are of
course assumptions; what it needs *beyond* them is nothing — no point of a curve, no ellipticity,
no domain or factorisation hypothesis on the ring.

When the Nagell–Lutz route later needs the on-curve form — with `κ = ψ₂(x, y) = 2y + a₁x + a₃`
Mathlib's `2`-division polynomial at a point, take `d = κ²`, which on the curve *is* `Ψ₂Sq(x)` by
`evalEval_ψ₂_sq` — that is a one-line specialisation. It is deliberately **not** stated here: its
hypothesis `κ² ∣ 4·Ψ₃(x)` is supplied by point-level `[n]`-multiplication material that is not yet
in this repository, and a theorem whose premise nothing can yet discharge is not API this file
should export. For a short model (`a₁ = a₃ = 0`, so `κ = 2y`) that future conclusion reads
`(2y)² ∣ 4Δ`.

## Main results

* `TauCeti.WeierstrassCurve.dvd_four_mul_Δ_of_dvd_Ψ₂Sq_of_dvd_four_mul_Ψ₃`: over any commutative
  ring, a common divisor of `Ψ₂Sq(x)` and `4·Ψ₃(x)` divides `4Δ`.
* `TauCeti.WeierstrassCurve.evalEval_ψ₂_sq`: on the curve, `ψ₂(x, y)² = Ψ₂Sq(x)`.

Stated over an arbitrary commutative ring: no domain, integrality or ellipticity hypothesis.

⚠ **No torsion hypothesis appears here, and no part of `lutz_nagell` is proved.** Nothing in this
file takes a premise that awaits absent material: the headline is a statement about polynomials,
usable by any caller with a common divisor in hand, and `evalEval_ψ₂_sq` is an unconditional
on-curve evaluation.

This is an ingredient for the Nagell–Lutz milestone of `TauCetiRoadmap/EllipticCurves/README.md`,
Layer 6, item "The torsion subgroup and Nagell–Lutz", whose short-model target `lutz_nagell` asks
for `x, y ∈ ℤ` together with `y = 0 ∨ y² ∣ Δ`. It is the algebraic step feeding the **second
disjunct** of that disjunction, in the long-model form the roadmap also names
(`lutz_nagell_integrality_general`, "with its discriminant companion"). Establishing the full
disjunction additionally requires the torsion input above and a separate treatment of the `y = 0`
branch.

## Provenance

Ported from the AINTLIB `NagellLutz` project (`github.com/CBirkbeck/AINTLIB`, Apache-2.0), pinned by
that roadmap at `dev/modular-curves @ 9fec8eba7652`:
`LutzNagell/LutzNagellTheorem/PIDMain.lean`, declarations `kappa_sq_eq_Psi2Sq`, `bezout_identity`,
`kappa_sq_dvd_four_delta`, `eval_Ψ₃` and `lutz_nagell_pid_discriminant`. Restated here against
Mathlib's `ψ₂`, `Ψ₂Sq` and `Ψ₃` rather than the raw expressions the source carries, so no
`eval_Ψ₃` bridge lemma is needed; the source's `[IsDomain]`, `[IsPrincipalIdealRing]` and
`[CharZero]` hypotheses were already `omit`ted there and are absent here too.
-/

public section

open Polynomial

open scoped Polynomial.Bivariate

namespace TauCeti

namespace WeierstrassCurve

variable {R : Type*} [CommRing R] (W : _root_.WeierstrassCurve R) {x y : R}

/-- On the curve, the square of `ψ₂` at a point is the univariate `Ψ₂Sq` at its `x`-coordinate.

This is Mathlib's polynomial identity `ψ₂_sq` — `ψ₂² = C Ψ₂Sq + 4 * polynomial` — evaluated at a
point where the Weierstrass polynomial vanishes. -/
@[simp]
theorem evalEval_ψ₂_sq (h : W.toAffine.Equation x y) :
    W.ψ₂.evalEval x y ^ 2 = (W.Ψ₂Sq).eval x := by
  have hsq := congrArg (Polynomial.evalEval x y) W.ψ₂_sq
  rw [_root_.WeierstrassCurve.Affine.Equation] at h
  simpa [h, evalEval_C] using hsq

/-- The Bézout combination exhibiting `4Δ` from `Ψ₂Sq(x)` and `Ψ₃(x)`.

`Δ` is a polynomial in the `b`-invariants, and this is the explicit certificate that `4Δ` lies in
the ideal they generate at any `x`. -/
private theorem bezout_four_mul_Δ (x : R) :
    (432 * x ^ 3 + 108 * W.b₂ * x ^ 2 + 216 * W.b₄ * x +
        (-W.b₂ ^ 3 + 36 * W.b₂ * W.b₄ - 108 * W.b₆)) * (W.Ψ₂Sq).eval x +
      (-48 * x ^ 2 - 8 * W.b₂ * x + (W.b₂ ^ 2 - 32 * W.b₄)) *
        (6 * x ^ 2 + W.b₂ * x + W.b₄) ^ 2 = 4 * W.Δ := by
  simp only [_root_.WeierstrassCurve.Ψ₂Sq, _root_.WeierstrassCurve.b₂, _root_.WeierstrassCurve.b₄,
    _root_.WeierstrassCurve.b₆, _root_.WeierstrassCurve.b₈, _root_.WeierstrassCurve.Δ,
    eval_add, eval_mul, eval_pow, eval_C, eval_X]
  ring

/-- The square of `6x² + b₂x + b₄` differs from `4·Ψ₃(x)` by a multiple of `Ψ₂Sq(x)`, so anything
dividing `Ψ₂Sq(x)` and `4·Ψ₃(x)` divides it. -/
private theorem dvd_sq_of_dvd_Ψ₂Sq_of_dvd_four_mul_Ψ₃ {d : R} (hd : d ∣ (W.Ψ₂Sq).eval x)
    (hΨ₃ : d ∣ 4 * (W.Ψ₃).eval x) : d ∣ (6 * x ^ 2 + W.b₂ * x + W.b₄) ^ 2 := by
  have hid : (6 * x ^ 2 + W.b₂ * x + W.b₄) ^ 2 =
      (12 * x + W.b₂) * (W.Ψ₂Sq).eval x - 4 * (W.Ψ₃).eval x := by
    simp only [_root_.WeierstrassCurve.Ψ₂Sq, _root_.WeierstrassCurve.Ψ₃,
      _root_.WeierstrassCurve.b₂, _root_.WeierstrassCurve.b₄, _root_.WeierstrassCurve.b₆,
      _root_.WeierstrassCurve.b₈, eval_add, eval_mul, eval_pow, eval_C, eval_X, eval_ofNat]
    ring
  exact hid ▸ dvd_sub (Dvd.dvd.mul_left hd _) hΨ₃

/-- **A common divisor of `Ψ₂Sq(x)` and `4·Ψ₃(x)` divides `4Δ`.**

This is the whole arithmetic content of the file. Beyond the two divisibility premises it assumes
nothing: it holds for every commutative ring, every `x` and every `d`, and no point of a curve
occurs in it. `4Δ` lies in the ideal generated by `Ψ₂Sq(x)` and `4·Ψ₃(x)` at any `x`, exhibited by
an explicit Bézout combination in the `b`-invariants. -/
theorem dvd_four_mul_Δ_of_dvd_Ψ₂Sq_of_dvd_four_mul_Ψ₃ {d : R} (hd : d ∣ (W.Ψ₂Sq).eval x)
    (hΨ₃ : d ∣ 4 * (W.Ψ₃).eval x) : d ∣ 4 * W.Δ := by
  rw [← bezout_four_mul_Δ W x]
  exact dvd_add (Dvd.dvd.mul_left hd _)
    (Dvd.dvd.mul_left (dvd_sq_of_dvd_Ψ₂Sq_of_dvd_four_mul_Ψ₃ W hd hΨ₃) _)

end WeierstrassCurve

end TauCeti
