/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.Analysis.Sobolev.Periodic.SolenoidalL2
import Mathlib.Analysis.InnerProductSpace.Dual
import Mathlib.Analysis.Normed.Operator.Bilinear

/-!
# The periodic incompressible Gelfand triple

This file packages the concrete functional-analytic chain

`V ⊂ H ⊂ V*`,

where `V` is mean-zero incompressible periodic `W¹,²`, `H` is the `L²` closure of its
quotient-native values, and `V*` is the strong real dual of `V`.  The first map is the value map
with codomain restricted to that closure.  It is injective by weak-derivative uniqueness and has
dense range by the definition of `H`.

The pivot map sends `h : H` to the functional `v ↦ inner ℝ h (VtoH v)`.  Its orientation is
kept explicit throughout.  Density of `V` in `H` makes this second map injective.

No Bochner spaces, time derivatives, or evolution equations are introduced here.

## Main declarations

* `PeriodicMeanZeroSolenoidalL2`: the concrete pivot Hilbert space `H`.
* `periodicEnergyInclusionL`: the continuous dense injection `V →L H`.
* `periodicEnergyInclusionL_denseRange`: density obtained from the closure definition of `H`.
* `periodicPivotEmbeddingL`: the continuous injection `H →L StrongDual ℝ V`.
-/

public section

noncomputable section

namespace TauCeti.UnitAddTorus

open MeasureTheory
open scoped ENNReal InnerProductSpace

variable {d : Type*} [Fintype d]

attribute [local instance] Classical.decEq

local instance (priority := 3000) ambientVectorL2InnerProductSpace :
    InnerProductSpace ℝ (PeriodicVectorL2 d) :=
  PiLp.innerProductSpace fun _ : d ↦ Lp ℝ 2 (volume : Measure (_root_.UnitAddTorus d))

local instance (priority := 3000) vectorW12InnerProductSpace :
    InnerProductSpace ℝ (PeriodicVectorW12 d) :=
  PiLp.innerProductSpace fun _ : d ↦ PeriodicW12 d

local instance (priority := 4000) energyNormedSpace :
    NormedSpace ℝ (PeriodicMeanZeroDivergenceFreeW12 d) :=
  (periodicMeanZeroDivergenceFreeW12Submodule d).toSubmodule.normedSpace

/-- The mean-zero solenoidal `L²` pivot space `H`, defined as the closed subspace generated by
values of the mean-zero incompressible periodic energy space. -/
abbrev PeriodicMeanZeroSolenoidalL2 (d : Type*) [Fintype d] :=
  (periodicMeanZeroSolenoidalL2Submodule d).toSubmodule

namespace PeriodicMeanZeroSolenoidalL2

/-- The ambient vector `L²` inner product restricted to the pivot subspace. -/
instance (priority := 2000) : InnerProductSpace ℝ (PeriodicMeanZeroSolenoidalL2 d) :=
  Submodule.innerProductSpace (periodicMeanZeroSolenoidalL2Submodule d).toSubmodule

/-- Completeness inherited from the defining closed ambient `L²` subspace. -/
instance : CompleteSpace (PeriodicMeanZeroSolenoidalL2 d) :=
  (periodicMeanZeroSolenoidalL2Submodule d).isClosed.completeSpace_coe

end PeriodicMeanZeroSolenoidalL2

namespace PeriodicVectorW12

/-- The quotient-native vector `L²` value norm is bounded by the full vector `W¹,²` graph
norm. -/
theorem norm_value_le (u : PeriodicVectorW12 d) : ‖value u‖ ≤ ‖u‖ := by
  have hgraph := norm_sq_eq_norm_value_sq_add_norm_weakJacobian_sq u
  nlinarith [sq_nonneg ‖value u‖, sq_nonneg ‖weakJacobian u‖,
    norm_nonneg (value u), norm_nonneg u]

end PeriodicVectorW12

/-- The continuous value inclusion from mean-zero incompressible periodic `W¹,²` into its
solenoidal `L²` closure. -/
def periodicEnergyInclusionL :
    PeriodicMeanZeroDivergenceFreeW12 d →L[ℝ] PeriodicMeanZeroSolenoidalL2 d :=
  periodicEnergyValueL.codRestrict
    (periodicMeanZeroSolenoidalL2Submodule d).toSubmodule
    periodicEnergyValueL_mem_periodicMeanZeroSolenoidalL2

/-- The inclusion has the expected ambient quotient-level value. -/
@[simp]
theorem periodicEnergyInclusionL_coe_apply
    (u : PeriodicMeanZeroDivergenceFreeW12 d) :
    ((periodicEnergyInclusionL u : PeriodicMeanZeroSolenoidalL2 d) :
        PeriodicVectorL2 d) =
      PeriodicVectorW12.value (u : PeriodicVectorW12 d) := by
  rw [periodicEnergyInclusionL, ContinuousLinearMap.coe_codRestrict_apply,
    periodicEnergyValueL_apply]

/-- The energy-to-pivot inclusion is contractive for the graph norm. -/
theorem norm_periodicEnergyInclusionL_apply_le
    (u : PeriodicMeanZeroDivergenceFreeW12 d) :
    ‖periodicEnergyInclusionL (d := d) u‖ ≤ ‖u‖ := by
  calc
    ‖periodicEnergyInclusionL (d := d) u‖ =
        ‖((periodicEnergyInclusionL (d := d) u : PeriodicMeanZeroSolenoidalL2 d) :
          PeriodicVectorL2 d)‖ := rfl
    _ = ‖PeriodicVectorW12.value (u : PeriodicVectorW12 d)‖ := by
      rw [periodicEnergyInclusionL_coe_apply]
    _ ≤ ‖(u : PeriodicVectorW12 d)‖ :=
      PeriodicVectorW12.norm_value_le (u : PeriodicVectorW12 d)
    _ = ‖u‖ := rfl

/-- Equality of quotient-level values determines an energy-space element, so the inclusion is
injective. -/
theorem periodicEnergyInclusionL_injective :
    Function.Injective (periodicEnergyInclusionL (d := d)) := by
  intro u v huv
  apply Subtype.ext
  apply PeriodicVectorW12.ext_component
  intro j
  apply PeriodicW12.ext_value
  have hj := congrArg
    (fun f : PeriodicMeanZeroSolenoidalL2 d ↦ ((f : PeriodicVectorL2 d) j)) huv
  simpa only [periodicEnergyInclusionL_coe_apply, PeriodicVectorW12.value_apply] using hj

/-- The energy inclusion has dense range in `H` directly from the definition of `H` as the
closure of energy values. -/
theorem periodicEnergyInclusionL_denseRange :
    DenseRange (periodicEnergyInclusionL (d := d)) := by
  rw [Metric.denseRange_iff]
  intro f r hr
  have hf := (mem_periodicMeanZeroSolenoidalL2Submodule_iff_approx
    (f : PeriodicVectorL2 d)).mp f.2
  rcases hf r hr with ⟨u, hu⟩
  refine ⟨u, ?_⟩
  change dist (f : PeriodicVectorL2 d) (periodicEnergyValueL u) < r
  exact hu

/-- The pivot embedding `H → V*`, oriented as
`periodicPivotEmbeddingL h v = inner ℝ h (periodicEnergyInclusionL v)`. -/
def periodicPivotEmbeddingL :
    PeriodicMeanZeroSolenoidalL2 d →L[ℝ]
      StrongDual ℝ (PeriodicMeanZeroDivergenceFreeW12 d) :=
  let innerMap : PeriodicMeanZeroSolenoidalL2 d →L[ℝ]
      PeriodicMeanZeroSolenoidalL2 d →L[ℝ] ℝ :=
    innerSL ℝ
  ContinuousLinearMap.flip (𝕜 := ℝ) (𝕜₂ := ℝ) (𝕜₃ := ℝ)
    (E := PeriodicMeanZeroSolenoidalL2 d)
    (F := PeriodicMeanZeroDivergenceFreeW12 d →L[ℝ]
      PeriodicMeanZeroSolenoidalL2 d)
    (G := StrongDual ℝ (PeriodicMeanZeroDivergenceFreeW12 d))
    (σ₂₃ := RingHom.id ℝ) (σ₁₃ := RingHom.id ℝ)
    (ContinuousLinearMap.precompR (𝕜 := ℝ)
      (E := PeriodicMeanZeroSolenoidalL2 d)
      (Fₗ := PeriodicMeanZeroSolenoidalL2 d) (Gₗ := ℝ)
      (PeriodicMeanZeroDivergenceFreeW12 d) innerMap)
    (periodicEnergyInclusionL (d := d))

/-- Evaluator formula fixing the orientation of the pivot duality pairing. -/
@[simp]
theorem periodicPivotEmbeddingL_apply_apply
    (h : PeriodicMeanZeroSolenoidalL2 d)
    (v : PeriodicMeanZeroDivergenceFreeW12 d) :
    periodicPivotEmbeddingL (d := d) h v =
      inner ℝ h (periodicEnergyInclusionL (d := d) v) := by
  rfl

/-- Ambient quotient-native `L²` form of the pivot pairing. -/
theorem periodicPivotEmbeddingL_apply_apply_eq_ambient_inner
    (h : PeriodicMeanZeroSolenoidalL2 d)
    (v : PeriodicMeanZeroDivergenceFreeW12 d) :
    periodicPivotEmbeddingL (d := d) h v =
      inner ℝ (h : PeriodicVectorL2 d)
        (PeriodicVectorW12.value (v : PeriodicVectorW12 d)) := by
  rw [periodicPivotEmbeddingL_apply_apply]
  change inner ℝ (h : PeriodicVectorL2 d)
    ((periodicEnergyInclusionL (d := d) v : PeriodicMeanZeroSolenoidalL2 d) :
      PeriodicVectorL2 d) = _
  rw [periodicEnergyInclusionL_coe_apply]

/-- The pivot embedding is contractive. -/
theorem norm_periodicPivotEmbeddingL_apply_le
    (h : PeriodicMeanZeroSolenoidalL2 d) :
    ‖periodicPivotEmbeddingL (d := d) h‖ ≤ ‖h‖ := by
  refine @ContinuousLinearMap.opNorm_le_bound ℝ ℝ
    (PeriodicMeanZeroDivergenceFreeW12 d) ℝ inferInstance inferInstance inferInstance
    inferInstance (energyNormedSpace (d := d)) inferInstance (RingHom.id ℝ)
    (periodicPivotEmbeddingL (d := d) h) ‖h‖ (norm_nonneg h) ?_
  intro v
  rw [periodicPivotEmbeddingL_apply_apply]
  calc
    ‖inner ℝ h (periodicEnergyInclusionL (d := d) v)‖ ≤
        ‖h‖ * ‖periodicEnergyInclusionL (d := d) v‖ := norm_inner_le_norm _ _
    _ ≤ ‖h‖ * ‖v‖ :=
      mul_le_mul_of_nonneg_left
        (norm_periodicEnergyInclusionL_apply_le (d := d) v) (norm_nonneg h)

/-- Density of `V` in `H` makes the pivot embedding injective. -/
theorem periodicPivotEmbeddingL_injective :
    Function.Injective (periodicPivotEmbeddingL (d := d)) := by
  intro h₁ h₂ hpivot
  have honRange :
      (fun h : PeriodicMeanZeroSolenoidalL2 d ↦ inner ℝ h₁ h) ∘
          periodicEnergyInclusionL (d := d) =
        (fun h : PeriodicMeanZeroSolenoidalL2 d ↦ inner ℝ h₂ h) ∘
          periodicEnergyInclusionL (d := d) := by
    funext v
    have hv := congrArg
      (fun F : StrongDual ℝ (PeriodicMeanZeroDivergenceFreeW12 d) ↦ F v) hpivot
    rw [periodicPivotEmbeddingL_apply_apply,
      periodicPivotEmbeddingL_apply_apply] at hv
    exact hv
  have hall :
      (fun h : PeriodicMeanZeroSolenoidalL2 d ↦ inner ℝ h₁ h) =
        fun h : PeriodicMeanZeroSolenoidalL2 d ↦ inner ℝ h₂ h :=
    (periodicEnergyInclusionL_denseRange (d := d)).equalizer
      (innerSL ℝ h₁).continuous (innerSL ℝ h₂).continuous honRange
  apply (InnerProductSpace.toDualMap ℝ (PeriodicMeanZeroSolenoidalL2 d)).injective
  apply ContinuousLinearMap.ext
  intro h
  exact congrFun hall h

end TauCeti.UnitAddTorus
