/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.Multiquadratic.MinusTwentyOne.Examples
public import TauCeti.NumberTheory.Multiquadratic.RelativeDegree
public import TauCeti.NumberTheory.Multiquadratic.Subfield.Classification

/-!
# The candidate genus field over `ℚ(√-21)`

The multiquadratic roadmap's second genus-field example uses the prime discriminants
`-4`, `-3`, and `-7`. Their associated radicands are `-1`, `-3`, and `-7`, with chosen
complex roots `i`, `i√3`, and `i√7`. The ambient compositum has degree eight over `ℚ`;
this file identifies the quadratic subfield generated by the product of those roots and
computes that the compositum has degree four over it.

The product root squares to `-21`, so its simple extension is the copy of `ℚ(√-21)`
inside the candidate genus field. The relative-degree calculation then specializes
`TauCeti.Multiquadratic.finrank_top_over_intermediateField_of_finrank_eq_two`.
This supplies the field-degree part of the roadmap's `ℚ(√-21)` acceptance example;
identifying the ambient compositum as the maximal unramified abelian extension is later work.

The prime-discriminant description follows D. A. Cox, *Primes of the Form x² + ny²*,
and F. Lemmermeyer's *Reciprocity Laws*.

## Main results

* `TauCeti.Multiquadratic.sqrtNegTwentyOneSubfield`: the quadratic subfield generated
  by the product `i · (i√3) · (i√7)`.
* `TauCeti.Multiquadratic.prodRootMem_univ_sq`: that product squares to `-21`.
* `TauCeti.Multiquadratic.finrank_candidateGenusField_over_sqrtNegTwentyOneSubfield`:
  the candidate genus field has degree four over this copy of `ℚ(√-21)`.
-/

public section

open IntermediateField

namespace TauCeti.Multiquadratic

/-- The radicands `-1`, `-3`, and `-7` are square-class independent over `ℚ`. -/
theorem not_isSquare_prod_minusTwentyOneRadicand (S : Finset (Fin 3)) (hS : S.Nonempty) :
    ¬ IsSquare (∏ i ∈ S, minusTwentyOneRadicand i) := by
  have hD : ∀ i : Fin 3, IsPrimeDiscriminant
      (negFourNegThreeNegSevenPrimeDiscriminants i) :=
    isPrimeDiscriminant_negFourNegThreeNegSevenPrimeDiscriminants
  simp_rw [minusTwentyOneRadicand_eq_primeDiscriminantRadicand]
  exact not_isSquare_prod_primeDiscriminantRadicands
    negFourNegThreeNegSevenPrimeDiscriminants hD
    injective_negFourNegThreeNegSevenPrimeDiscriminants
    not_all_three_evenPrimeDiscriminants_negFourNegThreeNegSevenPrimeDiscriminants S hS

/-- The copy of `ℚ(√-21)` inside the candidate genus field
`ℚ(i, √-3, √-7)`, generated by the product of its three chosen roots. -/
noncomputable def sqrtNegTwentyOneSubfield :
    IntermediateField ℚ
      (adjoin ℚ (Set.range minusTwentyOneRoot)) :=
  (quadraticSubfieldOfFinset minusTwentyOneRoot_sq
    not_isSquare_prod_minusTwentyOneRadicand
    ⟨Finset.univ, Finset.univ_nonempty⟩).1

/-- The named quadratic subfield is generated by the product of all three chosen roots. -/
@[simp] theorem sqrtNegTwentyOneSubfield_def :
    sqrtNegTwentyOneSubfield =
      adjoin ℚ
        {prodRootMem (K := ℚ) minusTwentyOneRoot (Finset.univ : Finset (Fin 3))} :=
  (quadraticSubfieldOfFinset_val minusTwentyOneRoot_sq
    not_isSquare_prod_minusTwentyOneRadicand
    ⟨Finset.univ, Finset.univ_nonempty⟩)

/-- The product of the three chosen roots is `i · (i√3) · (i√7)`. -/
@[simp] theorem prod_minusTwentyOneRoot :
    ∏ i, minusTwentyOneRoot i = Complex.I * sqrtNegThree * sqrtNegSeven := by
  rw [Fin.prod_univ_succ]
  simp [Fin.prod_univ_succ, mul_assoc]

/-- The product of all three chosen roots belongs to `sqrtNegTwentyOneSubfield`. -/
theorem prodRootMem_univ_mem_sqrtNegTwentyOneSubfield :
    prodRootMem (K := ℚ) minusTwentyOneRoot (Finset.univ : Finset (Fin 3))
      ∈ sqrtNegTwentyOneSubfield := by
  rw [sqrtNegTwentyOneSubfield_def]
  exact IntermediateField.subset_adjoin ℚ _ (Set.mem_singleton _)

/-- The generator of `sqrtNegTwentyOneSubfield` squares to `-21`. -/
@[simp] theorem prodRootMem_univ_sq :
    (prodRootMem (K := ℚ) minusTwentyOneRoot (Finset.univ : Finset (Fin 3))) ^ 2
      = algebraMap ℚ (adjoin ℚ (Set.range minusTwentyOneRoot)) (-21) := by
  have hprod :
      ∏ i : Fin 3, minusTwentyOneRadicand i = -21 := by
    rw [Fin.prod_univ_succ]
    norm_num [Fin.prod_univ_succ]
  rw [prodRootMem_sq minusTwentyOneRoot_sq]
  exact congrArg _ hprod

/-- The subfield generated by the product root of `-21` is quadratic over `ℚ`. -/
theorem finrank_sqrtNegTwentyOneSubfield :
    Module.finrank ℚ sqrtNegTwentyOneSubfield = 2 := by
  exact (quadraticSubfieldOfFinset minusTwentyOneRoot_sq
    not_isSquare_prod_minusTwentyOneRadicand
    ⟨Finset.univ, Finset.univ_nonempty⟩).2

/-- **The candidate genus field for `ℚ(√-21)` has relative degree four.**
The degree-eight compositum `ℚ(i, √-3, √-7)` has degree `4` over its quadratic
subfield generated by the product root, which squares to `-21`. -/
theorem finrank_candidateGenusField_over_sqrtNegTwentyOneSubfield :
    Module.finrank sqrtNegTwentyOneSubfield
      (adjoin ℚ (Set.range minusTwentyOneRoot)) = 4 := by
  have h := finrank_top_over_intermediateField_of_finrank_eq_two
    minusTwentyOneRoot_sq not_isSquare_prod_minusTwentyOneRadicand
    sqrtNegTwentyOneSubfield finrank_sqrtNegTwentyOneSubfield
  norm_num [Nat.card_fin] at h ⊢
  exact h

end TauCeti.Multiquadratic
