/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Logic.Relation
public import TauCeti.KnotTheory.Grid.Commutation.Move
public import TauCeti.KnotTheory.Grid.Stabilization.Basic

/-!
# Grid links as diagrams modulo grid moves

A commutation keeps the size of a grid diagram fixed, whereas a stabilization changes it by
one. Consequently the relation generated by both kinds of move cannot live on any one type
`GridDiagram n`; it lives on the dependent sum `Σ n, GridDiagram n` of diagrams of all sizes.

This file combines cyclic permutations, commutations, and stabilizations into
`GridDiagram.IsMove`, takes its equivalence closure as `GridDiagram.MovesTo`, and defines
`GridLink` to be the quotient by that relation. Thus a grid link is, by definition, a grid
diagram modulo cyclic permutations, commutations, and stabilizations. This is the combinatorial
input notion of link; its later reconciliation with embedded links is a separate target.

The quotient does not identify the chain maps attached to different move sequences. Later
naturality results should attach maps to `GridDiagram.IsMove` and prove their composition laws,
rather than extracting an untracked identification from equality in `GridLink`.

## Main definitions

* `TauCeti.GridDiagram.IsMove`: one cyclic permutation, commutation, stabilization, or
  destabilization between possibly differently sized diagrams.
* `TauCeti.GridDiagram.MovesTo`: the equivalence relation generated by elementary grid moves.
* `TauCeti.GridLink`: grid diagrams modulo grid moves.

## Main results

* `TauCeti.GridDiagram.toGridLink_eq_iff_movesTo`: two diagrams represent the same grid link
  exactly when they are connected by grid moves.
* `TauCeti.GridLink.lift`: define a function on grid links from a function on diagrams that is
  invariant under commutation and stabilization.

## References

This advances `TauCetiRoadmap/CombinatorialHeegaardFloer/README.md`, under "Standing
conventions", specifically "A link *is* (at first) a grid diagram modulo grid moves", using the
commutation and stabilization moves of Lane G.5. The presentation follows
Ozsvath--Stipsicz--Szabo, *Grid Homology for Knots and Links*, Chapter 3.
-/

public section

namespace TauCeti

namespace GridDiagram

/-- One elementary grid move between diagrams of possibly different sizes.

Cyclic permutations and commutations relate diagrams of the same size. A stabilization relates a
diagram of size `n` to one of size `n + 1`, and a destabilization records the reverse orientation
of the same local move. -/
inductive IsMove : (Σ n, GridDiagram n) → (Σ n, GridDiagram n) → Prop
  | cyclicRows {n : ℕ} {G G' : GridDiagram n}
      (h : G' = G.relabelRows (finRotate n) ∨ G = G'.relabelRows (finRotate n)) :
      IsMove ⟨n, G⟩ ⟨n, G'⟩
  | cyclicColumns {n : ℕ} {G G' : GridDiagram n}
      (h : G' = G.relabelColumns (finRotate n) ∨ G = G'.relabelColumns (finRotate n)) :
      IsMove ⟨n, G⟩ ⟨n, G'⟩
  | commutation {n : ℕ} {G G' : GridDiagram n} (h : IsCommutation G G') :
      IsMove ⟨n, G⟩ ⟨n, G'⟩
  | stabilization {n : ℕ} {G : GridDiagram n} {G' : GridDiagram (n + 1)}
      (h : IsStabilization G G') : IsMove ⟨n, G⟩ ⟨n + 1, G'⟩
  | destabilization {n : ℕ} {G : GridDiagram n} {G' : GridDiagram (n + 1)}
      (h : IsDestabilization G' G) : IsMove ⟨n + 1, G'⟩ ⟨n, G⟩

/-- Every elementary grid move is reversible. -/
theorem IsMove.symm {G G' : Σ n, GridDiagram n} (h : IsMove G G') : IsMove G' G := by
  cases h with
  | cyclicRows h => exact .cyclicRows (h.elim Or.inr Or.inl)
  | cyclicColumns h => exact .cyclicColumns (h.elim Or.inr Or.inl)
  | commutation h => exact .commutation (isCommutation_comm.mp h)
  | stabilization h =>
      exact .destabilization (isDestabilization_iff_isStabilization _ _ |>.mpr h)
  | destabilization h =>
      exact .stabilization (isDestabilization_iff_isStabilization _ _ |>.mp h)

/-- Two grid diagrams are related by grid moves when they lie in the equivalence relation
generated by cyclic permutations, commutations, stabilizations, and destabilizations. -/
def MovesTo {n m : ℕ} (G : GridDiagram n) (G' : GridDiagram m) : Prop :=
  Relation.EqvGen IsMove ⟨n, G⟩ ⟨m, G'⟩

/-- Every grid diagram is related to itself by the empty sequence of moves. -/
@[refl]
theorem MovesTo.refl {n : ℕ} (G : GridDiagram n) : MovesTo G G :=
  Relation.EqvGen.refl _

/-- A sequence of grid moves can be traversed in reverse. -/
@[symm]
theorem MovesTo.symm {n m : ℕ} {G : GridDiagram n} {G' : GridDiagram m}
    (h : MovesTo G G') : MovesTo G' G :=
  Relation.EqvGen.symm _ _ h

/-- Sequences of grid moves compose. -/
@[trans]
theorem MovesTo.trans {n m k : ℕ} {G : GridDiagram n} {G' : GridDiagram m}
    {G'' : GridDiagram k} (h : MovesTo G G') (h' : MovesTo G' G'') :
    MovesTo G G'' :=
  Relation.EqvGen.trans _ _ _ h h'

/-- One elementary move gives a sequence of grid moves of length one. -/
theorem IsMove.movesTo {n m : ℕ} {G : GridDiagram n} {G' : GridDiagram m}
    (h : IsMove ⟨n, G⟩ ⟨m, G'⟩) : MovesTo G G' :=
  Relation.EqvGen.rel _ _ h

/-- A cyclic permutation of the rows gives a grid-move relation. -/
theorem cyclicRows_movesTo {n : ℕ} (G : GridDiagram n) :
    MovesTo G (G.relabelRows (finRotate n)) :=
  IsMove.movesTo (.cyclicRows (Or.inl rfl))

/-- A cyclic permutation of the columns gives a grid-move relation. -/
theorem cyclicColumns_movesTo {n : ℕ} (G : GridDiagram n) :
    MovesTo G (G.relabelColumns (finRotate n)) :=
  IsMove.movesTo (.cyclicColumns (Or.inl rfl))

/-- An elementary commutation gives a grid-move relation. -/
theorem IsCommutation.movesTo {n : ℕ} {G G' : GridDiagram n}
    (h : IsCommutation G G') : MovesTo G G' :=
  IsMove.movesTo (.commutation h)

/-- An elementary stabilization gives a grid-move relation. -/
theorem IsStabilization.movesTo {n : ℕ} {G : GridDiagram n} {G' : GridDiagram (n + 1)}
    (h : IsStabilization G G') : MovesTo G G' :=
  IsMove.movesTo (.stabilization h)

/-- An elementary destabilization gives a grid-move relation. -/
theorem IsDestabilization.movesTo {n : ℕ} {G : GridDiagram n} {G' : GridDiagram (n + 1)}
    (h : IsDestabilization G' G) : MovesTo G' G :=
  IsMove.movesTo (.destabilization h)

end GridDiagram

/-- A grid link is a grid diagram, of arbitrary size, modulo cyclic permutations, commutations,
and stabilizations.

This is the combinatorial notion of link used by grid homology. Identifying it with an ambient
isotopy class of embedded links is the separate Cromwell-reconciliation target. -/
def GridLink := Quot GridDiagram.IsMove

namespace GridDiagram

variable {n m : ℕ} (G : GridDiagram n)

/-- The grid link represented by a grid diagram. -/
def toGridLink : GridLink :=
  Quot.mk GridDiagram.IsMove ⟨n, G⟩

/-- Two grid diagrams represent the same grid link exactly when they are connected by grid
moves. -/
theorem toGridLink_eq_iff_movesTo {G' : GridDiagram m} :
    G.toGridLink = G'.toGridLink ↔ MovesTo G G' :=
  ⟨Quot.eqvGen_exact, Quot.eqvGen_sound⟩

/-- One elementary grid move does not change the represented grid link. -/
theorem IsMove.toGridLink_eq {G : GridDiagram n} {G' : GridDiagram m}
    (h : IsMove ⟨n, G⟩ ⟨m, G'⟩) : G.toGridLink = G'.toGridLink :=
  Quot.sound h

/-- A cyclic permutation of the rows does not change the represented grid link. -/
theorem cyclicRows_toGridLink_eq :
    G.toGridLink = (G.relabelRows (finRotate n)).toGridLink :=
  IsMove.toGridLink_eq (.cyclicRows (Or.inl rfl))

/-- A cyclic permutation of the columns does not change the represented grid link. -/
theorem cyclicColumns_toGridLink_eq :
    G.toGridLink = (G.relabelColumns (finRotate n)).toGridLink :=
  IsMove.toGridLink_eq (.cyclicColumns (Or.inl rfl))

/-- A commutation does not change the represented grid link. -/
theorem IsCommutation.toGridLink_eq {G G' : GridDiagram n} (h : IsCommutation G G') :
    G.toGridLink = G'.toGridLink :=
  IsMove.toGridLink_eq (.commutation h)

/-- A stabilization does not change the represented grid link. -/
theorem IsStabilization.toGridLink_eq {G : GridDiagram n} {G' : GridDiagram (n + 1)}
    (h : IsStabilization G G') : G.toGridLink = G'.toGridLink :=
  IsMove.toGridLink_eq (.stabilization h)

/-- A destabilization does not change the represented grid link. -/
theorem IsDestabilization.toGridLink_eq {G : GridDiagram n} {G' : GridDiagram (n + 1)}
    (h : IsDestabilization G' G) : G'.toGridLink = G.toGridLink :=
  IsMove.toGridLink_eq (.destabilization h)

end GridDiagram

namespace GridLink

variable {α : Sort*}

/-- Every grid link can be handled by considering a grid diagram representing it. -/
theorem ind {motive : GridLink → Prop}
    (h : ∀ {n} (G : GridDiagram n), motive G.toGridLink) : ∀ L, motive L :=
  Quot.ind fun G => h G.2

/-- Define a function on grid links from a function on grid diagrams that is invariant under
cyclic permutations, elementary commutations, and stabilizations.

No separate destabilization hypothesis is needed: invariance under a stabilization supplies
the reverse equality as well. -/
def lift (f : ∀ n, GridDiagram n → α)
    (hrows : ∀ {n} (G : GridDiagram n), f n G = f n (G.relabelRows (finRotate n)))
    (hcolumns : ∀ {n} (G : GridDiagram n), f n G = f n (G.relabelColumns (finRotate n)))
    (hcomm : ∀ {n} {G G' : GridDiagram n}, GridDiagram.IsCommutation G G' →
      f n G = f n G')
    (hstab : ∀ {n} {G : GridDiagram n} {G' : GridDiagram (n + 1)},
      GridDiagram.IsStabilization G G' → f n G = f (n + 1) G') :
    GridLink → α :=
  Quot.lift (fun G => f G.1 G.2) fun G G' h => by
    cases h with
    | cyclicRows h =>
        rcases h with h | h
        · cases h
          exact hrows _
        · cases h
          exact (hrows _).symm
    | cyclicColumns h =>
        rcases h with h | h
        · cases h
          exact hcolumns _
        · cases h
          exact (hcolumns _).symm
    | commutation h => exact hcomm h
    | stabilization h => exact hstab h
    | destabilization h =>
        exact (hstab (GridDiagram.isDestabilization_iff_isStabilization _ _ |>.mp h)).symm

/-- Evaluating a lifted function on the class of a diagram recovers its value on that
diagram. -/
theorem lift_toGridLink (f : ∀ n, GridDiagram n → α)
    (hrows : ∀ {n} (G : GridDiagram n), f n G = f n (G.relabelRows (finRotate n)))
    (hcolumns : ∀ {n} (G : GridDiagram n), f n G = f n (G.relabelColumns (finRotate n)))
    (hcomm : ∀ {n} {G G' : GridDiagram n}, GridDiagram.IsCommutation G G' →
      f n G = f n G')
    (hstab : ∀ {n} {G : GridDiagram n} {G' : GridDiagram (n + 1)},
      GridDiagram.IsStabilization G G' → f n G = f (n + 1) G')
    {n : ℕ} (G : GridDiagram n) :
    lift f hrows hcolumns hcomm hstab G.toGridLink = f n G :=
  (rfl)

end GridLink

end TauCeti
