/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.FieldTheory.Finite.Basic
public import Mathlib.FieldTheory.RatFunc.IntermediateField

/-!
# The `q`-th powers in a rational function field

For a finite field `K` with `q` elements, the `q`-power map is a `K`-algebra endomorphism of the
rational function field `K(X)` (Mathlib's `FiniteField.frobeniusAlgHom`). Its image is the
subfield `K(X^q)`, and `K(X)` has degree exactly `q` over it.

## Main results

* `TauCeti.RatFunc.finrank_adjoin_X_pow`: `[K(X) : K(X^n)] = n`, over any field and for any `n`.
* `TauCeti.FiniteField.fieldRange_frobeniusAlgHom_ratFunc`: the image of the `q`-power map on
  `K(X)` is `K⟮X ^ q⟯`.
* `TauCeti.FiniteField.finrank_fieldRange_frobeniusAlgHom_ratFunc`: `[K(X) : K(X^q)] = q`, the two
  above combined.

All three are `@[simp]`.

## Roadmap

`TauCetiRoadmap/EllipticCurves/README.md`, **Layer 1**, the Frobenius isogeny — "the key input to
Layer 3". The layer seeds

```lean
noncomputable def Isogeny.degree (φ : Isogeny W₁ W₂) : ℕ :=
  Module.finrank φ.fieldPullback.fieldRange W₁.FunctionField
theorem degree_frobeniusIsogeny [Finite F] (W : WeierstrassCurve.Affine F) :
    (frobeniusIsogeny W).degree = Nat.card F
```

so the target is `Module.finrank` of `K(W)` over the field range of the `q`-power map. This file
proves that statement for the rational function field. It is what the seeded degree is computed
from: `K(x^q)` sits below both `K(x)` and `K(W)^q` inside `K(W)`, the two intermediate degrees
`[K(W) : K(x)]` and `[K(W)^q : K(x^q)]` are both `2`, and the tower law along the two routes reads
`[K(W) : K(W)^q] · 2 = 2 · [K(x) : K(x^q)]`. The right-hand factor is the `q` proved here.

## Provenance

Ported from the AINTLIB `HasseWeil` project (`github.com/CBirkbeck/AINTLIB`, Apache-2.0, pinned by
that roadmap at `dev/hasse-weil @ 513e83879e2f`), `HasseWeil/FrobeniusIsogeny.lean`, declarations
`frobenius_fieldRange_ratFunc` and `finrank_ratFunc_frobenius`.

Changes from the source. Both are `private` there, inside the file that builds the Frobenius
isogeny, and are stated with an elliptic curve and a `DecidableEq K` in scope; neither is used by
either proof, and neither statement mentions a curve. The degree is separated out here as
`RatFunc.finrank_adjoin_X_pow`, over an arbitrary field and exponent, since nothing in it is about
the Frobenius.

Neither proof is ported. The source computes the field range by hand, passing an element of `K(X)`
to its numerator and denominator and applying `FiniteField.expand_card` to each; Mathlib's
`IsFractionRing.algHom_fieldRange_eq_of_comp_eq_of_range_eq` does that passage generically, so all
that is left is to identify the restriction of the `q`-power map to `K[X]` with evaluation at
`X ^ q` — one application of `Polynomial.algHom_ext` — and to name its range with
`Algebra.adjoin_singleton_eq_range_aeval`.
-/

public section

open Polynomial

namespace TauCeti

namespace RatFunc

/-- **`[K(X) : K(X ^ n)] = n`** for any field `K` and any `n`. At `n = 0` both sides read `0`:
`K⟮1⟯` is `K`, over which `K(X)` is infinite-dimensional, and `Module.finrank` reports `0`. -/
@[simp]
theorem finrank_adjoin_X_pow (K : Type*) [Field K] (n : ℕ) :
    Module.finrank (IntermediateField.adjoin K {(_root_.RatFunc.X : _root_.RatFunc K) ^ n})
      (_root_.RatFunc K) = n := by
  -- `X ^ n` as the image of a polynomial, so that `finrank_eq_max_natDegree` reads its
  -- numerator and denominator off `X ^ n` and `1`
  rw [← _root_.RatFunc.algebraMap_X, ← map_pow, _root_.RatFunc.finrank_eq_max_natDegree,
    _root_.RatFunc.num_algebraMap, _root_.RatFunc.denom_algebraMap, natDegree_X_pow,
    natDegree_one, Nat.max_zero]

end RatFunc

namespace FiniteField

variable (K : Type*) [Field K] [Fintype K]

/-- **The `q`-th powers in `K(X)` are the rational functions in `X ^ q`.** -/
@[simp]
theorem fieldRange_frobeniusAlgHom_ratFunc :
    (_root_.FiniteField.frobeniusAlgHom K (RatFunc K)).fieldRange =
      IntermediateField.adjoin K {(RatFunc.X : RatFunc K) ^ Fintype.card K} := by
  -- The `q`-power map restricts to `K[X]` as evaluation at `X ^ q`, whose range is the algebra
  -- generated by `X ^ q`; `IsFractionRing` then passes both facts to `K(X)`.
  refine IsFractionRing.algHom_fieldRange_eq_of_comp_eq_of_range_eq (A := K[X])
    (g := aeval ((RatFunc.X : RatFunc K) ^ Fintype.card K)) ?_
    (Algebra.adjoin_singleton_eq_range_aeval K _).symm
  have h : (_root_.FiniteField.frobeniusAlgHom K (RatFunc K)).comp
      (IsScalarTower.toAlgHom K K[X] (RatFunc K))
      = aeval ((RatFunc.X : RatFunc K) ^ Fintype.card K) :=
    Polynomial.algHom_ext (by
      simp [_root_.FiniteField.frobeniusAlgHom_apply, RatFunc.algebraMap_X])
  exact congrArg (fun a : K[X] →ₐ[K] RatFunc K => (a : K[X] →+* RatFunc K)) h

/-- **The rational function field has degree `q` over its subfield of `q`-th powers.** -/
@[simp]
theorem finrank_fieldRange_frobeniusAlgHom_ratFunc :
    Module.finrank (_root_.FiniteField.frobeniusAlgHom K (RatFunc K)).fieldRange (RatFunc K) =
      Fintype.card K := by
  rw [fieldRange_frobeniusAlgHom_ratFunc K, TauCeti.RatFunc.finrank_adjoin_X_pow]

end FiniteField

end TauCeti

end
