/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Geometry.Lie.Adjoint.Derivation
public import TauCeti.Geometry.Lie.Exponential.Basic

/-!
# Naturality of the Lie-group exponential under conjugation

Conjugation transports the integral curve generated by a tangent vector to the integral curve
generated by its tangent adjoint image. Evaluating at time one gives the conjugation formula for
the Lie-group exponential. No separate Hausdorff or boundaryless hypotheses are needed: both
follow from the Lie-group structure.

This advances Deliverable A, Layer 1 of
`TauCetiRoadmap/RepresentationTheory/LieGroups/README.md`.

## Main results

* `TauCeti.Lie.conj_mulInvariantIntegralCurve`: conjugation transports canonical invariant
  integral curves and their basepoints through `tangentAd`.
* `TauCeti.Lie.conj_mulInvariantExp`: conjugating `mulInvariantExp X` by `g` gives the
  exponential of `tangentAd g X`.
* `TauCeti.Lie.conj_lieExp`: conjugating `lieExp X` by `g` gives the exponential of `Ad g X`.

## References

* [Lie groups and the Lie algebra correspondence roadmap](https://github.com/TauCetiProject/TauCetiRoadmap/blob/main/TauCetiRoadmap/RepresentationTheory/LieGroups/README.md),
  Deliverable A, Layer 1, "The conjugation formulas".
-/

public section

noncomputable section

namespace TauCeti.Lie

open scoped ContDiff Manifold

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
  {H : Type*} [TopologicalSpace H] {I : ModelWithCorners ℝ E H}
  {G : Type*} [TopologicalSpace G] [ChartedSpace H G] [Group G]

section Tangent

variable [CompleteSpace E] [LieGroup I 3 G] [IsManifold I 1 G]

attribute [local instance] LieGroup.minSmoothnessThree

local instance lieGroupOneAdjointExponential : LieGroup I 1 G :=
  LieGroup.of_le (I := I) (G := G) (m := 1) (n := 3) (by norm_num)

attribute [local instance] ContMDiffMul.boundarylessManifold

/-- Conjugation transports the canonical invariant integral curve generated by `X` to the one
generated by the tangent adjoint image of `X`, with the basepoint conjugated as well. -/
@[simp]
theorem conj_mulInvariantIntegralCurve (g : G) (X : GroupLieAlgebra I G) (x : G) (t : ℝ) :
    let _ : T2Space G := t2Space_of_lieGroup (I := I) (n := 3)
    g * mulInvariantIntegralCurve (I := I) (G := G) X x t * g⁻¹ =
      mulInvariantIntegralCurve (tangentAd (I := I) g X) (g * x * g⁻¹) t := by
  let _ : T2Space G := t2Space_of_lieGroup (I := I) (n := 3)
  dsimp only
  let Φ := conjDiffeomorph (I := I) (n := 1) g
  let γ := mulInvariantIntegralCurve (I := I) (G := G) X x
  have hcurve : IsMIntegralCurve (Φ ∘ γ)
      (mulInvariantVectorField (tangentAd (I := I) g X)) := by
    rw [isMIntegralCurve_iff_isMIntegralCurveOn]
    apply ((isMIntegralCurve_mulInvariantIntegralCurve
      (I := I) (G := G) X x).isMIntegralCurveOn Set.univ).map_of_mfderiv_eq
    · intro t _
      exact Φ.contMDiff.mdifferentiable (by simp) (γ t)
    · intro t _
      dsimp only [Φ]
      rw [mfderiv_conjugation_mulInvariantVectorField, tangentAd_apply]
  have hzero : (Φ ∘ γ) 0 = g * x * g⁻¹ := by simp [Φ, γ]
  have heq : Φ ∘ γ =
      mulInvariantIntegralCurve (tangentAd (I := I) g X) (g * x * g⁻¹) :=
    eq_mulInvariantIntegralCurve (tangentAd (I := I) g X) (g * x * g⁻¹) hzero hcurve
  simpa only [Φ, γ, Function.comp_apply, conjDiffeomorph_apply] using congrFun heq t

/-- Conjugating `mulInvariantExp X` by `g` gives the exponential of `tangentAd g X`. -/
@[simp]
theorem conj_mulInvariantExp (g : G) (X : GroupLieAlgebra I G) :
    let _ : T2Space G := t2Space_of_lieGroup (I := I) (n := 3)
    g * mulInvariantExp (I := I) (G := G) X * g⁻¹ =
      mulInvariantExp (tangentAd (I := I) g X) := by
  let _ : T2Space G := t2Space_of_lieGroup (I := I) (n := 3)
  dsimp only
  rw [mulInvariantExp_eq_mulInvariantIntegralCurve,
    mulInvariantExp_eq_mulInvariantIntegralCurve]
  simp

end Tangent

section Derivation

variable [FiniteDimensional ℝ E] [LieGroup I ∞ G]

attribute [local instance] LieGroup.minSmoothnessThree

attribute [local instance] ContMDiffMul.boundarylessManifold

/-- Conjugating the group-valued exponential of `X` by `g` gives the exponential of `Ad g X`. -/
@[simp]
theorem conj_lieExp (g : G) (X : LeftInvariantDerivation I G) :
    let _ : T2Space G := t2Space_of_lieGroup (I := I) (n := ∞)
    g * lieExp (I := I) X * g⁻¹ = lieExp (Ad (I := I) g X) := by
  let _ : T2Space G := t2Space_of_lieGroup (I := I) (n := ∞)
  dsimp only
  rw [lieExp_eq_mulInvariantExp, lieExp_eq_mulInvariantExp]
  rw [conj_mulInvariantExp]
  congr 1
  rw [← leftInvariantDerivationLieEquivGroupLieAlgebra_apply,
    ← leftInvariantDerivationLieEquivGroupLieAlgebra_apply]
  exact (leftInvariantDerivationLieEquivGroupLieAlgebra_Ad (I := I) g X).symm

end Derivation

end TauCeti.Lie
