/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Geometry.Lie.Adjoint.Infinitesimal
public import TauCeti.Analysis.Normed.Operator.Exponential
public import Mathlib.Topology.Algebra.Module.FiniteDimension
import Mathlib.Analysis.ODE.ExistUnique

/-!
# The tangent adjoint action on the Lie-group exponential

The tangent adjoint representation along the one-parameter subgroup generated by `X` and the
operator exponential of `ad X` solve the same linear differential equation with the same initial
value. Uniqueness identifies them, proving the tangent-space form of the headline Layer 1 formula
`Ad (lieExp X) = exp (ad X)`.

This advances Deliverable A, Layer 1 of
`TauCetiRoadmap/RepresentationTheory/LieGroups/README.md`.

## Main results

* `TauCeti.Lie.hasDerivAt_tangentAd_mulInvariantExp_smul_apply`: the tangent adjoint orbit solves
  the linear differential equation generated by `ad X` at every time.
* `TauCeti.Lie.tangentAd_mulInvariantExp_apply`: the tangent adjoint-exponential formula.
* `TauCeti.Lie.tangentAd_mulInvariantExp_smul_self`: the generated one-parameter subgroup fixes its
  generator under the tangent adjoint action.

## References

* [Lie groups and the Lie algebra correspondence roadmap](https://github.com/TauCetiProject/TauCetiRoadmap/blob/main/TauCetiRoadmap/RepresentationTheory/LieGroups/README.md),
  Deliverable A, Layer 1, "The conjugation formulas".
-/

public section

noncomputable section

namespace TauCeti.Lie

open Set
open scoped ContDiff Manifold

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
  {H : Type*} [TopologicalSpace H] {I : ModelWithCorners ℝ E H}
  {G : Type*} [TopologicalSpace G] [ChartedSpace H G] [Group G]
  [FiniteDimensional ℝ E] [LieGroup I ∞ G]

attribute [local instance] LieGroup.minSmoothnessThree
attribute [local instance] ContMDiffMul.boundarylessManifold

/-- At every time, the tangent adjoint orbit solves the linear ODE generated by `ad X`. -/
theorem hasDerivAt_tangentAd_mulInvariantExp_smul_apply
    (X Y : GroupLieAlgebra I G) (t : ℝ) :
    let _ : T2Space G := t2Space_of_lieGroup (I := I) (n := ∞)
    let f : ℝ → E := fun s => (show E from tangentAd (I := I)
      (mulInvariantExp (I := I) (G := G) (s • X)) Y)
    HasDerivAt f
      ((Module.End.toContinuousLinearMap E)
        ((groupLieAlgebraEquivModelVectorSpace (I := I) (G := G)).conj
          (LieAlgebra.ad ℝ (GroupLieAlgebra I G) X)) (f t)) t := by
  let _ : T2Space G := t2Space_of_lieGroup (I := I) (n := ∞)
  dsimp only
  let f : ℝ → E := fun s => (show E from tangentAd (I := I)
    (mulInvariantExp (I := I) (G := G) (s • X)) Y)
  -- The orbit is model-space-valued because `GroupLieAlgebra I G` definitionally reduces to `E`;
  -- the explicit ascriptions below expose that boundary to the normed derivative API.
  have hzero := hasDerivAt_tangentAd_mulInvariantExp_smul_apply_zero
    (I := I) (G := G) X (show GroupLieAlgebra I G from f t)
  have hshift : f = fun s => (show E from tangentAd (I := I)
      (mulInvariantExp (I := I) (G := G) ((s - t) • X))
      (show GroupLieAlgebra I G from f t)) := by
    funext s
    -- Unfold the local orbit `f` and present both tangent values in the model space.
    change (show E from tangentAd (I := I)
        (mulInvariantExp (I := I) (G := G) (s • X)) Y) =
      (show E from tangentAd (I := I)
        (mulInvariantExp (I := I) (G := G) ((s - t) • X))
        (tangentAd (I := I) (mulInvariantExp (I := I) (G := G) (t • X)) Y))
    calc
      _ = (show E from tangentAd (I := I)
          (mulInvariantExp (I := I) (G := G) (((s - t) + t) • X)) Y) := by
        rw [sub_add_cancel]
      _ = (show E from tangentAd (I := I)
          (mulInvariantExp (I := I) (G := G) ((s - t) • X) *
            mulInvariantExp (I := I) (G := G) (t • X)) Y) := by
        rw [mulInvariantExp_add_smul]
      _ = _ := by rw [tangentAd_mul, LieEquiv.trans_apply]
  have hcomp := hzero.scomp_of_eq t ((hasDerivAt_id t).sub_const t) (by simp)
  have hderiv : HasDerivAt
      (fun s => (show E from tangentAd (I := I)
        (mulInvariantExp (I := I) (G := G) ((s - t) • X))
        (show GroupLieAlgebra I G from f t)))
      (show E from LieAlgebra.ad ℝ (GroupLieAlgebra I G) X
        (show GroupLieAlgebra I G from f t)) t := by
    -- Expose the shifted curve produced by scalar composition in the same model-space form.
    change HasDerivAt
      (fun s => (show E from tangentAd (I := I)
        (mulInvariantExp (I := I) (G := G) ((s - t) • X))
        (show GroupLieAlgebra I G from f t))) _ t at hcomp
    convert hcomp using 1
    exact (one_smul ℝ (show E from LieAlgebra.ad ℝ (GroupLieAlgebra I G) X
      (show GroupLieAlgebra I G from f t))).symm
  rw [← hshift] at hderiv
  -- Fold the local orbit and bounded adjoint operator back into the theorem's target.
  change HasDerivAt f
    ((Module.End.toContinuousLinearMap E)
      ((groupLieAlgebraEquivModelVectorSpace (I := I) (G := G)).conj
        (LieAlgebra.ad ℝ (GroupLieAlgebra I G) X)) (f t)) t
  apply hderiv.congr_deriv
  rfl

/-- Applying the tangent operator exponential to `Y` solves the linear ODE generated by `ad X`. -/
private theorem hasDerivAt_exp_adContinuousLinearMap_apply
    (X Y : GroupLieAlgebra I G) (t : ℝ) :
    let A := (Module.End.toContinuousLinearMap E)
      ((groupLieAlgebraEquivModelVectorSpace (I := I) (G := G)).conj
        (LieAlgebra.ad ℝ (GroupLieAlgebra I G) X))
    HasDerivAt (fun s : ℝ => NormedSpace.exp (s • A) (show E from Y))
      (A (NormedSpace.exp (t • A) (show E from Y))) t := by
  dsimp only
  let A := (Module.End.toContinuousLinearMap E)
    ((groupLieAlgebraEquivModelVectorSpace (I := I) (G := G)).conj
      (LieAlgebra.ad ℝ (GroupLieAlgebra I G) X))
  -- `GroupLieAlgebra I G` is definitionally the model space `E`, while the normed operator
  -- exponential and its derivative are stated on `E`.
  have hexp := hasDerivAt_exp_smul_const' A t
  have heval := (ContinuousLinearMap.apply ℝ E (show E from Y)).hasFDerivAt
    |>.comp_hasDerivAt t hexp
  -- Evaluation of the operator exponential has the displayed derivative by definitional
  -- reduction of continuous-linear-map application.
  convert heval using 1 <;> rfl

/-- The tangent adjoint action of `mulInvariantExp X`, evaluated on `Y`, is the operator
exponential of `ad X`. -/
theorem tangentAd_mulInvariantExp_apply (X Y : GroupLieAlgebra I G) :
    let _ : T2Space G := t2Space_of_lieGroup (I := I) (n := ∞)
    (show E from tangentAd (I := I) (mulInvariantExp (I := I) (G := G) X) Y) =
      NormedSpace.exp
        ((Module.End.toContinuousLinearMap E)
          ((groupLieAlgebraEquivModelVectorSpace (I := I) (G := G)).conj
            (LieAlgebra.ad ℝ (GroupLieAlgebra I G) X)))
        (show E from Y) := by
  let _ : T2Space G := t2Space_of_lieGroup (I := I) (n := ∞)
  dsimp only
  let A := (Module.End.toContinuousLinearMap E)
    ((groupLieAlgebraEquivModelVectorSpace (I := I) (G := G)).conj
      (LieAlgebra.ad ℝ (GroupLieAlgebra I G) X))
  -- `GroupLieAlgebra I G` is definitionally the model space `E`, while the normed operator
  -- exponential is stated on `E`; the explicit ascriptions expose that boundary.
  let f : ℝ → E := fun t => (show E from tangentAd (I := I)
    (mulInvariantExp (I := I) (G := G) (t • X)) Y)
  let g : ℝ → E := fun t => NormedSpace.exp (t • A) (show E from Y)
  have hf (t : ℝ) : HasDerivAt f (A (f t)) t := by
    simpa only [f, A] using
      hasDerivAt_tangentAd_mulInvariantExp_smul_apply (I := I) (G := G) X Y t
  have hg (t : ℝ) : HasDerivAt g (A (g t)) t := by
    simpa only [g, A] using
      hasDerivAt_exp_adContinuousLinearMap_apply (I := I) (G := G) X Y t
  have hv : ∀ _ : ℝ, LipschitzOnWith ‖A‖₊ A univ :=
    fun _ => A.lipschitz.lipschitzOnWith
  have hinitial : f 0 = g 0 := by
    dsimp only [f, g]
    -- Expose the two local curve definitions at zero before applying their unit laws.
    change (show E from tangentAd (I := I)
      (mulInvariantExp (I := I) (G := G) (0 • X)) Y) =
      NormedSpace.exp (0 • A) (show E from Y)
    rw [zero_smul, mulInvariantExp_zero, tangentAd_one, LieEquiv.refl_apply]
    rw [zero_smul, NormedSpace.exp_zero, one_apply_eq_self]
  have hfg : f = g := ODE_solution_unique_univ (K := ‖A‖₊)
    (v := fun _ => A) (s := fun _ => univ) (t₀ := 0) hv
    (fun t => ⟨hf t, mem_univ _⟩) (fun t => ⟨hg t, mem_univ _⟩) hinitial
  simpa only [f, g, one_smul, A] using congrFun hfg 1

/-- The tangent adjoint action of the one-parameter subgroup generated by `X` fixes `X`. -/
theorem tangentAd_mulInvariantExp_smul_self (X : GroupLieAlgebra I G) (t : ℝ) :
    let _ : T2Space G := t2Space_of_lieGroup (I := I) (n := ∞)
    tangentAd (I := I) (mulInvariantExp (I := I) (G := G) (t • X)) X = X := by
  let _ : T2Space G := t2Space_of_lieGroup (I := I) (n := ∞)
  dsimp only
  let A := (Module.End.toContinuousLinearMap E)
    ((groupLieAlgebraEquivModelVectorSpace (I := I) (G := G)).conj
      (LieAlgebra.ad ℝ (GroupLieAlgebra I G) X))
  have hAX_eq_bracket : A (show E from X) =
      (show E from LieAlgebra.ad ℝ (GroupLieAlgebra I G) X X) := by
    rfl
  have hAX : A (show E from X) = 0 := by
    rw [hAX_eq_bracket, LieAlgebra.ad_apply, lie_self]
    rfl
  change (show E from tangentAd (I := I)
    (mulInvariantExp (I := I) (G := G) (t • X)) X) = (show E from X)
  rw [tangentAd_mulInvariantExp_apply]
  simp only [map_smul]
  apply sub_eq_zero.mp
  -- Re-expose the definitionally equal model representatives so the general operator-exponential
  -- integral identity matches this tangent-Lie-algebra goal.
  change NormedSpace.exp (t • A) (show E from X) - (show E from X) = 0
  rw [ContinuousLinearMap.exp_smul_apply_sub_eq_intervalIntegral, hAX]
  simp only [map_zero, intervalIntegral.integral_zero]
end TauCeti.Lie
