/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RingTheory.Huber.LocalizationTopology.Completion

/-!
# The plus ring `A_U⁺` of a rational localisation

For a rational subset `U = R(T/s)` of `Spa(A, A⁺)`, roadmap Layer 3.1 asks for `A_U⁺`: the integral
closure in `A_U = A⟨T/s⟩` of the image of the subring generated by `A⁺` and the fractions `t/s`.
This file defines it, following the roadmap's wording exactly: one integral closure, taken in
`A_U`, of the image of `A⁺[T/s]`.

## The layers

```text
Algebra.adjoin A⁺ {t/s}   A⁺[t₁/s, …, tₙ/s]  (Mathlib's, unwrapped)  ⊆ Aₛ
completedPlusSubringBase  its image                                  ⊆ A⟨T/s⟩
completedPlusSubring      the integral closure of that               ⊆ A⟨T/s⟩
```

The integral closure is taken **in the completion**, which is what makes integral closedness of
`A_U⁺` hold by construction rather than by a transfer theorem.

Neither an intermediate integral closure inside `Aₛ` nor a topological closure of the image is
interposed. Either would enlarge the generating subring before the integral closure is taken, and
the result would agree with the roadmap's object only after an identification theorem this file
does not prove. What is defined here is the roadmap's sentence read literally: **one** integral
closure, in `A_U`, of the image of `A⁺[T/s]`.

## Main definitions

* `TauCeti.Huber.PairOfDefinition.completedPlusSubringBase`: the image of `A⁺[T/s]` in `A⟨T/s⟩`.
* `TauCeti.Huber.PairOfDefinition.completedPlusSubring`: **`A_U⁺`**.

## Main results

* `TauCeti.Huber.PairOfDefinition.toCompletionLoc_mem_completedPlusSubring` and
  `TauCeti.Huber.PairOfDefinition.divBy_mem_completedPlusSubring`: the image of `A⁺` and each
  fraction `t/s` lie in `A_U⁺`, which is what the roadmap's description of its generators asks.
* `TauCeti.Huber.PairOfDefinition.completedPlusSubring_le_powerBoundedSubring`: `A_U⁺ ⊆ (A_U)°`.

Of the three conditions making `(A_U, A_U⁺)` a Huber pair, two are here: integral closedness by
construction (`isIntegrallyClosedIn_completedPlusSubring`) and power-boundedness
(`completedPlusSubring_le_powerBoundedSubring`). **Openness is not proved here.** It reduces, by
`Subgroup.isOpen_of_openSubgroup` and the `isOpen_ringOfDefinition` field of the completed pair,
to containing that pair's ring of definition — and since that ring is a *closure* of an image
while `A_U⁺` carries no topological closure, the only route available here — `closure_le` — asks
for `A_U⁺` to be closed. That is sufficient rather than necessary: a direct argument for the
containment would do as well, and none is on hand.

## Provenance

AINTLIB (`github.com/CBirkbeck/AINTLIB`, Apache-2.0, branch `dev/adic-spaces` at `37bbdaeb9`)
carries a version of this construction in `projects/AdicSpaces/Adic spaces/Presheaf.lean` as
`RationalLocData.locPlusSubring`, `completedPlusSubringBase` and `completedPlusSubring`. The idea
of taking the final integral closure in the completion, so that integral closedness is free, is
theirs.

**This file deliberately differs from AINTLIB in two respects.** Their `completedPlusSubringBase`
is the *topological closure* of the image of `(A⁺[T/s])^int` — an integral closure taken already in
`Aₛ`, then closed. This one is the image of `A⁺[T/s]` itself, with neither extra layer. The roadmap
describes a single integral closure of that image, and each additional layer enlarges the
generating subring, so the objects agree only after an identification theorem that is not
available here. Their shape buys closedness of `A_U⁺`, which their power-boundedness argument then
uses; that cost is deferred rather than avoided, and is what the openness note above
records. No proof was copied and
nothing here is ported.

## References

* [Wedhorn, *Adic Spaces*][wedhorn_adic], §8.2, 8.16 and 7.47(4).
-/

public section

open Pointwise Topology TauCeti.Localization

namespace TauCeti.Huber

namespace PairOfDefinition

section Topological

variable {A : Type*} [CommRing A] [TopologicalSpace A] [IsTopologicalRing A]

/-- The base of `A_U⁺`: the image of `A⁺[T/s]` in `A⟨T/s⟩`. -/
noncomputable def completedPlusSubringBase (P : PairOfDefinition A) (Aplus : Subring A)
    (T : Finset A) (s : A) (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (hden : HasDenominatorPower P T s S) :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    Subring (UniformSpace.Completion S) :=
  letI := locUniformSpace P T s S hden
  letI := isUniformAddGroup_locUniformSpace P T s S hden
  letI := isTopologicalRing_locUniformSpace P T s S hden
  ((Algebra.adjoin Aplus (Set.range fun t : T ↦ (divBy (t : A) s : S))).toSubring).map
    UniformSpace.Completion.coeRingHom

/-- **`A_U⁺`**: the integral closure, inside `A⟨T/s⟩`, of `completedPlusSubringBase`.

Taking the integral closure *in the completion* is what makes integral closedness hold by
construction; defining `A_U⁺` instead as the closure of the image of `A⁺[T/s]^int` would leave that
owing Huber's Lemma 2.4.3, which identifies the two. -/
noncomputable def completedPlusSubring (P : PairOfDefinition A) (Aplus : Subring A)
    (T : Finset A) (s : A) (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (hden : HasDenominatorPower P T s S) :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    Subring (UniformSpace.Completion S) :=
  letI := locUniformSpace P T s S hden
  letI := isUniformAddGroup_locUniformSpace P T s S hden
  letI := isTopologicalRing_locUniformSpace P T s S hden
  -- the `Subring ↥R → Algebra ↥R B` route is not instance-automatic, so name it here
  letI : Algebra ↥(completedPlusSubringBase P Aplus T s S hden) (UniformSpace.Completion S) :=
    (completedPlusSubringBase P Aplus T s S hden).subtype.toAlgebra
  (integralClosure ↥(completedPlusSubringBase P Aplus T s S hden)
    (UniformSpace.Completion S)).toSubring

/-- The image of `A⁺` lands in `A_U⁺`. -/
theorem toCompletionLoc_mem_completedPlusSubring (P : PairOfDefinition A) (Aplus : Subring A)
    (T : Finset A) (s : A) (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (hden : HasDenominatorPower P T s S) {a : A} (ha : a ∈ Aplus) :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    toCompletionLoc P T s S hden a ∈ completedPlusSubring P Aplus T s S hden := by
  let _ := locUniformSpace P T s S hden
  have _ := isUniformAddGroup_locUniformSpace P T s S hden
  have _ := isTopologicalRing_locUniformSpace P T s S hden
  let _ : Algebra ↥(completedPlusSubringBase P Aplus T s S hden) (UniformSpace.Completion S) :=
    (completedPlusSubringBase P Aplus T s S hden).subtype.toAlgebra
  refine Subalgebra.algebraMap_mem (integralClosure _ _)
    (⟨toCompletionLoc P T s S hden a, ?_⟩ : ↥(completedPlusSubringBase P Aplus T s S hden))
  refine ⟨algebraMap A S a, Subalgebra.algebraMap_mem _ (⟨a, ha⟩ : ↥Aplus), ?_⟩
  simp [toCompletionLoc_apply, UniformSpace.Completion.coeRingHom]

/-- Each fraction `t/s` lands in `A_U⁺`. -/
theorem divBy_mem_completedPlusSubring (P : PairOfDefinition A) (Aplus : Subring A)
    (T : Finset A) (s : A) (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (hden : HasDenominatorPower P T s S) {t : A} (ht : t ∈ T) :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    ((divBy t s : S) : UniformSpace.Completion S) ∈ completedPlusSubring P Aplus T s S hden := by
  let _ := locUniformSpace P T s S hden
  have _ := isUniformAddGroup_locUniformSpace P T s S hden
  have _ := isTopologicalRing_locUniformSpace P T s S hden
  let _ : Algebra ↥(completedPlusSubringBase P Aplus T s S hden) (UniformSpace.Completion S) :=
    (completedPlusSubringBase P Aplus T s S hden).subtype.toAlgebra
  refine Subalgebra.algebraMap_mem (integralClosure _ _)
    (⟨((divBy t s : S) : UniformSpace.Completion S), ?_⟩ :
      ↥(completedPlusSubringBase P Aplus T s S hden))
  refine ⟨divBy t s, Algebra.subset_adjoin ⟨⟨t, ht⟩, rfl⟩, ?_⟩
  simp [UniformSpace.Completion.coeRingHom]

/-- **Membership in the base**, as the file's characteristic lemma: the body is not exposed, so
this is how a consumer reaches `A⁺[T/s]` underneath the image. -/
@[simp]
theorem mem_completedPlusSubringBase_iff (P : PairOfDefinition A) (Aplus : Subring A)
    (T : Finset A) (s : A) (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (hden : HasDenominatorPower P T s S) :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    ∀ {x : UniformSpace.Completion S},
      x ∈ completedPlusSubringBase P Aplus T s S hden ↔
        ∃ y ∈ Algebra.adjoin Aplus (Set.range fun t : T ↦ (divBy (t : A) s : S)),
          UniformSpace.Completion.coeRingHom y = x := by
  let _ := locUniformSpace P T s S hden
  have _ := isUniformAddGroup_locUniformSpace P T s S hden
  have _ := isTopologicalRing_locUniformSpace P T s S hden
  intro x
  rw [completedPlusSubringBase, Subring.mem_map]
  simp only [Subalgebra.mem_toSubring]

/-- **Membership in `A_U⁺`**: it is exactly integrality over the base. -/
@[simp]
theorem mem_completedPlusSubring_iff (P : PairOfDefinition A) (Aplus : Subring A)
    (T : Finset A) (s : A) (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (hden : HasDenominatorPower P T s S) :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    letI : Algebra ↥(completedPlusSubringBase P Aplus T s S hden) (UniformSpace.Completion S) :=
      (completedPlusSubringBase P Aplus T s S hden).subtype.toAlgebra
    ∀ {x : UniformSpace.Completion S},
      x ∈ completedPlusSubring P Aplus T s S hden ↔
        IsIntegral ↥(completedPlusSubringBase P Aplus T s S hden) x := by
  let _ := locUniformSpace P T s S hden
  have _ := isUniformAddGroup_locUniformSpace P T s S hden
  have _ := isTopologicalRing_locUniformSpace P T s S hden
  let _ : Algebra ↥(completedPlusSubringBase P Aplus T s S hden) (UniformSpace.Completion S) :=
    (completedPlusSubringBase P Aplus T s S hden).subtype.toAlgebra
  intro x
  rw [completedPlusSubring, Subalgebra.mem_toSubring, mem_integralClosure_iff]

/-- **`A_U⁺` is integrally closed in `A_U`**, which is the point of taking the integral closure in
the completion rather than in `Aₛ`: the property holds by construction, with no transfer theorem.
-/
instance isIntegrallyClosedIn_completedPlusSubring (P : PairOfDefinition A) (Aplus : Subring A)
    (T : Finset A) (s : A) (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (hden : HasDenominatorPower P T s S) :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    letI : Algebra ↥(completedPlusSubringBase P Aplus T s S hden) (UniformSpace.Completion S) :=
      (completedPlusSubringBase P Aplus T s S hden).subtype.toAlgebra
    IsIntegrallyClosedIn ↥(completedPlusSubring P Aplus T s S hden)
      (UniformSpace.Completion S) := by
  let _ := locUniformSpace P T s S hden
  have _ := isUniformAddGroup_locUniformSpace P T s S hden
  have _ := isTopologicalRing_locUniformSpace P T s S hden
  let _ : Algebra ↥(completedPlusSubringBase P Aplus T s S hden) (UniformSpace.Completion S) :=
    (completedPlusSubringBase P Aplus T s S hden).subtype.toAlgebra
  rw [completedPlusSubring]
  infer_instance

/-- **The universal property of `A_U⁺`**: it is the *smallest* integrally closed subring of `A_U`
containing the base. Containment in an integrally closed `R` is decided by the base alone, so a
minimality or uniqueness argument never has to unfold the integral closure.

This is `Subring.integralClosure_subring_le_iff` transported across the definition; the body of
`completedPlusSubring` is not exposed, so this is the elimination principle a consumer has. -/
theorem completedPlusSubring_le_iff (P : PairOfDefinition A) (Aplus : Subring A)
    (T : Finset A) (s : A) (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (hden : HasDenominatorPower P T s S) :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    letI : Algebra ↥(completedPlusSubringBase P Aplus T s S hden) (UniformSpace.Completion S) :=
      (completedPlusSubringBase P Aplus T s S hden).subtype.toAlgebra
    ∀ {R : Subring (UniformSpace.Completion S)}
      [IsIntegrallyClosedIn ↥R (UniformSpace.Completion S)],
      completedPlusSubring P Aplus T s S hden ≤ R ↔
        completedPlusSubringBase P Aplus T s S hden ≤ R := by
  let _ := locUniformSpace P T s S hden
  have _ := isUniformAddGroup_locUniformSpace P T s S hden
  have _ := isTopologicalRing_locUniformSpace P T s S hden
  let _ : Algebra ↥(completedPlusSubringBase P Aplus T s S hden) (UniformSpace.Completion S) :=
    (completedPlusSubringBase P Aplus T s S hden).subtype.toAlgebra
  intro R _
  rw [completedPlusSubring]
  exact Subring.integralClosure_subring_le_iff

/-- **`A_U⁺` is power-bounded**: it lies inside `(A_U)°`, which is the second of the three
conditions making `(A_U, A_U⁺)` a Huber pair.

Containment in `(A_U)°` is decided by the base alone, because `A°` is integrally closed
(`isIntegrallyClosedIn_powerBoundedSubring`) — that is `completedPlusSubring_le_iff`. The base is
generated by the image of `A⁺` and the fractions `t/s`, and both families are power-bounded: the
first because power-boundedness of each element of `A⁺` transfers along `A → Aₛ → A⟨T/s⟩`, the
second because every element of `D` is power-bounded in `Aₛ`. `(A_U)°` is a subring, so the
generated subring stays inside it. -/
theorem completedPlusSubring_le_powerBoundedSubring (P : PairOfDefinition A) (Aplus : Subring A)
    (hAplus : ∀ ⦃a⦄, a ∈ Aplus → IsPowerBounded a)
    (T : Finset A) (s : A) (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (hden : HasDenominatorPower P T s S) :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    letI := isHuberRing_completion_locTopology P T s S hden
    completedPlusSubring P Aplus T s S hden
      ≤ powerBoundedSubring (UniformSpace.Completion S) := by
  let _ := locUniformSpace P T s S hden
  have _ := isUniformAddGroup_locUniformSpace P T s S hden
  have _ := isTopologicalRing_locUniformSpace P T s S hden
  let _ := isHuberRing_locUniformSpace P T s S hden
  let _ := isHuberRing_completion_locTopology P T s S hden
  let _ : Algebra ↥(completedPlusSubringBase P Aplus T s S hden) (UniformSpace.Completion S) :=
    (completedPlusSubringBase P Aplus T s S hden).subtype.toAlgebra
  rw [completedPlusSubring_le_iff]
  intro x hx
  obtain ⟨y, hy, rfl⟩ := (mem_completedPlusSubringBase_iff P Aplus T s S hden).mp hx
  -- `y` is a polynomial in the `t/s` with coefficients in `A⁺`, so it is power-bounded in `Aₛ`;
  -- power-boundedness then transfers across the completion.
  have hyS : IsPowerBounded y := by
    have hle : (Algebra.adjoin ↥Aplus (Set.range fun t : T ↦ (divBy (t : A) s : S))).toSubring
        ≤ powerBoundedSubring S := by
      rw [Algebra.adjoin_eq_ring_closure, Subring.closure_le]
      rintro w (⟨⟨a, ha⟩, rfl⟩ | ⟨⟨t, ht⟩, rfl⟩)
      · exact mem_powerBoundedSubring.mpr
          (isPowerBounded_algebraMap_of_isPowerBounded_locUniformSpace P T s S hden
            (hAplus ha))
      · exact mem_powerBoundedSubring.mpr (isPowerBounded_divBy_locUniformSpace P T s S hden ht)
    exact mem_powerBoundedSubring.mp (hle hy)
  exact mem_powerBoundedSubring.mpr (isPowerBounded_completion_coe_of_isPowerBounded hyS)

end Topological

end PairOfDefinition

end TauCeti.Huber
