/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.AlgebraicTopology.SimplicialComplex.Basic
public import TauCeti.AlgebraicTopology.SimplicialComplex.IsCone

/-!
# The closed star, link, and deletion of a simplex

For an abstract simplicial complex `K` and a simplex `σ`, this file builds the three local
subcomplexes that organise `K` around `σ`:

* the **closed star** `closedStar K σ`, the faces `ρ` whose union with `σ` is still a face of `K`
  (equivalently, the smallest subcomplex containing every face of `K` that contains `σ`);
* the **link** `link K σ`, the part of the closed star disjoint from `σ`;
* the **deletion** `deletion K σ` (the *anti-star*), the faces of `K` that do not contain `σ`.

These are the "basic API (faces, the star and link of a simplex)" that the geometric-topology
roadmap (`TauCetiRoadmap/GeometricTopology/README.md`, layer 11) asks for on top of Mathlib's
`AbstractSimplicialComplex`. The link is the load-bearing one downstream: a combinatorial
`n`-manifold is defined there by the condition that the link of every vertex is a combinatorial
`(n-1)`-sphere or `(n-1)`-ball, so `link` is the primitive that condition is phrased against. The
definitions follow Rourke--Sanderson, *Introduction to Piecewise-Linear Topology*, Chapter 3, and
they work for `PreAbstractSimplicialComplex` (the singleton-free version), since the link of a
simplex need not contain every vertex even when `K` does.

## Main definitions

* `PreAbstractSimplicialComplex.closedStar K σ`: the closed star of `σ` in `K`.
* `PreAbstractSimplicialComplex.link K σ`: the link of `σ` in `K`.
* `PreAbstractSimplicialComplex.deletion K σ`: the deletion (anti-star) of `σ` in `K`.

## Main results

* `PreAbstractSimplicialComplex.closedStar_le` / `link_le` / `deletion_le`: each is a
  subcomplex of `K`, and `link_le_closedStar` places the link inside the closed star.
* `PreAbstractSimplicialComplex.mem_closedStar` / `mem_link`: membership in the
  closed star or link, phrased as membership in `K` plus the local condition.
* `PreAbstractSimplicialComplex.mem_closedStar_nonempty` / `mem_link_nonempty`: the
  introduction-friendly membership forms using only nonemptiness and the defining local data.
* `PreAbstractSimplicialComplex.closedStar_sup_deletion`: the closed star and the deletion
  cover `K`, i.e. `closedStar K σ ⊔ deletion K σ = K`.
* `PreAbstractSimplicialComplex.link_le_deletion_of_nonempty`: for a nonempty `σ`, the
  link sits inside the deletion.
* `PreAbstractSimplicialComplex.closedStar_empty` / `link_empty` / `deletion_empty`: the
  values at the empty simplex (`K`, `K`, and `⊥`), pinning the conventions.
* `PreAbstractSimplicialComplex.isCone_closedStar` / `isCone_deletion`: the closed star of
  a face is a cone with apex any vertex of that face, and deleting a face missing the apex of a
  cone leaves a cone with the same apex.
* monotonicity of all three constructions in `K`.
-/

public section

open Finset

namespace PreAbstractSimplicialComplex

variable {ι : Type*} [DecidableEq ι] (K L : PreAbstractSimplicialComplex ι) (σ : Finset ι)

/-- The **closed star** of a simplex `σ` in `K`: the faces `ρ` whose union with `σ` is a face of
`K`. Equivalently, this is the subcomplex of `K` generated by faces whose union with `σ` remains
in `K`. -/
def closedStar : PreAbstractSimplicialComplex ι where
  faces := {ρ | ρ.Nonempty ∧ ρ ∪ σ ∈ K}
  isRelLowerSet_faces := by
    rintro a ⟨hane, haK⟩
    refine ⟨hane, fun {b} hba hbne => ⟨hbne, ?_⟩⟩
    exact (K.isRelLowerSet_faces haK).2 (union_subset_union hba Subset.rfl)
      (hbne.mono subset_union_left)

/-- The **link** of a simplex `σ` in `K`: the part of the closed star disjoint from `σ`, i.e. the
faces `ρ` disjoint from `σ` with `ρ ∪ σ` a face of `K`. This is the primitive the combinatorial
`n`-manifold condition is phrased against: the link of every vertex should be a combinatorial
sphere or ball. -/
def link : PreAbstractSimplicialComplex ι where
  faces := {ρ | ρ.Nonempty ∧ Disjoint ρ σ ∧ ρ ∪ σ ∈ K}
  isRelLowerSet_faces := by
    rintro a ⟨hane, hdis, haK⟩
    refine ⟨hane, fun {b} hba hbne => ⟨hbne, hdis.mono_left hba, ?_⟩⟩
    exact (K.isRelLowerSet_faces haK).2 (union_subset_union hba Subset.rfl)
      (hbne.mono subset_union_left)

/-- The **deletion** (or *anti-star*) of a simplex `σ` in `K`: the faces of `K` that do not contain
`σ` as a subset. Together with the closed star it covers `K` (`closedStar_sup_deletion`). -/
def deletion : PreAbstractSimplicialComplex ι where
  faces := {ρ | ρ ∈ K ∧ ¬ σ ⊆ ρ}
  isRelLowerSet_faces := by
    rintro a ⟨haK, haσ⟩
    refine ⟨(K.isRelLowerSet_faces haK).1, fun {b} hba hbne => ⟨?_, ?_⟩⟩
    · exact (K.isRelLowerSet_faces haK).2 hba hbne
    · exact fun h => haσ (h.trans hba)

variable {K L σ}

/-- A nonempty finset belongs to the closed star exactly when adjoining `σ` gives a face of
`K`. This is the introduction-friendly form of closed-star membership. -/
theorem mem_closedStar_nonempty {ρ : Finset ι} :
    ρ ∈ closedStar K σ ↔ ρ.Nonempty ∧ ρ ∪ σ ∈ K :=
  Iff.rfl

/-- A nonempty finset belongs to the link exactly when it is disjoint from `σ` and adjoining
`σ` gives a face of `K`. This is the introduction-friendly form of link membership. -/
theorem mem_link_nonempty {ρ : Finset ι} :
    ρ ∈ link K σ ↔ ρ.Nonempty ∧ Disjoint ρ σ ∧ ρ ∪ σ ∈ K :=
  Iff.rfl

omit [DecidableEq ι] in
@[simp]
theorem mem_deletion {ρ : Finset ι} : ρ ∈ deletion K σ ↔ ρ ∈ K ∧ ¬ σ ⊆ ρ := Iff.rfl

/-- A finset `ρ` belongs to the closed star exactly when `ρ` is a face of `K` and adjoining `σ`
still gives a face of `K`. -/
@[simp]
theorem mem_closedStar {ρ : Finset ι} :
    ρ ∈ closedStar K σ ↔ ρ ∈ K ∧ ρ ∪ σ ∈ K := by
  rw [mem_closedStar_nonempty]
  refine ⟨fun hρ => ⟨?_, hρ.2⟩, fun hρ => ⟨?_, hρ.2⟩⟩
  · exact (K.isRelLowerSet_faces hρ.2).2 subset_union_left hρ.1
  · exact (K.isRelLowerSet_faces hρ.1).1

/-- A finset `ρ` belongs to the link exactly when `ρ` is a face of `K`, is disjoint from `σ`, and
adjoining `σ` still gives a face of `K`. -/
@[simp]
theorem mem_link {ρ : Finset ι} :
    ρ ∈ link K σ ↔ ρ ∈ K ∧ Disjoint ρ σ ∧ ρ ∪ σ ∈ K := by
  rw [mem_link_nonempty]
  refine ⟨fun hρ => ⟨?_, hρ.2.1, hρ.2.2⟩, fun hρ => ⟨?_, hρ.2⟩⟩
  · exact (K.isRelLowerSet_faces hρ.2.2).2 subset_union_left hρ.1
  · exact (K.isRelLowerSet_faces hρ.1).1

/-- The closed star of `σ` is a subcomplex of `K`. -/
theorem closedStar_le : closedStar K σ ≤ K := by
  rintro ρ (hρ : ρ ∈ closedStar K σ)
  obtain ⟨hne, hρ⟩ := mem_closedStar_nonempty.mp hρ
  exact (K.isRelLowerSet_faces hρ).2 subset_union_left hne

/-- The link of `σ` is a subcomplex of its closed star. -/
theorem link_le_closedStar : link K σ ≤ closedStar K σ :=
  fun _ hρ => by
    obtain ⟨hne, _, hρ⟩ := mem_link_nonempty.mp hρ
    exact mem_closedStar_nonempty.mpr ⟨hne, hρ⟩

/-- The link of `σ` is a subcomplex of `K`. -/
theorem link_le : link K σ ≤ K :=
  link_le_closedStar.trans closedStar_le

omit [DecidableEq ι] in
/-- The deletion of `σ` is a subcomplex of `K`. -/
theorem deletion_le : deletion K σ ≤ K :=
  fun _ hρ => (mem_deletion.mp hρ).1

/-- The closed star and the deletion of `σ` cover `K`: every face either survives in the deletion
(it does not contain `σ`) or lies in the closed star (it, hence its union with `σ`, is a face). -/
theorem closedStar_sup_deletion : closedStar K σ ⊔ deletion K σ = K := by
  refine le_antisymm (sup_le closedStar_le deletion_le) fun ρ hρ => ?_
  rcases em (σ ⊆ ρ) with h | h
  · exact Or.inl (mem_closedStar_nonempty.mpr
      ⟨(K.isRelLowerSet_faces hρ).1, by rwa [union_eq_left.mpr h]⟩)
  · exact Or.inr (mem_deletion.mpr ⟨hρ, h⟩)

/-- For a nonempty simplex `σ`, the link lies inside the deletion: a face disjoint from a nonempty
`σ` cannot contain it. -/
theorem link_le_deletion_of_nonempty (hσ : σ.Nonempty) : link K σ ≤ deletion K σ := by
  rintro ρ (hρ : ρ ∈ link K σ)
  obtain ⟨hne, hdis, hρ⟩ := mem_link_nonempty.mp hρ
  exact mem_deletion.mpr ⟨(K.isRelLowerSet_faces hρ).2 subset_union_left hne,
    fun hsub => hσ.ne_empty (disjoint_self_iff_empty σ |>.mp (hdis.mono_left hsub))⟩

/-- The closed star at the empty simplex is the whole complex. -/
@[simp]
theorem closedStar_empty : closedStar K ∅ = K := by
  refine SetLike.ext fun ρ => ?_
  simp only [mem_closedStar, union_empty, and_self]

/-- The link at the empty simplex is the whole complex. -/
@[simp]
theorem link_empty : link K ∅ = K := by
  refine SetLike.ext fun ρ => ?_
  simp only [mem_link, disjoint_empty_right, union_empty, true_and, and_self]

omit [DecidableEq ι] in
/-- The deletion at the empty simplex is empty: every face contains `∅`. -/
@[simp]
theorem deletion_empty : deletion K ∅ = ⊥ :=
  eq_bot_iff.mpr fun ρ hρ => (hρ.2 (empty_subset ρ)).elim

/-- The closed star is monotone in the complex. -/
theorem closedStar_mono (h : K ≤ L) : closedStar K σ ≤ closedStar L σ :=
  fun _ hρ => by
    obtain ⟨hρ, hρσ⟩ := mem_closedStar.mp hρ
    exact mem_closedStar.mpr ⟨h hρ, h hρσ⟩

/-- The link is monotone in the complex. -/
theorem link_mono (h : K ≤ L) : link K σ ≤ link L σ :=
  fun _ hρ => by
    obtain ⟨hρ, hdis, hρσ⟩ := mem_link.mp hρ
    exact mem_link.mpr ⟨h hρ, hdis, h hρσ⟩

omit [DecidableEq ι] in
/-- The deletion is monotone in the complex. -/
theorem deletion_mono (h : K ≤ L) : deletion K σ ≤ deletion L σ :=
  fun _ hρ => by
    obtain ⟨hρ, hσ⟩ := mem_deletion.mp hρ
    exact mem_deletion.mpr ⟨h hρ, hσ⟩

section IsCone

variable {v : ι}

/-- The closed star of a face is a cone with apex any vertex of that face: adjoining `v ∈ σ` to
a face `ρ` of the closed star leaves the defining union `ρ ∪ σ` unchanged. -/
theorem isCone_closedStar (hσ : σ ∈ K) (hv : v ∈ σ) : IsCone (closedStar K σ) v where
  apex_mem := mem_closedStar_nonempty.mpr ⟨Finset.singleton_nonempty v, by
    rwa [Finset.singleton_union, Finset.insert_eq_self.mpr hv]⟩
  insert_mem ρ hρ := mem_closedStar_nonempty.mpr ⟨Finset.insert_nonempty v ρ, by
      rw [Finset.insert_union, Finset.insert_eq_self.mpr (Finset.mem_union_right _ hv)]
      exact (mem_closedStar_nonempty.mp hρ).2⟩

/-- Deleting a nonempty face that misses the apex of a cone leaves a cone with the same apex.
Note that the deletion of a face *containing* the apex need not be a cone: deleting `{v}` itself
destroys the apex. -/
theorem isCone_deletion (h : IsCone K v) (hσ : σ.Nonempty) (hv : v ∉ σ) :
    IsCone (deletion K σ) v where
  apex_mem := by
    refine mem_deletion.mpr ⟨h.apex_mem, fun hsub => ?_⟩
    rcases Finset.subset_singleton_iff.mp hsub with rfl | rfl
    · exact hσ.ne_empty rfl
    · exact hv (Finset.mem_singleton_self v)
  insert_mem ω hω := by
    rw [mem_deletion] at hω ⊢
    exact ⟨h.insert_mem hω.1, fun hsub =>
      hω.2 ((Finset.subset_insert_iff_of_notMem hv).mp hsub)⟩

end IsCone

end PreAbstractSimplicialComplex
