/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.GroupTheory.Presentation.GroupPresentation

/-!
# A transcribed presentation of the Mathieu group `M₂₄`

This file carries the `M₂₄` row of the sporadic presentation data required by milestone S1 of
`TauCetiRoadmap/CFSGStatement/README.md`. It records the ATLAS version 3 presentation `M24G1-P1` of
the Mathieu group `M₂₄` on its standard generators `a` and `b` as a `TauCeti.GroupPresentation`,
together with the source, the generator convention, transcription notes, and the expected counts.

Writing `s₁ = ab` and `s₋₁ = ab⁻¹` for the two syllables that occur, the seven transcribed relators
are

```text
a², b³, s₁²³, [a,b]¹², [a,bab]⁵, (s₁s₁s₋₁)³(s₁s₋₁s₋₁)³, (s₁(s₁s₋₁)³)⁴.
```

The Magma source file carries an eighth word `[a, b⁻¹abab]⁵`, but comments it out of the
`Group<x, y | ...>` constructor with the note "redundant, but quite useful.", so it lies outside
the relator list and is not transcribed; the recorded relator count is therefore seven, and the
presentation page displays the same seven words. Contrast the redundant word of `M23G1-P1`,
transcribed in `TauCeti.GroupTheory.SpecificGroups.CFSG.Sporadic.Mathieu.TwentyThree`, which stands
inside its relator list as written and is counted.

The source's commutator convention is `[r,s] = r⁻¹s⁻¹rs`, opposite to Mathlib's
`commutatorElement`, so each commutator is stored as `Relator.comm (.inv r) (.inv s)` as
`TauCeti.Relator` prescribes. The proved `TauCeti.Relator.toWord_toFreeGroup` is the audit boundary
between these expressions and the signed words that `PresentedGroup` consumes.

The source is a presentation rather than a semi-presentation — the ATLAS lists a separate
semi-presentation for `M₂₄`, which is not what is transcribed here — and it comes with a
demonstration of correctness: `a² = b³ = (ab)²³ = 1` force the presented group to be perfect and
hence generated by conjugates of `a`, the remaining relations force the source's subgroup `H` to
centralize `a`, a coset enumeration returns the index `31878` of that subgroup, which is the index
of the involution centralizer `2¹⁺⁶:L₃(2)` of a class `2B` involution in `M₂₄`, and `M₂₄` has
trivial Schur multiplier. GAP 4.15.1 independently checks the transcription in both directions. The
seven words compiled by `Relator.toWord` from the expressions below vanish on five independent
standard generating pairs of the natural 24-point representation of `M₂₄`, so the presented group
surjects onto `M₂₄`; enumerating the compiled relators over the image of the source's subgroup `H`
returns the index `31878` that the source predicts; and enumerating them over the cyclic subgroup
generated by the image of `ab` returns the index `10644480`, which with `s₁²³` bounding that
subgroup by `23` pins the order of the presented group at `244823040 = |M₂₄|`. The two classes must
be pinned by
centralizer order, `7680` for `a` and `1080` for `b`, and not by element orders alone: pairs with
`a` of order `2`, `b` of order `3`, `ab` of order `23` and `ababab²abab²ab²` of order `4` also occur
with `a` in class `2A` and `b` in class `3B`, and on those the last three relators do not vanish.
Both computations are provenance for the
transcription, not Lean theorems: this file asserts no order, finiteness, simplicity, or
identification result. The cross-check against the `M24` of the
[FiniteSimpleGroups](https://github.com/KitaKen1/finite-simple-groups-lean) development, which
`TauCetiRoadmap/CFSGStatement/README.md` asks for on the names that development covers, is still
owed on this row.

## Main definition

* `TauCeti.Sporadic.m24Presentation`: the ATLAS finite presentation of `M₂₄`.

## References

* R. A. Wilson, R. A. Parker, J. N. Bray et al., *ATLAS of Finite Group Representations*,
  version 3, presentation `M24G1-P1`,
  <https://brauer.maths.qmul.ac.uk/Atlas/v3/pres/M24G1-P1>, with the relator list and the
  demonstration of correctness in the Magma source file
  <https://brauer.maths.qmul.ac.uk/Atlas/spor/M24/mag/M24G1-P1.M>.
-/

public section

namespace TauCeti.Sporadic

private abbrev a : Relator (Fin 2) := .gen 0

private abbrev b : Relator (Fin 2) := .gen 1

@[inherit_doc Relator.mul]
local infixl:70 " ⬝ " => Relator.mul

/-- The source's commutator `[r, s] = r⁻¹ s⁻¹ r s`, which is `⁅r⁻¹, s⁻¹⁆` in Mathlib's
convention. -/
private abbrev sourceComm (r s : Relator (Fin 2)) : Relator (Fin 2) := .comm (.inv r) (.inv s)

/-- The syllable `a * b`. -/
private abbrev ab1 : Relator (Fin 2) := a ⬝ b

/-- The syllable `a * b⁻¹`. -/
private abbrev abNeg1 : Relator (Fin 2) := a ⬝ .inv b

/-- The ATLAS version 3 finite presentation `M24G1-P1` of the Mathieu group `M₂₄` on its standard
generators `a` and `b`.

The ATLAS lists this as a full presentation of the abstract group, separately from the
semi-presentation used to recognize standard generators inside a group already constructed. No
structural property of the presented group is asserted here: this definition records only the
cited generators and relations. -/
def m24Presentation : GroupPresentation where
  generatorNames := ["a", "b"]
  source := "R. A. Wilson, R. A. Parker, J. N. Bray et al., ATLAS of Finite Group \
    Representations, version 3"
  sourceLocator := "M24G1-P1, https://brauer.maths.qmul.ac.uk/Atlas/v3/pres/M24G1-P1, with the \
    relator list and the demonstration of correctness in the Magma source file \
    https://brauer.maths.qmul.ac.uk/Atlas/spor/M24/mag/M24G1-P1.M"
  generatorConvention := "The ATLAS standard generators a and b of M24, that is, a in class 2B \
    and b in class 3A with ab of order 23 and ababab^2abab^2ab^2 of order 4, in that order, so \
    index 0 is a and index 1 is b. Products are read left to right, negative exponents denote \
    inverses, and [r,s] denotes r^-1 s^-1 r s."
  transcriptionNotes := "The seven words of the source's relator list are stored as seven relators \
    equal to the identity. The Magma file's eighth word [a, b^-1*a*b*a*b]^5 is commented out of \
    the Group<x, y | ...> constructor with the note 'redundant, but quite useful.', so it lies \
    outside the relator list and is not transcribed. GAP 4.15.1 checks that the seven \
    compiled words vanish on five independent standard generating pairs of the natural 24-point \
    representation of M24, taking a with centralizer of order 7680 and b with centralizer of order \
    1080; that enumerating the compiled relators over the image of the source's subgroup H returns \
    the index 31878 that the source's demonstration of correctness predicts; and that enumerating \
    them over the cyclic subgroup generated by the image of ab returns the index 10644480, hence \
    the order 23 * 10644480 = 244823040 of M24."
  expectedGeneratorCount := 2
  expectedRelatorCount := 7
  transcribed :=
    [ .pow a 2,
      .pow b 3,
      .pow ab1 23,
      .pow (sourceComm a b) 12,
      .pow (sourceComm a (b ⬝ a ⬝ b)) 5,
      .pow (ab1 ⬝ ab1 ⬝ abNeg1) 3 ⬝ .pow (ab1 ⬝ abNeg1 ⬝ abNeg1) 3,
      .pow (ab1 ⬝ .pow (ab1 ⬝ abNeg1) 3) 4 ]

/-- The generator and relator counts recorded for `M₂₄` agree with the transcribed data. -/
theorem matchesMetadata_m24Presentation : m24Presentation.matchesMetadata := by decide

end TauCeti.Sporadic
