/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.GroupTheory.Presentation.GroupPresentation

/-!
# A transcribed presentation of the Mathieu group `M₂₃`

This file carries the `M₂₃` row of the sporadic presentation data required by milestone S1 of
`TauCetiRoadmap/CFSGStatement/README.md`. It records the ATLAS version 3 presentation `M23G1-P1` of
the Mathieu group `M₂₃` on its standard generators `a` and `b` as a `TauCeti.GroupPresentation`,
together with the source, the generator convention, transcription notes, and the expected counts.

Writing `s₁ = ab`, `s₂ = ab²` and `s₋₁ = ab⁻¹` for the three syllables that occur, the nine
transcribed relators are

```text
a², b⁴, s₁²³, s₂⁶, [a,b]⁶, (s₁s₋₁s₂)⁴,
s₁³ s₋₁ s₂ (s₁s₋₁)² s₁³ s₋₁³,
(s₁s₂s₂)⁶,
(s₁s₂)³ (s₂s₋₁)² s₁ s₂ s₁ s₋₁ s₂.
```

The eighth of these, `(abab²ab²)⁶`, is annotated "Is redundant, but very useful." in the source, and
the source's header records the two resulting counts as "NoRels: 8 [or 9]" with lengths 190 and 238.
Unlike the redundant words of the neighbouring ATLAS files — `M24G1-P1`, transcribed in
`TauCeti.GroupTheory.SpecificGroups.CFSG.Sporadic.Mathieu.TwentyFour`, comments its redundant word
out of the Magma `Group<x, y | ...>` constructor — this word stands inside the relator list as
written, so it is transcribed and the recorded relator count is nine. The source's demonstration of
correctness covers the list both with and without it.

The source's commutator convention is `[r,s] = r⁻¹s⁻¹rs`, opposite to Mathlib's
`commutatorElement`, so the commutator is stored as `Relator.comm (.inv r) (.inv s)` as
`TauCeti.Relator` prescribes. The proved `TauCeti.Relator.toWord_toFreeGroup` is the audit boundary
between these expressions and the signed words that `PresentedGroup` consumes.

The source is a presentation rather than a semi-presentation — the ATLAS lists a separate
semi-presentation for `M₂₃`, which is not what is transcribed here — and it comes with a
demonstration of correctness: the relations force the presented group to be perfect and hence
generated by conjugates of `a`, a coset enumeration returns the index `3795` of a subgroup that
visibly centralizes `a`, which is the index of the involution centralizer `2⁴:L₃(2)` in `M₂₃`, and
`M₂₃` has trivial Schur multiplier. GAP 4.15.1 independently checks the transcription in both
directions. The nine words compiled by `Relator.toWord` from the expressions below vanish on five
independent standard generating pairs of the natural 23-point representation of `M₂₃`, so the
presented group surjects onto `M₂₃`; and enumerating the compiled relators over the cyclic subgroup
generated by the image of `ab` returns the index `443520`, which with `s₁²³` bounding that subgroup
by `23` pins the order of the presented group at `10200960 = |M₂₃|`. Both computations are
provenance for the transcription, not Lean theorems: this file asserts no order, finiteness,
simplicity, or identification result. The cross-check against the `M23` of the
[FiniteSimpleGroups](https://github.com/KitaKen1/finite-simple-groups-lean) development, which
`TauCetiRoadmap/CFSGStatement/README.md` asks for on the names that development covers, is still
owed on this row.

## Main definition

* `TauCeti.Sporadic.m23Presentation`: the ATLAS finite presentation of `M₂₃`.

## References

* R. A. Wilson, R. A. Parker, J. N. Bray et al., *ATLAS of Finite Group Representations*,
  version 3, presentation `M23G1-P1`,
  <https://brauer.maths.qmul.ac.uk/Atlas/v3/pres/M23G1-P1>, with the relator list and the
  demonstration of correctness in the Magma source file
  <https://brauer.maths.qmul.ac.uk/Atlas/spor/M23/mag/M23G1-P1.M>.
-/

public section

namespace TauCeti.Sporadic

private abbrev a : Relator (Fin 2) := .gen 0

private abbrev b : Relator (Fin 2) := .gen 1

@[inherit_doc Relator.mul]
local infixl:70 " ⬝ " => Relator.mul

/-- The source's commutator `[r, s] = r⁻¹ s⁻¹ r s`, which is `⁅r⁻¹, s⁻¹⁆` in Mathlib's
convention. -/
private abbrev sourceComm (r s : Relator (Fin 2)) : Relator (Fin 2) := .comm (.inv r) (.inv s)

/-- The syllable `a * b`. -/
private abbrev ab1 : Relator (Fin 2) := a ⬝ b

/-- The syllable `a * b ^ 2`. -/
private abbrev ab2 : Relator (Fin 2) := a ⬝ .pow b 2

/-- The syllable `a * b⁻¹`. -/
private abbrev abNeg1 : Relator (Fin 2) := a ⬝ .inv b

/-- The ATLAS version 3 finite presentation `M23G1-P1` of the Mathieu group `M₂₃` on its standard
generators `a` and `b`.

The ATLAS lists this as a full presentation of the abstract group, separately from the
semi-presentation used to recognize standard generators inside a group already constructed. No
structural property of the presented group is asserted here: this definition records only the
cited generators and relations. -/
def m23Presentation : GroupPresentation where
  generatorNames := ["a", "b"]
  source := "R. A. Wilson, R. A. Parker, J. N. Bray et al., ATLAS of Finite Group \
    Representations, version 3"
  sourceLocator := "M23G1-P1, https://brauer.maths.qmul.ac.uk/Atlas/v3/pres/M23G1-P1, with the \
    relator list and the demonstration of correctness in the Magma source file \
    https://brauer.maths.qmul.ac.uk/Atlas/spor/M23/mag/M23G1-P1.M"
  generatorConvention := "The ATLAS standard generators a and b of M23, that is, a of order 2 and \
    b of order 4 with ab of order 23 and abababab^2abab^2ab^2 of order 8, in that order, so index \
    0 is a and index 1 is b. Products are read left to right, negative exponents denote inverses, \
    and [r,s] denotes r^-1 s^-1 r s."
  transcriptionNotes := "The nine words of the source's Magma relator list are stored as nine \
    relators equal to the identity. The eighth, (ab*ab^2*ab^2)^6, carries the source's annotation \
    'Is redundant, but very useful.' but stands inside the relator list as written rather than \
    being commented out of it, so it is transcribed; the source's header records the two counts as \
    'NoRels: 8 [or 9]', of total length 190 and 238, and demonstrates correctness for the list \
    both with and without that word. GAP 4.15.1 checks that the nine compiled words vanish on five \
    independent standard generating pairs of the natural 23-point representation of M23, and that \
    enumerating the compiled relators over the cyclic subgroup generated by the image of ab \
    returns the index 443520, hence the order 23 * 443520 = 10200960 of M23."
  expectedGeneratorCount := 2
  expectedRelatorCount := 9
  transcribed :=
    [ .pow a 2,
      .pow b 4,
      .pow ab1 23,
      .pow ab2 6,
      .pow (sourceComm a b) 6,
      .pow (ab1 ⬝ abNeg1 ⬝ ab2) 4,
      .pow ab1 3 ⬝ abNeg1 ⬝ ab2 ⬝ .pow (ab1 ⬝ abNeg1) 2 ⬝ .pow ab1 3 ⬝ .pow abNeg1 3,
      .pow (ab1 ⬝ ab2 ⬝ ab2) 6,
      .pow (ab1 ⬝ ab2) 3 ⬝ .pow (ab2 ⬝ abNeg1) 2 ⬝ ab1 ⬝ ab2 ⬝ ab1 ⬝ abNeg1 ⬝ ab2 ]

/-- The generator and relator counts recorded for `M₂₃` agree with the transcribed data. -/
theorem matchesMetadata_m23Presentation : m23Presentation.matchesMetadata := by decide

end TauCeti.Sporadic
