/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Data.Set.Card
public import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic

/-!
# Counting simple intermediate fields generated by a finite set

Given a finite set `T` of elements of a field extension `L / K`, the simple intermediate fields
`K⟮x⟯` generated by elements of `T` form a finite set, and there are at most `T.ncard` of them.
This is the reusable finite-generator-to-simple-field counting step, used before specializing to
particular finite generating sets such as bounded-polynomial root sets.

## Main results

* `TauCeti.IntermediateField.finite_setOf_exists_mem_eq_adjoin_simple_of_finite`:
  if `T` is finite, the simple intermediate fields generated by elements of `T` form a
  finite set.
* `TauCeti.IntermediateField.ncard_setOf_exists_mem_eq_adjoin_simple_le`:
  the number of simple intermediate fields generated by elements of a finite set `T` is
  at most `T.ncard`.
-/

public section

open scoped IntermediateField

namespace TauCeti.IntermediateField

variable {K L : Type*} [Field K] [Field L] [Algebra K L]

/-- The simple intermediate fields generated by elements of a finite set `T` form a finite set.

This is the reusable finite-generator-to-simple-field counting step used before specializing to
particular finite generating sets. -/
theorem finite_setOf_exists_mem_eq_adjoin_simple_of_finite {T : Set L} (hT : T.Finite) :
    {E : IntermediateField K L | ∃ x ∈ T, E = K⟮x⟯}.Finite :=
  (hT.image (fun x => (K⟮x⟯ : IntermediateField K L))).subset
    (fun E hE => by
      obtain ⟨x, hx, rfl⟩ := hE
      exact ⟨x, hx, rfl⟩)

/-- The simple intermediate fields generated by elements of a finite set `T` are no more numerous
than the elements of `T`. -/
theorem ncard_setOf_exists_mem_eq_adjoin_simple_le {T : Set L} (hT : T.Finite) :
    {E : IntermediateField K L | ∃ x ∈ T, E = K⟮x⟯}.ncard ≤ T.ncard := by
  have hsub :
      {E : IntermediateField K L | ∃ x ∈ T, E = K⟮x⟯} ⊆
        (fun x => (K⟮x⟯ : IntermediateField K L)) '' T := by
    intro E hE
    obtain ⟨x, hx, rfl⟩ := hE
    exact ⟨x, hx, rfl⟩
  exact (Set.ncard_le_ncard hsub (hT.image _)).trans (Set.ncard_image_le hT)

end TauCeti.IntermediateField
