/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.LinearAlgebra.Basis.Submodule
public import TauCeti.Algebra.Module.Rat
public import TauCeti.Algebra.Polynomial.Sequence
public import TauCeti.RingTheory.Binomial
public import TauCeti.RingTheory.Polynomial.Pochhammer

import Mathlib.Algebra.CharP.Algebra
import Mathlib.Algebra.Regular.SMul
import Mathlib.Data.Nat.Factorial.NatCast

/-!
# The binomial polynomials as a basis

The polynomials

```text
  (X choose n) = X (X - 1) ... (X - n + 1) / n!
```

form a basis of `K[X]` for any nontrivial `ℚ`-algebra `K`. This file packages them as a
`Polynomial.Sequence`. The sequence supplies the spanning half of the basis (`span`,
`span_degreeLT`, `span_degreeLE`), while linear independence is proved via
`Polynomial.Sequence.linearIndependent_of_isRightRegular_leadingCoeff`, extending Mathlib's
domain-only `Polynomial.Sequence.linearIndependent`.

We also obtain the integral form of the statement: restricting scalars to `ℤ`, the additive
subgroup generated by the `(X choose n)` is free on exactly those generators. We obtain its
integral basis from `Module.Basis.addSubgroupOfClosure`. Consequently every element of this subgroup
has a unique finite integral expansion in the binomial polynomials.

The identity relating `(X choose n)` to the descending Pochhammer polynomial supplies the degree
and leading-coefficient calculations. The integral span itself is the specialization of
`TauCeti.ringChooseSpan` at `X`.

## Main declarations

* `TauCeti.binomialPolynomialSequence`: the sequence `n ↦ (X choose n)` in `K[X]`.
* `TauCeti.binomialPolynomialBasis`: the resulting basis of `K[X]` over `K`.
* `TauCeti.linearIndependent_ringChoose_X`: linear independence over `K`.
* `TauCeti.linearIndependent_ringChoose_X_int`: linear independence over `ℤ`.
* `TauCeti.ringChooseSpanBasisX`: the integral basis of the subgroup generated by these
  polynomials in `K[X]`.
* `TauCeti.mem_ringChooseSpan_X_iff_existsUnique`: the unique integral expansion theorem.

## References

* J. C. Jantzen, *Representations of Algebraic Groups*, II.1.
* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, §26.
-/

public section

namespace TauCeti

open Polynomial

attribute [local instance] Classical.propDecidable
attribute [local instance] TauCeti.moduleNNRat
attribute [local instance] BinomialRing.toIsAddTorsionFree

/-! ## The polynomial basis -/

variable (K : Type*) [Ring K] [Algebra ℚ K]

/-- Multiplying the `n`th binomial polynomial by `n!` gives the descending Pochhammer
polynomial. -/
theorem factorial_smul_ringChoose_X_eq_descPochhammer (n : ℕ) :
    (n.factorial : K) • Ring.choose (X : K[X]) n = descPochhammer K n := by
  rw [Nat.cast_smul_eq_nsmul, ← Ring.descPochhammer_eq_factorial_smul_choose,
    ← Polynomial.eval₂_smulOneHom_eq_smeval]
  rw [RingHom.eq_intCast' RingHom.smulOneHom]
  have hX : (X : K[X]) = (Polynomial.mapRingHom (Int.castRingHom K)) X := by
    simp only [Polynomial.coe_mapRingHom, Polynomial.map_X]
  rw [hX, Polynomial.eval₂_intCastRingHom_X]
  simp only [Polynomial.coe_mapRingHom, descPochhammer_map]

/-- The `n`th binomial polynomial has degree `n`. -/
@[simp]
theorem degree_ringChoose_X [Nontrivial K] (n : ℕ) :
    (Ring.choose (X : K[X]) n).degree = n := by
  have hreg : IsSMulRegular K (n.factorial : K) :=
    (IsUnit.natCast_factorial_of_algebra ℚ n).isSMulRegular K
  have h := congrArg Polynomial.degree (factorial_smul_ringChoose_X_eq_descPochhammer K n)
  rw [Polynomial.degree_smul_of_smul_regular (Ring.choose (X : K[X]) n) hreg,
    descPochhammer_degree] at h
  exact h

/-- The `n`th binomial polynomial has natural degree `n`. -/
@[simp]
theorem natDegree_ringChoose_X [Nontrivial K] (n : ℕ) :
    (Ring.choose (X : K[X]) n).natDegree = n :=
  natDegree_eq_of_degree_eq_some (degree_ringChoose_X K n)

/-- The `n`th binomial polynomial is nonzero. -/
@[simp]
theorem ringChoose_X_ne_zero [Nontrivial K] (n : ℕ) :
    Ring.choose (X : K[X]) n ≠ 0 :=
  degree_ne_bot.mp (by rw [degree_ringChoose_X]; exact WithBot.coe_ne_bot)

/-- The binomial polynomials, ordered by degree, as a polynomial sequence. -/
noncomputable def binomialPolynomialSequence [Nontrivial K] : Polynomial.Sequence K where
  elems' := fun n => Ring.choose X n
  degree_eq' := degree_ringChoose_X K

/-- Evaluating the binomial polynomial sequence at index `n` yields `Ring.choose X n`. -/
@[simp]
theorem binomialPolynomialSequence_apply [Nontrivial K] (n : ℕ) :
    binomialPolynomialSequence K n = Ring.choose X n :=
  (rfl)

/-- The leading coefficient of `(X choose n)` is `algebraMap ℚ K (n.factorial : ℚ)⁻¹`. -/
@[simp]
theorem leadingCoeff_ringChoose_X (n : ℕ) :
    (Ring.choose (X : K[X]) n).leadingCoeff = algebraMap ℚ K (n.factorial : ℚ)⁻¹ := by
  have hreg : IsSMulRegular K (n.factorial : K) :=
    (IsUnit.natCast_factorial_of_algebra ℚ n).isSMulRegular K
  have h := congrArg Polynomial.leadingCoeff (factorial_smul_ringChoose_X_eq_descPochhammer K n)
  rw [Polynomial.leadingCoeff_smul_of_smul_regular (Ring.choose (X : K[X]) n) hreg,
    (monic_descPochhammer n).leadingCoeff, smul_eq_mul] at h
  have hfac : (n.factorial : K) = algebraMap ℚ K (n.factorial : ℚ) := by
    simp only [map_natCast]
  rw [hfac] at h
  have hinv : (algebraMap ℚ K (n.factorial : ℚ)⁻¹) * algebraMap ℚ K (n.factorial : ℚ) = 1 := by
    rw [← map_mul, inv_mul_cancel₀ (Nat.cast_ne_zero.mpr (Nat.factorial_ne_zero n)), map_one]
  calc
    (Ring.choose (X : K[X]) n).leadingCoeff =
        (algebraMap ℚ K (n.factorial : ℚ)⁻¹) *
          (algebraMap ℚ K (n.factorial : ℚ) * (Ring.choose (X : K[X]) n).leadingCoeff) := by
      rw [← mul_assoc, hinv, one_mul]
    _ = algebraMap ℚ K (n.factorial : ℚ)⁻¹ := by rw [h, mul_one]

/-- The leading coefficient of every binomial polynomial is a unit in `K`. -/
theorem isUnit_leadingCoeff_ringChoose_X (n : ℕ) :
    IsUnit (Ring.choose (X : K[X]) n).leadingCoeff := by
  rw [leadingCoeff_ringChoose_X]
  exact (isUnit_iff_ne_zero.mpr (inv_ne_zero (Nat.cast_ne_zero.mpr (Nat.factorial_ne_zero n)))).map
    (algebraMap ℚ K)

/-- The binomial polynomials are linearly independent over `K`. -/
theorem linearIndependent_ringChoose_X [Nontrivial K] :
    LinearIndependent K (fun n : ℕ => Ring.choose (X : K[X]) n) :=
  (binomialPolynomialSequence K).linearIndependent_of_isRightRegular_leadingCoeff fun n =>
    (isUnit_leadingCoeff_ringChoose_X K n).isRegular.right

/-- The binomial polynomials form a basis of `K[X]`. -/
noncomputable def binomialPolynomialBasis [Nontrivial K] : Module.Basis ℕ K K[X] :=
  (binomialPolynomialSequence K).basisOfIsUnitLeadingCoeff
    (isUnit_leadingCoeff_ringChoose_X K)

/-- The `n`th vector of the binomial polynomial basis is `(X choose n)`. -/
@[simp]
theorem binomialPolynomialBasis_apply [Nontrivial K] (n : ℕ) :
    binomialPolynomialBasis K n = Ring.choose X n :=
  Polynomial.Sequence.basisOfIsUnitLeadingCoeff_apply _ _ _

/-! ## The integral basis -/

/-- The binomial polynomials remain linearly independent after restricting scalars to `ℤ`. -/
theorem linearIndependent_ringChoose_X_int [Nontrivial K] :
    LinearIndependent ℤ (fun n : ℕ => Ring.choose (X : K[X]) n) :=
  (linearIndependent_ringChoose_X K).restrict_scalars' ℤ

/-- The binomial polynomials form an integral basis of their additive span in `K[X]`. -/
noncomputable def ringChooseSpanBasisX [Nontrivial K] :
    Module.Basis ℕ ℤ (ringChooseSpan (X : K[X])).toIntSubmodule :=
  (binomialPolynomialBasis K).addSubgroupOfClosure (ringChooseSpan (X : K[X])) (by
    have hrange : Set.range ⇑(binomialPolynomialBasis K) = Set.range (Ring.choose (X : K[X])) := by
      ext p; simp
    rw [ringChooseSpan_def, hrange])

/-- The `n`th vector of the integral basis is `(X choose n)`. -/
@[simp]
theorem coe_ringChooseSpanBasisX_apply [Nontrivial K] (n : ℕ) :
    (ringChooseSpanBasisX K n : K[X]) = Ring.choose X n := by
  simp [ringChooseSpanBasisX]

/-- A polynomial in `K[X]` lies in the integral binomial span exactly when it has a unique finite
integral expansion in the binomial polynomials. -/
theorem mem_ringChooseSpan_X_iff_existsUnique [Nontrivial K] (p : K[X]) :
    p ∈ ringChooseSpan (X : K[X]) ↔
      ∃! a : ℕ →₀ ℤ,
        a.sum (fun n z => z • Ring.choose (X : K[X]) n) = p :=
  mem_ringChooseSpan_iff_existsUnique (linearIndependent_ringChoose_X_int K) p

end TauCeti
