/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.Multiquadratic.Quadratic.Discriminant
import TauCeti.NumberTheory.NumberField.IntegralSqrt

/-!
# Quadratic fields attached to prime discriminants

A prime discriminant `D` determines the quadratic field generated by a square root of
`primeDiscriminantRadicand D`. This file identifies the number-field discriminant of that field
with `D` itself.

The main theorem is stated first for an arbitrary presentation of the quadratic field, and then
for the intermediate field generated by a root. The latter is the form needed to compute the
discriminant of the prime-discriminant compositum: Mathlib's
`NumberField.natAbs_discr_eq_natAbs_discr_pow_mul_natAbs_discr_pow` combines linearly disjoint
number fields whose mapped different ideals are coprime. Coprime field discriminants establish
that hypothesis via `NumberField.isCoprime_differentIdeal_of_isCoprime_discr`; iterating the
formula over the prime-discriminant factors of a quadratic discriminant is the finite-place input
to the genus-field construction.

The identification of prime discriminants with quadratic-field discriminants is classical; see
D. A. Cox, *Primes of the Form x² + ny²*, and F. Lemmermeyer, *Reciprocity Laws*.

## Main results

* `TauCeti.Multiquadratic.discr_eq_primeDiscriminant_of_sq`: a number field generated by a square
  root of the radicand of `D` has discriminant `D`.
* `TauCeti.Multiquadratic.discr_adjoin_singleton_eq_primeDiscriminant`: the same result for the
  intermediate field generated by the root.
* `TauCeti.Multiquadratic.isCoprime_discr_adjoin_singleton_of_primeDiscriminant`: distinct
  prime-discriminant quadratic fields have coprime discriminants when at most one is even.
-/

public section

open IntermediateField Polynomial
open scoped NumberField

namespace TauCeti.Multiquadratic

private theorem isCoprime_evenPrimeDiscriminant_oddPrimeDiscriminant {D : ℤ} {p : ℕ}
    (hD : IsEvenPrimeDiscriminant D) (hp : Odd p) :
    IsCoprime D (oddPrimeDiscriminant p) := by
  rw [Int.isCoprime_iff_nat_coprime, oddPrimeDiscriminant_natAbs]
  rcases hD with rfl | rfl | rfl
  · exact hp.coprime_two_left.pow_left 2
  · exact hp.coprime_two_left.pow_left 3
  · exact hp.coprime_two_left.pow_left 3

private theorem isCoprime_primeDiscriminant_of_ne_of_not_both_even {D E : ℤ}
    (hD : IsPrimeDiscriminant D) (hE : IsPrimeDiscriminant E) (hne : D ≠ E)
    (heven : ¬ (IsEvenPrimeDiscriminant D ∧ IsEvenPrimeDiscriminant E)) : IsCoprime D E := by
  rcases isPrimeDiscriminant_iff.mp hD with hDeven | ⟨p, hp, hpodd, rfl⟩
  · rcases isPrimeDiscriminant_iff.mp hE with hEeven | ⟨q, _hq, hqodd, rfl⟩
    · exact (heven ⟨hDeven, hEeven⟩).elim
    · exact isCoprime_evenPrimeDiscriminant_oddPrimeDiscriminant hDeven hqodd
  · rcases isPrimeDiscriminant_iff.mp hE with hEeven | ⟨q, hq, _hqodd, rfl⟩
    · exact (isCoprime_evenPrimeDiscriminant_oddPrimeDiscriminant hEeven hpodd).symm
    · rw [Int.isCoprime_iff_nat_coprime, oddPrimeDiscriminant_natAbs,
        oddPrimeDiscriminant_natAbs]
      exact (Nat.coprime_primes hp hq).mpr fun hpq => hne (by rw [hpq])

/-- A number field generated by a square root of the radicand of a prime discriminant `D` has
field discriminant `D`.

The root need not be supplied as an algebraic integer: its square is an integer, so integrality is
automatic. -/
theorem discr_eq_primeDiscriminant_of_sq {K : Type*} [Field K] [NumberField K] {D : ℤ}
    (hD : IsPrimeDiscriminant D) {x : K}
    (hx : x ^ 2 = algebraMap ℤ K (primeDiscriminantRadicand D))
    (hgen : Algebra.adjoin ℚ {x} = ⊤) : NumberField.discr K = D := by
  let d := primeDiscriminantRadicand D
  let θ : 𝓞 K := TauCeti.NumberField.integralSqrt hx
  have hθ : algebraMap (𝓞 K) K θ = x := TauCeti.NumberField.algebraMap_integralSqrt hx
  have hmin : minpoly ℤ θ = X ^ 2 - C d :=
    TauCeti.NumberField.minpoly_integralSqrt hx (not_isSquare_primeDiscriminantRadicand_rat hD)
  have hgenθ : Algebra.adjoin ℚ {(θ : K)} = ⊤ := by
    rw [NumberField.RingOfIntegers.coe_eq_algebraMap, hθ]
    exact hgen
  rw [discr_eq_fundamentalDiscriminant hmin hgenθ (squarefree_primeDiscriminantRadicand hD),
    fundamentalDiscriminant_primeDiscriminantRadicand hD]

/-- The quadratic intermediate field generated by a square root of the radicand of a prime
discriminant `D` has field discriminant `D`. This is the form used when adjoining the
prime-discriminant roots one at a time in their compositum. -/
theorem discr_adjoin_singleton_eq_primeDiscriminant {L : Type*} [Field L] [CharZero L]
    {D : ℤ} (hD : IsPrimeDiscriminant D) {x : L}
    (hx : x ^ 2 = algebraMap ℤ L (primeDiscriminantRadicand D)) :
    let hxint : IsIntegral ℚ x := IsIntegral.of_pow (n := 2) (by norm_num) (by
      rw [hx, IsScalarTower.algebraMap_apply ℤ ℚ L]
      exact isIntegral_algebraMap)
    letI : NumberField (adjoin ℚ {x}) :=
      { to_finiteDimensional := adjoin.finiteDimensional hxint }
    NumberField.discr (adjoin ℚ {x}) = D := by
  have hxint : IsIntegral ℚ x := IsIntegral.of_pow (n := 2) (by norm_num) (by
    rw [hx, IsScalarTower.algebraMap_apply ℤ ℚ L]
    exact isIntegral_algebraMap)
  let _ : NumberField (adjoin ℚ {x}) :=
    { to_finiteDimensional := adjoin.finiteDimensional hxint }
  let pb : PowerBasis ℚ (adjoin ℚ {x}) := adjoin.powerBasis hxint
  apply discr_eq_primeDiscriminant_of_sq hD (x := pb.gen)
  · apply Subtype.ext
    simpa [pb, adjoin.powerBasis_gen] using hx
  · exact pb.adjoin_gen_eq_top

/-- Quadratic fields attached to distinct prime discriminants have coprime field discriminants,
provided the two discriminants are not both even. The prime-discriminant factorization of a
quadratic discriminant has exactly this property, so this is the coprimality input to Mathlib's
discriminant formula for a compositum. -/
theorem isCoprime_discr_adjoin_singleton_of_primeDiscriminant {L : Type*} [Field L]
    [CharZero L] {D E : ℤ} (hD : IsPrimeDiscriminant D) (hE : IsPrimeDiscriminant E)
    (hne : D ≠ E) (heven : ¬ (IsEvenPrimeDiscriminant D ∧ IsEvenPrimeDiscriminant E))
    {x y : L} (hx : x ^ 2 = algebraMap ℤ L (primeDiscriminantRadicand D))
    (hy : y ^ 2 = algebraMap ℤ L (primeDiscriminantRadicand E)) :
    let hxint : IsIntegral ℚ x := IsIntegral.of_pow (n := 2) (by norm_num) (by
      rw [hx, IsScalarTower.algebraMap_apply ℤ ℚ L]
      exact isIntegral_algebraMap)
    let hyint : IsIntegral ℚ y := IsIntegral.of_pow (n := 2) (by norm_num) (by
      rw [hy, IsScalarTower.algebraMap_apply ℤ ℚ L]
      exact isIntegral_algebraMap)
    letI : NumberField (adjoin ℚ {x}) :=
      { to_finiteDimensional := adjoin.finiteDimensional hxint }
    letI : NumberField (adjoin ℚ {y}) :=
      { to_finiteDimensional := adjoin.finiteDimensional hyint }
    IsCoprime (NumberField.discr (adjoin ℚ {x})) (NumberField.discr (adjoin ℚ {y})) := by
  dsimp only
  have hxint : IsIntegral ℚ x := IsIntegral.of_pow (n := 2) (by norm_num) (by
    rw [hx, IsScalarTower.algebraMap_apply ℤ ℚ L]
    exact isIntegral_algebraMap)
  have hyint : IsIntegral ℚ y := IsIntegral.of_pow (n := 2) (by norm_num) (by
    rw [hy, IsScalarTower.algebraMap_apply ℤ ℚ L]
    exact isIntegral_algebraMap)
  let _ : NumberField (adjoin ℚ {x}) :=
    { to_finiteDimensional := adjoin.finiteDimensional hxint }
  let _ : NumberField (adjoin ℚ {y}) :=
    { to_finiteDimensional := adjoin.finiteDimensional hyint }
  rw [discr_adjoin_singleton_eq_primeDiscriminant hD hx,
    discr_adjoin_singleton_eq_primeDiscriminant hE hy]
  exact isCoprime_primeDiscriminant_of_ne_of_not_both_even hD hE hne heven

end TauCeti.Multiquadratic
