/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.Multiquadratic.Prime.Discriminant.Independence
public import TauCeti.NumberTheory.Multiquadratic.Subfield.Classification
import TauCeti.NumberTheory.Multiquadratic.RelativeDegree

/-!
# The relative degree of the prime-discriminant compositum over its quadratic base

The genus-field layer builds the candidate genus field of `ℚ(√d)` as the compositum
`M = ℚ(√(radicand P) : P)` of the quadratic fields attached to the prime discriminants `P`
dividing the discriminant of `ℚ(√d)`. `Prime/Discriminant/Independence` records its **absolute**
degree, `[M : ℚ] = 2ᵗ` (`finrank_adjoin_roots_primeDiscriminantRadicands`). This file records the
complementary **relative** degree of `M` over the quadratic subfield generated by the product of
*all* the chosen roots:

`[M : ℚ(∏ root)] = 2 ^ (t - 1)`.

That product root squares to the product `∏ radicand P` of the radicands, which for the
prime-discriminant factorization of a fundamental discriminant is (a square times) the radicand `d`
itself; so the base `ℚ(∏ root)` is the copy of `ℚ(√d)` inside the candidate genus field, and this is
the relative degree `[K_gen : ℚ(√d)] = 2 ^ (t - 1)` the roadmap's genus-field examples read off.

The proof is the general subfield-lattice relative-degree theorem
`finrank_top_over_intermediateField_of_finrank_eq_two` — `M` has degree `2 ^ (n - 1)` over any of
its quadratic subfields — applied to the product-of-all-roots subfield
(`quadraticSubfieldOfFinset` on `Finset.univ`, whose degree over `ℚ` is `2`), fed the prime-
discriminant square-class independence
`not_isSquare_prod_primeDiscriminantRadicands_of_forall_isEvenPrimeDiscriminant_eq`. The roadmap's
`ℚ(√-5)` and `ℚ(√-21)` examples establish the analogous relative degree for their concrete
subfields.

The prime-discriminant description of the genus field is classical; see D. A. Cox,
*Primes of the Form x² + ny²*, and F. Lemmermeyer, *Reciprocity Laws*.

## Main results

* `TauCeti.Multiquadratic.finrank_adjoin_range_over_prodRootMem_univ_of_primeDiscriminants`: for an
  injective family of prime discriminants with at most one even member, the compositum of the roots
  of their radicands has degree `2 ^ (t - 1)` over the quadratic subfield generated by the product
  of all the roots.
-/

public section

open IntermediateField

namespace TauCeti.Multiquadratic

/-- **Relative degree of the prime-discriminant compositum over its `ℚ(√d)` base.** Let `D : ι → ℤ`
be a nonempty, injective family of prime discriminants with at most one even member (the shape
supplied by the prime-discriminant factorization of a quadratic discriminant), and let `root i` be
chosen square roots of their radicands in a field `L ⊇ ℚ`. Then the compositum
`M = ℚ(root i : i)` — the candidate genus field — has degree `2 ^ (|ι| - 1)` over the quadratic
subfield `ℚ(∏ᵢ root i)` generated by the product of all the roots.

That product root squares to `∏ᵢ radicand (D i)`; when the `D i` are the prime discriminants of the
fundamental discriminant of a squarefree `d` this product is `d`, so the base is the copy of
`ℚ(√d)` inside `M` and the statement is `[K_gen : ℚ(√d)] = 2 ^ (t - 1)`. The concrete `ℚ(√-21)`
and `ℚ(√-5)` examples establish this relative degree for their specific subfields. -/
theorem finrank_adjoin_range_over_prodRootMem_univ_of_primeDiscriminants
    {ι : Type*} [Fintype ι] [Nonempty ι] {L : Type*} [Field L] [Algebra ℚ L]
    (D : ι → ℤ) (hD : ∀ i, IsPrimeDiscriminant (D i)) (hinj : Function.Injective D)
    (heven_unique : ∀ i j,
      IsEvenPrimeDiscriminant (D i) → IsEvenPrimeDiscriminant (D j) → D i = D j)
    (root : ι → L)
    (hroot : ∀ i, root i ^ 2 = algebraMap ℚ L ((primeDiscriminantRadicand (D i) : ℤ) : ℚ)) :
    Module.finrank
        (adjoin ℚ {prodRootMem (K := ℚ) root (Finset.univ : Finset ι)})
        (adjoin ℚ (Set.range root)) = 2 ^ (Nat.card ι - 1) := by
  have hindep : ∀ S : Finset ι, S.Nonempty →
      ¬ IsSquare (∏ i ∈ S, ((primeDiscriminantRadicand (D i) : ℤ) : ℚ)) :=
    not_isSquare_prod_primeDiscriminantRadicands_of_forall_isEvenPrimeDiscriminant_eq
      D hD hinj heven_unique
  have hF : Module.finrank ℚ (adjoin ℚ {prodRootMem (K := ℚ) root (Finset.univ : Finset ι)}) = 2 :=
    finrank_adjoin_prodRootMem hroot (hindep Finset.univ Finset.univ_nonempty)
  exact finrank_top_over_intermediateField_of_finrank_eq_two hroot hindep _ hF

end TauCeti.Multiquadratic
