/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.Multiquadratic.Legendre.PrimeDiscriminant.Examples
public import TauCeti.NumberTheory.Multiquadratic.Prime.Discriminant.Splitting
import TauCeti.NumberTheory.NumberField.Internal.PrimeDivisibility

/-!
# Complete splitting criteria for the first genus-field examples

The multiquadratic roadmap's genus-field worked examples begin with
`ℚ(√-5)`, whose prime-discriminant generators are `-4` and `5`, and
`ℚ(√-21)`, whose prime-discriminant generators are `-4`, `-3`, and `-7`.
The general prime-discriminant splitting theorem already gives the complete-splitting condition
in a uniform dependent form. This file records the corresponding concrete complete-splitting
criteria, using the concrete character criteria from
`TauCeti.NumberTheory.Multiquadratic.Legendre.PrimeDiscriminant.Examples`.

The prime-discriminant convention follows Cox's *Primes of the Form x² + ny²* and
Lemmermeyer's *Reciprocity Laws*, as in the prime-discriminant splitting API this file reuses.

## Main results

* `TauCeti.NumberField.ncard_primesOver_neg_four_five_iff` and
  `TauCeti.NumberField.ncard_primesOver_neg_four_neg_three_neg_seven_iff`: complete-splitting
  forms for fields generated by square roots of the associated radicands.
-/

public section

open Ideal Module NumberField

namespace TauCeti.NumberField

variable {K : Type*} [Field K] [NumberField K]

private theorem not_intCast_prime_dvd_neg_four {p : ℕ} [Fact p.Prime] (hodd : p ≠ 2) :
    ¬ (p : ℤ) ∣ (-4 : ℤ) := by
  intro h
  have hp_dvd_four : p ∣ 4 := by exact_mod_cast (Int.dvd_neg.mp h)
  have hp_dvd_two : p ∣ 2 := by
    have hpow : p ∣ 2 ^ 2 := by simpa using hp_dvd_four
    exact Nat.Prime.dvd_of_dvd_pow Fact.out hpow
  exact hodd ((Nat.prime_dvd_prime_iff_eq Fact.out Nat.prime_two).mp hp_dvd_two)

private theorem forall_not_dvd_negFourFivePrimeDiscriminants {p : ℕ} [Fact p.Prime]
    (hodd : p ≠ 2) (hfive : p ≠ 5) :
    ∀ i, ¬ (p : ℤ) ∣ TauCeti.Multiquadratic.negFourFivePrimeDiscriminants i := by
  intro i
  fin_cases i
  · exact not_intCast_prime_dvd_neg_four hodd
  · exact Internal.not_intCast_prime_dvd_natPrime (by decide : Nat.Prime 5) hfive

private theorem forall_not_dvd_negFourNegThreeNegSevenPrimeDiscriminants {p : ℕ} [Fact p.Prime]
    (hodd : p ≠ 2) (hthree : p ≠ 3) (hseven : p ≠ 7) :
    ∀ i, ¬ (p : ℤ) ∣
      TauCeti.Multiquadratic.negFourNegThreeNegSevenPrimeDiscriminants i := by
  intro i
  fin_cases i
  · exact not_intCast_prime_dvd_neg_four hodd
  · simpa using Internal.not_intCast_prime_dvd_natPrime (by decide : Nat.Prime 3) hthree
  · simpa using Internal.not_intCast_prime_dvd_natPrime (by decide : Nat.Prime 7) hseven

/-- **Complete splitting for the `ℚ(√-5)` genus-field generator list.** Let `K` be generated
by square roots of the radicands attached to `[-4, 5]`, namely `-1` and `5`. An odd prime
`p ≠ 5` splits completely in `K` exactly under the two character conditions
`p ≡ 1 (mod 4)` and `(p / 5) = 1`. -/
theorem ncard_primesOver_neg_four_five_iff (r : Fin 2 → K) (hr : ∀ i, r i ^ 2 = algebraMap ℤ K
      (TauCeti.Multiquadratic.primeDiscriminantRadicand
        (TauCeti.Multiquadratic.negFourFivePrimeDiscriminants i)))
    (htop : IntermediateField.adjoin ℚ (Set.range r) = ⊤)
    {p : ℕ} [Fact p.Prime] (hodd : p ≠ 2) (hfive : p ≠ 5) :
    (primesOver (span {(p : ℤ)}) (RingOfIntegers K)).ncard = finrank ℚ K ↔
      p % 4 = 1 ∧ @legendreSym 5 ⟨by decide⟩ (p : ℤ) = 1 :=
  (ncard_primesOver_primeDiscriminantRadicands_iff
    TauCeti.Multiquadratic.negFourFivePrimeDiscriminants r hr htop hodd
      (forall_not_dvd_negFourFivePrimeDiscriminants hodd hfive)).trans
        (TauCeti.Multiquadratic.forall_legendreSym_neg_four_five_eq_one_iff hodd)

/-- **Complete splitting for the `ℚ(√-21)` genus-field generator list.** Let `K` be generated
by square roots of the radicands attached to `[-4, -3, -7]`, namely `-1`, `-3`, and `-7`.
An odd prime `p` not among `3` and `7` splits completely in `K` exactly under the three
character conditions `p ≡ 1 (mod 4)`, `(p / 3) = 1`, and `(p / 7) = 1`. -/
theorem ncard_primesOver_neg_four_neg_three_neg_seven_iff (r : Fin 3 → K)
    (hr : ∀ i, r i ^ 2 = algebraMap ℤ K (TauCeti.Multiquadratic.primeDiscriminantRadicand
        (TauCeti.Multiquadratic.negFourNegThreeNegSevenPrimeDiscriminants i)))
    (htop : IntermediateField.adjoin ℚ (Set.range r) = ⊤)
    {p : ℕ} [Fact p.Prime] (hodd : p ≠ 2) (hthree : p ≠ 3) (hseven : p ≠ 7) :
    (primesOver (span {(p : ℤ)}) (RingOfIntegers K)).ncard = finrank ℚ K ↔
      p % 4 = 1 ∧ @legendreSym 3 ⟨by decide⟩ (p : ℤ) = 1 ∧
        @legendreSym 7 ⟨by decide⟩ (p : ℤ) = 1 :=
  (ncard_primesOver_primeDiscriminantRadicands_iff
    TauCeti.Multiquadratic.negFourNegThreeNegSevenPrimeDiscriminants r hr htop hodd
      (forall_not_dvd_negFourNegThreeNegSevenPrimeDiscriminants hodd hthree hseven)).trans
        (TauCeti.Multiquadratic.forall_legendreSym_neg_four_neg_three_neg_seven_eq_one_iff
          hodd)

end TauCeti.NumberField
