/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.GroupTheory.Presentation.GroupPresentation

/-!
# A transcribed presentation of the Higman--Sims group

This file carries the `HS` row of the sporadic presentation data required by milestone S1 of
`TauCetiRoadmap/CFSGStatement/README.md`. It records John Bray's ATLAS version 3 presentation of
the Higman--Sims group on its standard generators `a` and `b` as a `TauCeti.GroupPresentation`,
together with the source, the generator convention, transcription notes, and the expected counts.

Writing `s₁ = ab`, `s₂ = ab²`, `s₋₁ = ab⁻¹` and `s₋₂ = ab⁻²` for the four syllables that occur, the
thirteen transcribed relators are

```text
a², b⁵, s₁¹¹, s₂¹⁰, [a,b]⁵, [a,bab]³, [a,b²]⁶,
s₁s₁s₂s₋₁s₋₂s₋₁s₂s₁s₁s₋₂⁴,
s₁(s₂s₋₂²)²s₂s₁s₂(s₋₁s₂)²,
s₁s₁s₂²s₁s₋₁²s₁s₂²s₁s₁s₋₂s₋₁s₋₂,
(s₁s₁s₂s₋₁s₋₂s₁s₁s₋₁)²,
(s₁s₁s₂)²s₁s₁s₋₁s₁s₁s₂³s₁s₁s₋₁,
s₁(s₁s₂)³s₁s₁s₂s₋₁s₁s₋₂s₁s₋₁s₂.
```

The last three are redundant, and are flagged as such by the source; they are transcribed anyway
because the coset enumerations that the source uses to justify the presentation are run with them.

The source's commutator convention is `[r,s] = r⁻¹s⁻¹rs`, opposite to Mathlib's
`commutatorElement`, so each commutator is stored as `Relator.comm (.inv r) (.inv s)` as
`TauCeti.Relator` prescribes. The proved `TauCeti.Relator.toWord_toFreeGroup` is the audit boundary
between these expressions and the signed words that `PresentedGroup` consumes.

The source is a presentation rather than a semi-presentation, and it comes with a demonstration of
correctness: the relations `a² = b⁵ = (ab)¹¹ = 1` force the presented group to be perfect and
generated by conjugates of `a`; the subgroup listed in the source visibly centralizes `a` and a
coset enumeration returns the index `5775` of the involution centralizer of `HS`; and the double
cover `2·HS` is excluded because `ab²` lifts to elements of order `20` there, while `(ab²)¹⁰ = 1` is
a relator. GAP 4.15.1 independently checks that the thirteen words compiled by `Relator.toWord`
from the expressions below vanish on five independent standard generating pairs of the 100-point
primitive representation of `HS`, that is, pairs generating the group with `a` an involution whose
centralizer has order `7680`, `b` of order 5 with centralizer of order `500`, and `ab` of order
`11`. Both computations are provenance for the transcription, not Lean theorems: this file asserts
no order, finiteness, simplicity, or identification result.

## Main definition

* `TauCeti.Sporadic.hsPresentation`: John Bray's ATLAS finite presentation of `HS`.

## References

* R. A. Wilson, R. A. Parker, J. N. Bray et al., *ATLAS of Finite Group Representations*,
  version 3, presentation `HSG1-P1`, contributed by John Bray,
  <https://brauer.maths.qmul.ac.uk/Atlas/v3/pres/HSG1-P1>, with the relators and the demonstration
  of correctness in the Magma source file
  <https://brauer.maths.qmul.ac.uk/Atlas/spor/HS/mag/HSG1-P1.M>.
-/

public section

namespace TauCeti.Sporadic

private abbrev a : Relator (Fin 2) := .gen 0

private abbrev b : Relator (Fin 2) := .gen 1

@[inherit_doc Relator.mul]
local infixl:70 " ⬝ " => Relator.mul

/-- The source's commutator `[r, s] = r⁻¹ s⁻¹ r s`, which is `⁅r⁻¹, s⁻¹⁆` in Mathlib's
convention. -/
private abbrev sourceComm (r s : Relator (Fin 2)) : Relator (Fin 2) := .comm (.inv r) (.inv s)

/-- The syllable `a * b`. -/
private abbrev ab1 : Relator (Fin 2) := a ⬝ b

/-- The syllable `a * b ^ 2`. -/
private abbrev ab2 : Relator (Fin 2) := a ⬝ .pow b 2

/-- The syllable `a * b⁻¹`. -/
private abbrev abNeg1 : Relator (Fin 2) := a ⬝ .inv b

/-- The syllable `a * b⁻²`. -/
private abbrev abNeg2 : Relator (Fin 2) := a ⬝ .pow (.inv b) 2

/-- John Bray's ATLAS version 3 finite presentation of the Higman--Sims group `HS` on its standard
generators `a` and `b`.

The ATLAS lists this as a full presentation of the abstract group, separately from the
semi-presentation used to recognize standard generators inside a group already constructed. No
structural property of the presented group is asserted here: this definition records only the
cited generators and relations. -/
def hsPresentation : GroupPresentation where
  generatorNames := ["a", "b"]
  source := "R. A. Wilson, R. A. Parker, J. N. Bray et al., ATLAS of Finite Group \
    Representations, version 3; presentation contributed by John Bray"
  sourceLocator := "HSG1-P1, https://brauer.maths.qmul.ac.uk/Atlas/v3/pres/HSG1-P1, with the \
    relator list and the demonstration of correctness in the Magma source file \
    https://brauer.maths.qmul.ac.uk/Atlas/spor/HS/mag/HSG1-P1.M"
  generatorConvention := "The ATLAS standard generators a and b of HS, that is, a in class 2A and \
    b in class 5A with ab of order 11, in that order, so index 0 is a and index 1 is b. Products \
    are read left to right, negative exponents denote inverses, and [r,s] denotes r^-1 s^-1 r s."
  transcriptionNotes := "The thirteen words of the source's relator list are stored as thirteen \
    relators equal to the identity. The last three, marked R1, R2 and R3 there, are redundant, \
    and are transcribed because the source runs its coset enumerations with them. The source \
    demonstrates correctness by enumerating the 5775 cosets of a subgroup that visibly \
    centralizes a, using (a*b^2)^10 = 1 to exclude the double cover 2.HS. GAP 4.15.1 checks that \
    the thirteen compiled words vanish on five independent standard generating pairs of the \
    100-point primitive representation of HS, taking a with centralizer of order 7680, b of \
    order 5 with centralizer of order 500, and ab of order 11."
  expectedGeneratorCount := 2
  expectedRelatorCount := 13
  transcribed :=
    [ .pow a 2,
      .pow b 5,
      .pow ab1 11,
      .pow ab2 10,
      .pow (sourceComm a b) 5,
      .pow (sourceComm a (b ⬝ a ⬝ b)) 3,
      .pow (sourceComm a (.pow b 2)) 6,
      ab1 ⬝ ab1 ⬝ ab2 ⬝ abNeg1 ⬝ abNeg2 ⬝ abNeg1 ⬝ ab2 ⬝ ab1 ⬝ ab1 ⬝ .pow abNeg2 4,
      ab1 ⬝ .pow (ab2 ⬝ .pow abNeg2 2) 2 ⬝ ab2 ⬝ ab1 ⬝ ab2 ⬝ .pow (abNeg1 ⬝ ab2) 2,
      ab1 ⬝ ab1 ⬝ .pow ab2 2 ⬝ ab1 ⬝ .pow abNeg1 2 ⬝ ab1 ⬝ .pow ab2 2 ⬝ ab1 ⬝ ab1 ⬝
        abNeg2 ⬝ abNeg1 ⬝ abNeg2,
      .pow (ab1 ⬝ ab1 ⬝ ab2 ⬝ abNeg1 ⬝ abNeg2 ⬝ ab1 ⬝ ab1 ⬝ abNeg1) 2,
      .pow (ab1 ⬝ ab1 ⬝ ab2) 2 ⬝ ab1 ⬝ ab1 ⬝ abNeg1 ⬝ ab1 ⬝ ab1 ⬝ .pow ab2 3 ⬝ ab1 ⬝ ab1 ⬝ abNeg1,
      ab1 ⬝ .pow (ab1 ⬝ ab2) 3 ⬝ ab1 ⬝ ab1 ⬝ ab2 ⬝ abNeg1 ⬝ ab1 ⬝ abNeg2 ⬝ ab1 ⬝ abNeg1 ⬝ ab2 ]

/-- The generator and relator counts recorded for `HS` agree with the transcribed data. -/
theorem matchesMetadata_hsPresentation : hsPresentation.matchesMetadata := by decide

end TauCeti.Sporadic
