/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.GroupTheory.Presentation.GroupPresentation

/-!
# A transcribed presentation of the McLaughlin group

This file carries the `McL` row of the sporadic presentation data required by milestone S1 of
`TauCetiRoadmap/CFSGStatement/README.md`. It records John Bray's ATLAS version 3 presentation of
the McLaughlin group on its standard generators `a` and `b` as a `TauCeti.GroupPresentation`,
together with the source, the generator convention, transcription notes, and the expected counts.

Writing `s₁ = ab`, `s₂ = ab²`, `s₋₁ = ab⁻¹` and `s₋₂ = ab⁻²` for the four syllables that occur, the
fifteen transcribed relators are

```text
a², b⁵, [a,b]⁵, s₁¹¹, s₂¹², [a,b²]⁶, (s₁s₋₂)⁷,
[a, b⁻²s₁s₁s₂]²,
[a, b⁻²s₂s₋₁s₁s₂²s₁s₋₁],
[a, bs₂³]²,
[a, b²s₁s₂²]²,
s₁s₂s₋₂s₁s₋₁s₂(s₋₂s₁)²(s₂s₋₂s₂)²,
[a, b²s₂s₋₁s₂]²,
[a, b²s₁]⁴,
[a, b²s₂]⁴.
```

Three of these are redundant, and are flagged as such by the source; they are transcribed anyway
because the coset enumerations that the source uses to justify the presentation are easier with
them.

The source's commutator convention is `[r,s] = r⁻¹s⁻¹rs`, opposite to Mathlib's
`commutatorElement`, so each commutator is stored as `Relator.comm (.inv r) (.inv s)` as
`TauCeti.Relator` prescribes. The proved `TauCeti.Relator.toWord_toFreeGroup` is the audit boundary
between these expressions and the signed words that `PresentedGroup` consumes.

The source is a presentation rather than a semi-presentation, and it comes with a demonstration of
correctness: the relations `a² = b⁵ = (ab)¹¹ = 1` force the presented group to be perfect and
generated by conjugates of `a`; the relations `a² = [a,b]⁵ = [a,b²]⁶ = 1` force the subgroup listed
in the source to centralize `a`; a coset enumeration returns the index `22275` of the involution
centralizer of `McL`, leaving `McL` or its triple cover `3·McL`; and the latter is excluded because
its standard generators have `|AB| = 33`, while `(ab)¹¹ = 1` is a relator. GAP 4.15.1 independently
checks that the fifteen words compiled by `Relator.toWord` from the expressions below vanish on
five independent standard generating pairs of the 275-point primitive representation of `McL`,
that is, pairs generating the group whose centralizers have orders `40320` and `750` and which
meet the two ATLAS element-order conditions. Both computations are provenance for the
transcription, not Lean theorems: this file asserts no order, finiteness, simplicity, or
identification result.

## Main definition

* `TauCeti.Sporadic.mclPresentation`: John Bray's ATLAS finite presentation of `McL`.

## References

* R. A. Wilson, R. A. Parker, J. N. Bray et al., *ATLAS of Finite Group Representations*,
  version 3, presentation `McLG1-P1`, contributed by John Bray,
  <https://brauer.maths.qmul.ac.uk/Atlas/v3/pres/McLG1-P1>, with the relators and the
  demonstration of correctness in the Magma source file
  <https://brauer.maths.qmul.ac.uk/Atlas/spor/McL/mag/McLG1-P1.M>.
-/

public section

namespace TauCeti.Sporadic

private abbrev a : Relator (Fin 2) := .gen 0

private abbrev b : Relator (Fin 2) := .gen 1

@[inherit_doc Relator.mul]
local infixl:70 " ⬝ " => Relator.mul

/-- The source's commutator `[r, s] = r⁻¹ s⁻¹ r s`, which is `⁅r⁻¹, s⁻¹⁆` in Mathlib's
convention. -/
private abbrev sourceComm (r s : Relator (Fin 2)) : Relator (Fin 2) := .comm (.inv r) (.inv s)

/-- The syllable `a * b`. -/
private abbrev ab1 : Relator (Fin 2) := a ⬝ b

/-- The syllable `a * b ^ 2`. -/
private abbrev ab2 : Relator (Fin 2) := a ⬝ .pow b 2

/-- The syllable `a * b⁻¹`. -/
private abbrev abNeg1 : Relator (Fin 2) := a ⬝ .inv b

/-- The syllable `a * b⁻²`. -/
private abbrev abNeg2 : Relator (Fin 2) := a ⬝ .pow (.inv b) 2

/-- John Bray's ATLAS version 3 finite presentation of the McLaughlin group `McL` on its standard
generators `a` and `b`.

The ATLAS lists this as a full presentation of the abstract group, separately from the
semi-presentation used to recognize standard generators inside a group already constructed. No
structural property of the presented group is asserted here: this definition records only the
cited generators and relations. -/
def mclPresentation : GroupPresentation where
  generatorNames := ["a", "b"]
  source := "R. A. Wilson, R. A. Parker, J. N. Bray et al., ATLAS of Finite Group \
    Representations, version 3; presentation contributed by John Bray"
  sourceLocator := "McLG1-P1, https://brauer.maths.qmul.ac.uk/Atlas/v3/pres/McLG1-P1, with the \
    relator list and the demonstration of correctness in the Magma source file \
    https://brauer.maths.qmul.ac.uk/Atlas/spor/McL/mag/McLG1-P1.M"
  generatorConvention := "The ATLAS standard generators a and b of McL, that is, a in class 2A \
    and b in class 5A with ab of order 11 and ababababbababbabb of order 7, in that order, so \
    index 0 is a and index 1 is b. Products are read left to right, negative exponents denote \
    inverses, and [r,s] denotes r^-1 s^-1 r s."
  transcriptionNotes := "The fifteen words of the source's relator list are stored as fifteen \
    relators equal to the identity. Three of them, marked R0, R1 and R2 there, are redundant, and \
    are transcribed because the source's coset enumerations are easier with them. The source \
    demonstrates correctness by enumerating the 22275 cosets of a subgroup that centralizes a, \
    then excluding the triple cover 3.McL, whose standard generators have |AB| = 33 rather than \
    11. GAP 4.15.1 checks that the fifteen compiled words vanish on five independent standard \
    generating pairs of the 275-point primitive representation of McL, taking a and b with \
    centralizers of orders 40320 and 750 and imposing the two ATLAS element-order conditions."
  expectedGeneratorCount := 2
  expectedRelatorCount := 15
  transcribed :=
    [ .pow a 2,
      .pow b 5,
      .pow (sourceComm a b) 5,
      .pow ab1 11,
      .pow ab2 12,
      .pow (sourceComm a (.pow b 2)) 6,
      .pow (ab1 ⬝ abNeg2) 7,
      .pow (sourceComm a (.pow (.inv b) 2 ⬝ ab1 ⬝ ab1 ⬝ ab2)) 2,
      sourceComm a (.pow (.inv b) 2 ⬝ ab2 ⬝ abNeg1 ⬝ ab1 ⬝ .pow ab2 2 ⬝ ab1 ⬝ abNeg1),
      .pow (sourceComm a (b ⬝ .pow ab2 3)) 2,
      .pow (sourceComm a (.pow b 2 ⬝ ab1 ⬝ .pow ab2 2)) 2,
      ab1 ⬝ ab2 ⬝ abNeg2 ⬝ ab1 ⬝ abNeg1 ⬝ ab2 ⬝ .pow (abNeg2 ⬝ ab1) 2 ⬝
        .pow (ab2 ⬝ abNeg2 ⬝ ab2) 2,
      .pow (sourceComm a (.pow b 2 ⬝ ab2 ⬝ abNeg1 ⬝ ab2)) 2,
      .pow (sourceComm a (.pow b 2 ⬝ ab1)) 4,
      .pow (sourceComm a (.pow b 2 ⬝ ab2)) 4 ]

/-- The generator and relator counts recorded for `McL` agree with the transcribed data. -/
theorem matchesMetadata_mclPresentation : mclPresentation.matchesMetadata := by decide

end TauCeti.Sporadic
