/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.GroupTheory.Presentation.GroupPresentation

/-!
# A transcribed presentation of the Suzuki sporadic group

This file carries the `Suz` row of the sporadic presentation data required by milestone S1 of
`TauCetiRoadmap/CFSGStatement/README.md`. It records the presentation `GPLTable.Suz.1` from
Rolf Lindenbergh's Group Presentations Library as a `TauCeti.GroupPresentation`, together with
the exact source, generator convention, transcription notes, expected counts, and decidable
checks on the transcription.

The presentation uses the Coxeter graph

```text
  a --5-- b --3-- c --8-- d --3-- e
  b --3-- f --4-- g --3-- b
```

where every generator is an involution and every omitted edge has label `2`. In particular, the
graph contributes seven square relations and one product-order relation for each of the twenty-one
unordered pairs of generators. The labels in the display are the source's path strings
`a5b3c8d3e,b3f4g3b`; the second string is the triangle on `b`, `f`, and `g` and is not joined to
`c`.

The source then appends the six relations

```text
a = (cd)^4,  a = (fg)^2,  (abcf)^5,  (bfg)^5,
((bcdcd)^5 e)^3,  (abcg)^5.
```

The last relation occupies the source record's `presdef[4]` field. The library initialization
includes that field when its `GPL_PCE` option is true, and version 1.0 sets this option to true by
default, so it belongs to the default full presentation transcribed here. The equality decoder in
the same source compiles `x = y` as `x⁻¹y`; that convention determines the first two extra words.

There are therefore `7 + 21 + 6 = 34` relators. The proved metadata theorem checks this count, and
the other two theorems check directly from the compiled signed words that they have total length
`275` and are cyclically reduced. The length is a derived transcription check, not a figure quoted
from the source. As a separate consistency check, GAP 4.15.1 enumerates `1782` cosets of the
subgroup generated by `a` through `f`, which the GPL record labels `G2(4)`. This computation is
transcription provenance rather than a Lean theorem: no order, finiteness, simplicity, or
identification result is asserted here. A separate source-to-Lean read-through remains part of the
S1 review artifact required by the roadmap.

## Main definition

* `TauCeti.Sporadic.suzPresentation`: the GPL finite presentation of the Suzuki sporadic group.

## References

* R. Lindenbergh, *Group Presentations Library*, version 1.0, record `GPLTable.Suz.1`,
  <https://doris.tudelft.nl/~rlindenbergh/GPL/gpl.g>.
* C. E. Praeger and L. H. Soicher, *Low Rank Representations and Graphs for Sporadic Groups*,
  Cambridge University Press, 1997, Chapter 4, doi:10.1017/CBO9780511526039.005.
-/

public section

namespace TauCeti.Sporadic

private abbrev a : Relator (Fin 7) := .gen 0

private abbrev b : Relator (Fin 7) := .gen 1

private abbrev c : Relator (Fin 7) := .gen 2

private abbrev d : Relator (Fin 7) := .gen 3

private abbrev e : Relator (Fin 7) := .gen 4

private abbrev f : Relator (Fin 7) := .gen 5

private abbrev g : Relator (Fin 7) := .gen 6

@[inherit_doc Relator.mul]
local infixl:70 " ⬝ " => Relator.mul

/-- The seven involution relations and the twenty-one pair relations decoded from the two Coxeter
paths `a5b3c8d3e` and `b3f4g3b` in `GPLTable.Suz.1`.

The fourteen nonedges are written explicitly with exponent two, so this list records the complete
Coxeter matrix rather than relying on an implicit default. -/
private def suzCoxeterRelators : List (Relator (Fin 7)) :=
  [ .pow a 2,
    .pow b 2,
    .pow c 2,
    .pow d 2,
    .pow e 2,
    .pow f 2,
    .pow g 2,
    .pow (a ⬝ b) 5,
    .pow (b ⬝ c) 3,
    .pow (c ⬝ d) 8,
    .pow (d ⬝ e) 3,
    .pow (b ⬝ f) 3,
    .pow (f ⬝ g) 4,
    .pow (g ⬝ b) 3,
    .pow (a ⬝ c) 2,
    .pow (a ⬝ d) 2,
    .pow (a ⬝ e) 2,
    .pow (a ⬝ f) 2,
    .pow (a ⬝ g) 2,
    .pow (b ⬝ d) 2,
    .pow (b ⬝ e) 2,
    .pow (c ⬝ e) 2,
    .pow (c ⬝ f) 2,
    .pow (c ⬝ g) 2,
    .pow (d ⬝ f) 2,
    .pow (d ⬝ g) 2,
    .pow (e ⬝ f) 2,
    .pow (e ⬝ g) 2 ]

/-- The six words following the Coxeter paths in `GPLTable.Suz.1`.

The source decoder represents an equality `x = y` by the relator `x⁻¹y`, explaining the leading
inverses in the first two entries. The final entry is the source's optional PCE relation, included
by the library's version 1.0 default. -/
private def suzAdditionalRelators : List (Relator (Fin 7)) :=
  [ .inv a ⬝ .pow (c ⬝ d) 4,
    .inv a ⬝ .pow (f ⬝ g) 2,
    .pow (a ⬝ b ⬝ c ⬝ f) 5,
    .pow (b ⬝ f ⬝ g) 5,
    .pow (.pow (b ⬝ c ⬝ d ⬝ c ⬝ d) 5 ⬝ e) 3,
    .pow (a ⬝ b ⬝ c ⬝ g) 5 ]

/-- The Group Presentations Library finite presentation `GPLTable.Suz.1` of the Suzuki sporadic
group on generators `a`, `b`, `c`, `d`, `e`, `f`, and `g`.

The source describes this as a full presentation of the abstract group and identifies its origin
as Praeger--Soicher. No structural property of the presented group is asserted here: this
definition records only the cited generators and relations. -/
def suzPresentation : GroupPresentation where
  generatorNames := ["a", "b", "c", "d", "e", "f", "g"]
  source := "R. Lindenbergh, Group Presentations Library, version 1.0; presentation attributed \
    there to C. E. Praeger and L. H. Soicher, Low Rank Representations and Graphs for Sporadic \
    Groups, Cambridge University Press, 1997"
  sourceLocator := "GPLTable.Suz.1 in \
    https://doris.tudelft.nl/~rlindenbergh/GPL/gpl.g; Praeger--Soicher, Chapter 4, \
    doi:10.1017/CBO9780511526039.005"
  generatorConvention := "Generators have source order a,b,c,d,e,f,g, so indices 0 through 6 \
    have those names. A Coxeter path declares each node to be an involution, a labeled edge x-m-y \
    declares (x*y)^m = 1, and an omitted edge declares (x*y)^2 = 1. Products are read left to \
    right. The source decoder compiles x = y as x^-1*y."
  transcriptionNotes := "Expand the paths a5b3c8d3e and b3f4g3b to seven square relations, \
    seven labeled-edge relations, and fourteen omitted-edge relations. Append the five words in \
    presdef[3], compiling the two equalities by the source's MakeWordList decoder, and the one \
    word in presdef[4]. The latter is present because InitializeGroupPresentationGPL includes \
    presdef[4] when GPL_PCE is true, as it is by default in version 1.0. The expected relator \
    count and total length are derived from this exact expansion. GAP 4.15.1 enumerates 1782 \
    cosets of the subgroup generated by a through f, which the source labels G2(4). A separate \
    source-to-Lean read-through remains an S1 review obligation."
  expectedGeneratorCount := 7
  expectedRelatorCount := 34
  transcribed := suzCoxeterRelators ++ suzAdditionalRelators

/-- The generator names recorded for `Suz`. -/
@[simp]
theorem suzPresentation_generatorNames :
    suzPresentation.generatorNames = ["a", "b", "c", "d", "e", "f", "g"] := by
  rfl

/-- The source recorded for `Suz`. -/
@[simp]
theorem suzPresentation_source :
    suzPresentation.source = "R. Lindenbergh, Group Presentations Library, version 1.0; \
      presentation attributed there to C. E. Praeger and L. H. Soicher, Low Rank \
      Representations and Graphs for Sporadic Groups, Cambridge University Press, 1997" := by
  rfl

/-- The locator recorded for `Suz`, including the source's identifier for this presentation. -/
@[simp]
theorem suzPresentation_sourceLocator :
    suzPresentation.sourceLocator = "GPLTable.Suz.1 in \
      https://doris.tudelft.nl/~rlindenbergh/GPL/gpl.g; Praeger--Soicher, Chapter 4, \
      doi:10.1017/CBO9780511526039.005" := by
  rfl

/-- The generator and word-decoding convention recorded for `Suz`. -/
@[simp]
theorem suzPresentation_generatorConvention :
    suzPresentation.generatorConvention = "Generators have source order a,b,c,d,e,f,g, so indices \
      0 through 6 have those names. A Coxeter path declares each node to be an involution, a \
      labeled edge x-m-y declares (x*y)^m = 1, and an omitted edge declares (x*y)^2 = 1. Products \
      are read left to right. The source decoder compiles x = y as x^-1*y." := by
  rfl

/-- The transcription notes recorded for `Suz`. -/
@[simp]
theorem suzPresentation_transcriptionNotes :
    suzPresentation.transcriptionNotes = "Expand the paths a5b3c8d3e and b3f4g3b to seven square \
      relations, seven labeled-edge relations, and fourteen omitted-edge relations. Append the \
      five words in presdef[3], compiling the two equalities by the source's MakeWordList decoder, \
      and the one word in presdef[4]. The latter is present because \
      InitializeGroupPresentationGPL includes presdef[4] when GPL_PCE is true, as it is by default \
      in version 1.0. The expected relator count and total length are derived from this exact \
      expansion. GAP 4.15.1 enumerates 1782 cosets of the subgroup generated by a through f, which \
      the source labels G2(4). A separate source-to-Lean read-through remains an S1 review \
      obligation." := by
  rfl

/-- The generator count recorded for `Suz`. -/
@[simp]
theorem suzPresentation_expectedGeneratorCount :
    suzPresentation.expectedGeneratorCount = 7 := by
  rfl

/-- The relator count recorded for `Suz`. -/
@[simp]
theorem suzPresentation_expectedRelatorCount : suzPresentation.expectedRelatorCount = 34 := by
  rfl

/-- The relator expressions transcribed for `Suz`, with all thirty-four words visible to consumers
of the sealed presentation definition. -/
@[simp]
theorem suzPresentation_transcribed :
    suzPresentation.transcribed =
      let a : Relator (Fin suzPresentation.generatorNames.length) :=
        .gen ⟨0, by simp [suzPresentation]⟩
      let b : Relator (Fin suzPresentation.generatorNames.length) :=
        .gen ⟨1, by simp [suzPresentation]⟩
      let c : Relator (Fin suzPresentation.generatorNames.length) :=
        .gen ⟨2, by simp [suzPresentation]⟩
      let d : Relator (Fin suzPresentation.generatorNames.length) :=
        .gen ⟨3, by simp [suzPresentation]⟩
      let e : Relator (Fin suzPresentation.generatorNames.length) :=
        .gen ⟨4, by simp [suzPresentation]⟩
      let f : Relator (Fin suzPresentation.generatorNames.length) :=
        .gen ⟨5, by simp [suzPresentation]⟩
      let g : Relator (Fin suzPresentation.generatorNames.length) :=
        .gen ⟨6, by simp [suzPresentation]⟩
      [ .pow a 2,
        .pow b 2,
        .pow c 2,
        .pow d 2,
        .pow e 2,
        .pow f 2,
        .pow g 2,
        .pow (a ⬝ b) 5,
        .pow (b ⬝ c) 3,
        .pow (c ⬝ d) 8,
        .pow (d ⬝ e) 3,
        .pow (b ⬝ f) 3,
        .pow (f ⬝ g) 4,
        .pow (g ⬝ b) 3,
        .pow (a ⬝ c) 2,
        .pow (a ⬝ d) 2,
        .pow (a ⬝ e) 2,
        .pow (a ⬝ f) 2,
        .pow (a ⬝ g) 2,
        .pow (b ⬝ d) 2,
        .pow (b ⬝ e) 2,
        .pow (c ⬝ e) 2,
        .pow (c ⬝ f) 2,
        .pow (c ⬝ g) 2,
        .pow (d ⬝ f) 2,
        .pow (d ⬝ g) 2,
        .pow (e ⬝ f) 2,
        .pow (e ⬝ g) 2,
        .inv a ⬝ .pow (c ⬝ d) 4,
        .inv a ⬝ .pow (f ⬝ g) 2,
        .pow (a ⬝ b ⬝ c ⬝ f) 5,
        .pow (b ⬝ f ⬝ g) 5,
        .pow (.pow (b ⬝ c ⬝ d ⬝ c ⬝ d) 5 ⬝ e) 3,
        .pow (a ⬝ b ⬝ c ⬝ g) 5 ] := by
  simp [suzPresentation, suzCoxeterRelators, suzAdditionalRelators]

/-- The generator and relator counts recorded for `Suz` agree with the transcribed data. -/
theorem suzPresentation_matchesMetadata : suzPresentation.matchesMetadata := by
  decide

/-- The compiled relators of the `Suz` presentation contain `275` signed letters in total. -/
theorem suzPresentation_totalLength : suzPresentation.totalLength = 275 := by
  simp [GroupPresentation.totalLength_def, GroupPresentation.relators_def, suzPresentation,
    suzCoxeterRelators, suzAdditionalRelators]

/-- Every compiled relator of the `Suz` presentation is cyclically reduced. -/
theorem suzPresentation_relatorsCyclicallyReduced :
    suzPresentation.relatorsCyclicallyReduced := by
  simp [GroupPresentation.relatorsCyclicallyReduced_iff, GroupPresentation.relators_def,
    suzPresentation, suzCoxeterRelators, suzAdditionalRelators, FreeGroup.IsCyclicallyReduced,
    FreeGroup.invRev]

end TauCeti.Sporadic
