/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.GroupTheory.Presentation.GroupPresentation

/-!
# A transcribed presentation of the third Conway group

This file carries the `Co₃` row of the sporadic presentation data required by milestone S1 of
`TauCetiRoadmap/CFSGStatement/README.md`. It records Đoković's Coxeter-type presentation of the
third Conway group on seven involutions as a `TauCeti.GroupPresentation`, together with its exact
source, generator convention, transcription notes, expected counts, and decidable count check.

The twenty-four defining relators are

```text
a², b², c², d², e², f², g²,
(ac)², (ad)², (ae)², (bd)², (ce)², (dg)², (eg)²,
(ab)³, (cd)³, (de)³,
f(ag)³, g(bf)³, (cfg)³, e(abc)³, e(acg)⁴, (bcfcf)³, e(abcf)⁷.
```

These expressions have source length `174`: the sum of their freely reduced word lengths plus one
separator for each relator. This reproduces presentation (13.1) and its stated length exactly. The
paper obtains the presentation from a faithful permutation representation of `Co₃` and verifies
its defining data using Todd--Coxeter enumeration and recognition results, rather than presenting
the displayed relations as a generator-recognition test inside a pre-existing group.

As an independent transcription check, GAP 4.15.1 enumerates `170775` cosets of the subgroup
generated by `a`, `b`, `c`, `e`, `f`, and `g`, exactly the index reported in the paper. Its coset
action has degree `170775`, is simple of order `495766656000`, and GAP constructs an isomorphism
from that image to AtlasRep 2.1.9's independent 276-point permutation group for `Co₃`. This is
transcription provenance rather than a Lean theorem: the file asserts no order, finiteness,
simplicity, or identification result.

## Main definition

* `TauCeti.Sporadic.co3Presentation`: Đoković's finite presentation of `Co₃`.

## References

* D. Ž. Đoković, *Presentations of some finite simple groups*, J. Austral. Math. Soc. Ser. A
  **45** (1988), 143--168, presentation (13.1), p. 162,
  <https://doi.org/10.1017/S1446788700030068>.
-/

public section

namespace TauCeti.Sporadic

private abbrev a : Relator (Fin 7) := .gen 0

private abbrev b : Relator (Fin 7) := .gen 1

private abbrev c : Relator (Fin 7) := .gen 2

private abbrev d : Relator (Fin 7) := .gen 3

private abbrev e : Relator (Fin 7) := .gen 4

private abbrev f : Relator (Fin 7) := .gen 5

private abbrev g : Relator (Fin 7) := .gen 6

@[inherit_doc Relator.mul]
local infixl:70 " ⬝ " => Relator.mul

/-- Đoković's Coxeter-type finite presentation of the third Conway group `Co₃` on seven
involutions `a`, `b`, `c`, `d`, `e`, `f`, and `g`.

The cited source gives a presentation of the abstract group, not a semi-presentation used only to
recognize generators inside a group already constructed. No structural property of the presented
group is asserted here: this definition records only the cited generators and relators. -/
def co3Presentation : GroupPresentation where
  generatorNames := ["a", "b", "c", "d", "e", "f", "g"]
  source := "Dragomir Z. Djokovic, Presentations of some finite simple groups, Journal of the \
    Australian Mathematical Society Series A 45 (1988), 143-168"
  sourceLocator := "presentation (13.1), p. 162, \
    https://doi.org/10.1017/S1446788700030068"
  generatorConvention := "The seven involutory generators a, b, c, d, e, f, and g in \
    presentation (13.1), in that order, so indices 0 through 6 carry those names. Products are \
    read left to right, juxtaposition denotes multiplication, and powers bind before an adjacent \
    factor: for example, f(ag)^3 is f multiplied by the third power of ag."
  transcriptionNotes := "Transcribe the twenty-four defining relators in presentation (13.1), \
    excluding the twelve words listed separately as consequences. Their source length is 174. \
    GAP 4.15.1 reproduces the reported index 170775 for the subgroup generated by a,b,c,e,f,g; \
    the resulting simple coset-action image has order 495766656000 and GAP identifies it with \
    AtlasRep 2.1.9's independent 276-point Co3 permutation group."
  expectedGeneratorCount := 7
  expectedRelatorCount := 24
  transcribed :=
    [ .pow a 2,
      .pow b 2,
      .pow c 2,
      .pow d 2,
      .pow e 2,
      .pow f 2,
      .pow g 2,
      .pow (a ⬝ c) 2,
      .pow (a ⬝ d) 2,
      .pow (a ⬝ e) 2,
      .pow (b ⬝ d) 2,
      .pow (c ⬝ e) 2,
      .pow (d ⬝ g) 2,
      .pow (e ⬝ g) 2,
      .pow (a ⬝ b) 3,
      .pow (c ⬝ d) 3,
      .pow (d ⬝ e) 3,
      f ⬝ .pow (a ⬝ g) 3,
      g ⬝ .pow (b ⬝ f) 3,
      .pow (c ⬝ f ⬝ g) 3,
      e ⬝ .pow (a ⬝ b ⬝ c) 3,
      e ⬝ .pow (a ⬝ c ⬝ g) 4,
      .pow (b ⬝ c ⬝ f ⬝ c ⬝ f) 3,
      e ⬝ .pow (a ⬝ b ⬝ c ⬝ f) 7 ]

/-- The generator and relator counts recorded for `Co₃` agree with the transcribed data. -/
theorem matchesMetadata_co3Presentation : co3Presentation.matchesMetadata := by
  decide

end TauCeti.Sporadic
