/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.GroupTheory.Presentation.GroupPresentation

/-!
# A transcribed presentation of the second Conway group

This file carries the `Co₂` row of the sporadic presentation data required by milestone S1 of
`TauCetiRoadmap/CFSGStatement/README.md`. It records John Bray's ATLAS version 3 presentation of
the second Conway group on its standard generators `a` and `b` as a `TauCeti.GroupPresentation`,
together with the source, the generator convention, transcription notes, and the expected counts.

Writing `s₁ = ab`, `s₂ = ab²`, `s₋₁ = ab⁻¹` and `s₋₂ = ab⁻²` for the four syllables that occur, the
ten transcribed relators are

```text
a², b⁵, s₂⁹, [a,b]⁴, [a,b²]⁴, [a,bab]³,
[a, bs₂s₁]², [a, bs₋₂]³, [a, b⁻²s₁s₋₂]²,
(s₁s₂s₋₁s₋₂)⁷.
```

The source also displays `[a, b²ab²]³`, but strikes it out of the relator list in both of its
renderings: the version 3 presentation page marks that word with the `redundant` class, which its
stylesheet renders struck through, and the Magma source file comments it out of `Group<x, y | ...>`
with the note "Redundant, but useful." It is therefore outside the relator list proper and is not
transcribed, which is why the recorded relator count is ten. The source's demonstration of
correctness gives coset enumerations both with and without that word, so the ten transcribed
relators are the ones it proves to define `Co₂`.

The source's commutator convention is `[r,s] = r⁻¹s⁻¹rs`, opposite to Mathlib's
`commutatorElement`, so each commutator is stored as `Relator.comm (.inv r) (.inv s)` as
`TauCeti.Relator` prescribes. The proved `TauCeti.Relator.toWord_toFreeGroup` is the audit boundary
between these expressions and the signed words that `PresentedGroup` consumes.

The source is a presentation rather than a semi-presentation, and it comes with a demonstration of
correctness: the relations `a² = b⁵ = (ab²)⁹ = 1` force the presented group to be perfect and
generated by conjugates of `a`; the relations `[a,b]⁴ = [a,b²]⁴ = [a,bab]³ = [a,bab⁻²]³ = 1` force
the source's subgroups `HH` and `H2` to centralize `a`; and a coset enumeration over either returns
the index `56925` of the involution centralizer `[2⁹]·S₆(2)` of `Co₂`. GAP 4.15.1 independently
checks that the ten words compiled by `Relator.toWord` from the expressions below vanish on
five independent standard generating pairs of the 2300-point primitive representation of `Co₂`,
that is, pairs generating the group with `a` an involution whose centralizer has order `743178240`,
`b` of order 5 with centralizer of order `3000`, and `ab` of order `28`. Both computations are
provenance for the transcription, not Lean theorems: this file asserts no order, finiteness,
simplicity, or identification result.

## Main definition

* `TauCeti.Sporadic.co2Presentation`: John Bray's ATLAS finite presentation of `Co₂`.

## References

* R. A. Wilson, R. A. Parker, J. N. Bray et al., *ATLAS of Finite Group Representations*,
  version 3, presentation `Co2G1-P1`, contributed by John Bray,
  <https://brauer.maths.qmul.ac.uk/Atlas/v3/pres/Co2G1-P1>, with the relators and the
  demonstration of correctness in the Magma source file
  <https://brauer.maths.qmul.ac.uk/Atlas/spor/Co2/mag/Co2G1-P1.M>.
-/

public section

namespace TauCeti.Sporadic

private abbrev a : Relator (Fin 2) := .gen 0

private abbrev b : Relator (Fin 2) := .gen 1

@[inherit_doc Relator.mul]
local infixl:70 " ⬝ " => Relator.mul

/-- The source's commutator `[r, s] = r⁻¹ s⁻¹ r s`, which is `⁅r⁻¹, s⁻¹⁆` in Mathlib's
convention. -/
private abbrev sourceComm (r s : Relator (Fin 2)) : Relator (Fin 2) := .comm (.inv r) (.inv s)

/-- The syllable `a * b`. -/
private abbrev ab1 : Relator (Fin 2) := a ⬝ b

/-- The syllable `a * b ^ 2`. -/
private abbrev ab2 : Relator (Fin 2) := a ⬝ .pow b 2

/-- The syllable `a * b⁻¹`. -/
private abbrev abNeg1 : Relator (Fin 2) := a ⬝ .inv b

/-- The syllable `a * b⁻²`. -/
private abbrev abNeg2 : Relator (Fin 2) := a ⬝ .pow (.inv b) 2

/-- John Bray's ATLAS version 3 finite presentation of the second Conway group `Co₂` on its
standard generators `a` and `b`.

The ATLAS lists this as a full presentation of the abstract group, separately from the
semi-presentation used to recognize standard generators inside a group already constructed. No
structural property of the presented group is asserted here: this definition records only the
cited generators and relations. -/
def co2Presentation : GroupPresentation where
  generatorNames := ["a", "b"]
  source := "R. A. Wilson, R. A. Parker, J. N. Bray et al., ATLAS of Finite Group \
    Representations, version 3; presentation contributed by John Bray"
  sourceLocator := "Co2G1-P1, https://brauer.maths.qmul.ac.uk/Atlas/v3/pres/Co2G1-P1, with the \
    relator list and the demonstration of correctness in the Magma source file \
    https://brauer.maths.qmul.ac.uk/Atlas/spor/Co2/mag/Co2G1-P1.M"
  generatorConvention := "The ATLAS standard generators a and b of Co2, that is, a in class 2A \
    and b in class 5A with ab of order 28, in that order, so index 0 is a and index 1 is b. \
    Products are read left to right, negative exponents denote inverses, and [r,s] denotes \
    r^-1 s^-1 r s."
  transcriptionNotes := "The ten words of the source's relator list are stored as ten relators \
    equal to the identity. The source's eleventh displayed word (x,y^2*x*y^2)^3 is struck out of \
    the relator list, shown struck through on the presentation page and commented out as \
    'Redundant, but useful.' in the Magma file, so it lies outside the relator list and is not \
    transcribed. The source demonstrates correctness with and without that word, enumerating in \
    each case the 56925 cosets of a subgroup that centralizes a, \
    which is the index of the involution centralizer [2^9].S6(2) in Co2. GAP 4.15.1 checks that \
    the ten compiled words vanish on five independent standard generating pairs of the 2300-point \
    primitive representation of Co2, taking a with centralizer of order 743178240, b of order 5 \
    with centralizer of order 3000, and ab of order 28."
  expectedGeneratorCount := 2
  expectedRelatorCount := 10
  transcribed :=
    [ .pow a 2,
      .pow b 5,
      .pow ab2 9,
      .pow (sourceComm a b) 4,
      .pow (sourceComm a (.pow b 2)) 4,
      .pow (sourceComm a (b ⬝ a ⬝ b)) 3,
      .pow (sourceComm a (b ⬝ ab2 ⬝ ab1)) 2,
      .pow (sourceComm a (b ⬝ abNeg2)) 3,
      .pow (sourceComm a (.pow (.inv b) 2 ⬝ ab1 ⬝ abNeg2)) 2,
      .pow (ab1 ⬝ ab2 ⬝ abNeg1 ⬝ abNeg2) 7 ]

/-- The generator and relator counts recorded for `Co₂` agree with the transcribed data. -/
theorem matchesMetadata_co2Presentation : co2Presentation.matchesMetadata := by decide

end TauCeti.Sporadic
