/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RingTheory.Binomial
public import TauCeti.Algebra.Ring.Subgroup
public import TauCeti.LinearAlgebra.Finsupp.LinearCombination

/-!
# Products of generalized binomial coefficients

This file gives the linearization formula for the product of two generalized binomial
coefficients in a binomial ring. The formula reads

```text
(r choose m) (r choose n) =
  ∑ i + j = n, (m choose j) (m + i choose m) (r choose (m + i)).
```

The coefficients are natural numbers. Consequently the additive subgroup spanned by the
coefficients `(r choose n)` is already a subring. This integral form is the Cartan--Cartan
multiplication rule used when normal-ordering the generators of the Kostant integral form:
products of the generators `(h choose n)` remain integral linear combinations of generators of
the same kind.

The proof combines Mathlib's Chu--Vandermonde identity `Ring.add_choose_eq` with its shifted
factorization `Ring.choose_smul_choose`. No polynomial expansion or division by factorials is
needed.

Integer translation is controlled by the same basis. Chu--Vandermonde expresses
`(r + z choose n)`, for `z : ℤ`, as an integral combination of the coefficients `(r choose k)`.
Applying the formula again with `-z` proves equality of the two integral spans. This is the
integrality input for commuting Cartan binomial coefficients past divided powers of root vectors.

## Main results

* `TauCeti.ringChoose_mul_ringChoose`: the product of two binomial coefficients in `r`, expanded
  as a natural-number linear combination of binomial coefficients in `r`.
* `TauCeti.ringChooseSpan`: the additive subgroup spanned by the binomial coefficients in one
  element.
* `TauCeti.span_int_range_ringChoose`: that span coincides with the `ℤ`-submodule generated by
  the coefficients.
* `TauCeti.mem_ringChooseSpan_iff_existsUnique`: unique integral expansion in the binomial
  coefficients under `ℤ`-linear independence.
* `TauCeti.mul_mem_ringChooseSpan`: that span is closed under multiplication.
* `TauCeti.toAddSubgroup_subringClosure_range_ringChoose`: the subring generated by the binomial
  coefficients in `r` has no additive elements beyond this span.
* `TauCeti.Ring.choose_intCast`: generalized binomial coefficients commute with integer casts.
* `TauCeti.Ring.choose_add_intCast_mem`: additive subgroups containing the coefficients of `r`
  up to degree `n` contain the degree-`n` coefficient of every integer translate of `r`.
* `TauCeti.ringChoose_add_intCast_mem_ringChooseSpan` and
  `TauCeti.ringChoose_sub_intCast_mem_ringChooseSpan`: integer translates of a coefficient lie in
  the integral span of the original coefficients.
* `TauCeti.ringChooseSpan_add_intCast` and `TauCeti.ringChooseSpan_sub_intCast`: integer
  translation leaves that integral span unchanged.
* `TauCeti.exists_forall_sum_mul_choose_eq`: prescribed integer values on an initial segment are
  attained by an integral combination of binomial coefficients.

## References

* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, §26.
* J. C. Jantzen, *Representations of Algebraic Groups*, II.1.
-/

public section

namespace TauCeti

open Finset

variable {R : Type*}

section Product

variable [Ring R] [BinomialRing R]

/-- The product of two generalized binomial coefficients, expanded as an integral linear
combination of generalized binomial coefficients in the same element.

The pair `(i, j)` runs over `i + j = n`. Thus the summand has binomial degree `m + i` and
coefficient `(m choose j) * (m + i choose m)`. Terms with `m < j` vanish automatically. -/
theorem ringChoose_mul_ringChoose (r : R) (m n : ℕ) :
    Ring.choose r m * Ring.choose r n =
      ∑ ij ∈ antidiagonal n,
        (Nat.choose m ij.2 * Nat.choose (m + ij.1) m) • Ring.choose r (m + ij.1) := by
  have hcomm : Commute (r - (m : R)) (m : R) :=
    (Nat.cast_commute m r).symm.sub_left (Commute.refl (m : R))
  calc
    Ring.choose r m * Ring.choose r n =
        Ring.choose r m * Ring.choose ((r - (m : R)) + (m : R)) n := by
      rw [sub_add_cancel]
    _ = Ring.choose r m *
        ∑ ij ∈ antidiagonal n,
          Ring.choose (r - (m : R)) ij.1 * Ring.choose (m : R) ij.2 := by
      rw [Ring.add_choose_eq n hcomm]
    _ = ∑ ij ∈ antidiagonal n,
        Ring.choose r m *
          (Ring.choose (r - (m : R)) ij.1 * Ring.choose (m : R) ij.2) := by
      rw [mul_sum]
    _ = ∑ ij ∈ antidiagonal n,
        (Nat.choose m ij.2 * Nat.choose (m + ij.1) m) •
          Ring.choose r (m + ij.1) := by
      apply sum_congr rfl
      intro ij _
      rw [Ring.choose_natCast, ← mul_assoc]
      rw [← (Nat.cast_commute (Nat.choose m ij.2)
        (Ring.choose r m * Ring.choose (r - (m : R)) ij.1)).eq]
      rw [← nsmul_eq_mul]
      have hproduct :
          Nat.choose (m + ij.1) m • Ring.choose r (m + ij.1) =
            Ring.choose r m * Ring.choose (r - (m : R)) ij.1 := by
        simpa using Ring.choose_smul_choose r (Nat.le_add_right m ij.1)
      rw [← hproduct, smul_smul]

end Product

/-! ## The integral span -/

section Span

variable [AddCommGroupWithOne R] [Pow R ℕ] [BinomialRing R]

/-- The additive subgroup spanned by all generalized binomial coefficients in `r`. -/
def ringChooseSpan (r : R) : AddSubgroup R :=
  AddSubgroup.closure (Set.range (Ring.choose r))

/-- The integral span is the additive closure of the generalized binomial coefficients. -/
theorem ringChooseSpan_def (r : R) :
    ringChooseSpan r = AddSubgroup.closure (Set.range (Ring.choose r)) :=
  (rfl)

/-- Every generalized binomial coefficient in `r` belongs to its integral span. -/
@[simp]
theorem ringChoose_mem_ringChooseSpan (r : R) (n : ℕ) :
    Ring.choose r n ∈ ringChooseSpan r :=
  AddSubgroup.subset_closure ⟨n, rfl⟩

/-- The integral span of the generalized binomial coefficients in `r` lies in an additive
subgroup exactly when that subgroup contains every such coefficient. -/
@[simp]
theorem ringChooseSpan_le_iff {A : AddSubgroup R} {r : R} :
    ringChooseSpan r ≤ A ↔ ∀ n, Ring.choose r n ∈ A :=
  ⟨fun h n => h (ringChoose_mem_ringChooseSpan r n),
    fun h => (AddSubgroup.closure_le _).2 (Set.range_subset_iff.2 h)⟩

/-- The `ℤ`-linear span of the generalized binomial coefficients in `r` is the integral submodule
associated to `ringChooseSpan r`. -/
@[simp]
theorem span_int_range_ringChoose (r : R) :
    Submodule.span ℤ (Set.range (Ring.choose r)) =
      (ringChooseSpan r).toIntSubmodule := by
  apply Submodule.toAddSubgroup_injective
  rw [Submodule.span_int_eq_addSubgroupClosure,
    AddSubgroup.toIntSubmodule_toAddSubgroup, ringChooseSpan_def]

/-- An element lies in the integral span of the generalized binomial coefficients in `r` exactly
when it has a unique finite integral expansion in those coefficients, provided the sequence of
coefficients is `ℤ`-linearly independent. -/
theorem mem_ringChooseSpan_iff_existsUnique {r : R}
    (h : LinearIndependent ℤ (fun n => Ring.choose r n)) (x : R) :
    x ∈ ringChooseSpan r ↔
      ∃! a : ℕ →₀ ℤ,
        a.sum (fun n z => z • Ring.choose r n) = x := by
  rw [← AddSubgroup.toIntSubmodule_toAddSubgroup (ringChooseSpan r),
    Submodule.mem_toAddSubgroup,
    ← span_int_range_ringChoose r]
  exact TauCeti.LinearIndependent.mem_span_range_iff_existsUnique h x

end Span

section One

variable [NonAssocRing R] [Pow R ℕ] [NatPowAssoc R] [BinomialRing R]

/-- The integral span of the generalized binomial coefficients contains one. -/
@[simp]
theorem one_mem_ringChooseSpan (r : R) : 1 ∈ ringChooseSpan r := by
  rw [← Ring.choose_zero_right r]
  exact ringChoose_mem_ringChooseSpan r 0

end One

section Subring

variable [Ring R] [BinomialRing R]

/-- The integral span of the generalized binomial coefficients is closed under multiplication.

This is the algebraic content of `ringChoose_mul_ringChoose`: its natural-number coefficients act by
repeated addition, so every product of spanning generators remains in the same additive span. -/
theorem mul_mem_ringChooseSpan (r : R) {x y : R} (hx : x ∈ ringChooseSpan r)
    (hy : y ∈ ringChooseSpan r) : x * y ∈ ringChooseSpan r := by
  rw [ringChooseSpan_def] at hx hy ⊢
  refine AddSubgroup.mul_mem_closure_of_mul_mem ?_ hx hy
  rintro _ ⟨m, rfl⟩ _ ⟨n, rfl⟩
  rw [ringChoose_mul_ringChoose]
  have generator_mem (k : ℕ) :
      Ring.choose r k ∈ AddSubgroup.closure (Set.range (Ring.choose r)) :=
    AddSubgroup.subset_closure ⟨k, rfl⟩
  exact sum_mem fun ij _ => AddSubgroup.nsmul_mem _
    (generator_mem (m + ij.1)) _

/-- The subring generated by the generalized binomial coefficients in one element `r` is, as an
additive subgroup, exactly their integral span: no products or powers of these coefficients
escape the span they already generate additively. -/
@[simp]
theorem toAddSubgroup_subringClosure_range_ringChoose (r : R) :
    (Subring.closure (Set.range (Ring.choose r))).toAddSubgroup = ringChooseSpan r := by
  rw [ringChooseSpan_def]
  apply Subring.toAddSubgroup_closure_of_one_mem_of_mul_mem
  · rw [← ringChooseSpan_def]
    exact one_mem_ringChooseSpan r
  · rintro _ ⟨m, rfl⟩ _ ⟨n, rfl⟩
    rw [← ringChooseSpan_def]
    exact mul_mem_ringChooseSpan r
      (ringChoose_mem_ringChooseSpan r m) (ringChoose_mem_ringChooseSpan r n)

/-- Membership in the subring generated by the generalized binomial coefficients in `r` is
membership in their integral additive span. -/
@[simp]
theorem mem_subringClosure_range_ringChoose_iff {r x : R} :
    x ∈ Subring.closure (Set.range (Ring.choose r)) ↔ x ∈ ringChooseSpan r := by
  rw [← Subring.mem_toAddSubgroup, toAddSubgroup_subringClosure_range_ringChoose]

end Subring

/-! ## Integer translation -/

namespace Ring

variable [Ring R] [BinomialRing R]

/-- Generalized binomial coefficients commute with the canonical map from the integers. -/
@[simp]
theorem choose_intCast (z : ℤ) (n : ℕ) :
    _root_.Ring.choose (z : R) n =
      (_root_.Ring.choose (R := ℤ) z n : R) := by
  exact (_root_.Ring.map_choose (Int.castRingHom R) z n).symm

/-- An additive subgroup-like set containing the generalized binomial coefficients of `r` up to
degree `n` contains the degree-`n` coefficient after translating `r` by an integer. -/
theorem choose_add_intCast_mem {G : Type*} [SetLike G R] [AddSubgroupClass G R]
    {A : G} {r : R} {n : ℕ} (hr : ∀ k ≤ n, _root_.Ring.choose r k ∈ A) (z : ℤ) :
    _root_.Ring.choose (r + (z : R)) n ∈ A := by
  rw [_root_.Ring.add_choose_eq n (Int.cast_commute z r).symm]
  exact sum_mem fun ij hij => by
    rw [choose_intCast]
    simpa only [zsmul_eq_mul'] using
      zsmul_mem (hr ij.1 (HasAntidiagonal.antidiagonal.fst_le hij))
        (_root_.Ring.choose (R := ℤ) z ij.2)

end Ring

/-- Translating the argument of a generalized binomial coefficient by an integer keeps it in the
integral span of the coefficients in the original argument.

Chu--Vandermonde expands `(r + z choose n)` as products of `(r choose i)` with integer-valued
coefficients `(z choose j)`. -/
@[simp]
theorem ringChoose_add_intCast_mem_ringChooseSpan [Ring R] [BinomialRing R]
    (r : R) (z : ℤ) (n : ℕ) :
    Ring.choose (r + (z : R)) n ∈ ringChooseSpan r := by
  exact Ring.choose_add_intCast_mem (fun k _ => ringChoose_mem_ringChooseSpan r k) z

/-- Subtracting an integer from the argument of a generalized binomial coefficient keeps it in
the integral span of the coefficients in the original argument. -/
@[simp]
theorem ringChoose_sub_intCast_mem_ringChooseSpan [Ring R] [BinomialRing R]
    (r : R) (z : ℤ) (n : ℕ) :
    Ring.choose (r - (z : R)) n ∈ ringChooseSpan r := by
  simpa only [sub_eq_add_neg, Int.cast_neg] using
    ringChoose_add_intCast_mem_ringChooseSpan r (-z) n

/-- Integer translation leaves the integral span of the generalized binomial coefficients
unchanged. -/
@[simp]
theorem ringChooseSpan_add_intCast [Ring R] [BinomialRing R] (r : R) (z : ℤ) :
    ringChooseSpan (r + (z : R)) = ringChooseSpan r := by
  apply le_antisymm
  · rw [ringChooseSpan_le_iff]
    exact ringChoose_add_intCast_mem_ringChooseSpan r z
  · rw [ringChooseSpan_le_iff]
    intro n
    have h := ringChoose_add_intCast_mem_ringChooseSpan (r + (z : R)) (-z) n
    simpa using h

/-- Subtracting an integer from the argument leaves the integral span of the generalized binomial
coefficients unchanged. -/
@[simp]
theorem ringChooseSpan_sub_intCast [Ring R] [BinomialRing R] (r : R) (z : ℤ) :
    ringChooseSpan (r - (z : R)) = ringChooseSpan r := by
  simpa only [sub_eq_add_neg, Int.cast_neg] using ringChooseSpan_add_intCast r (-z)

/-!
# Identities and negation for generalized binomial coefficients

In a binomial ring, Mathlib's `Ring.choose_neg` writes `(-r choose n)` as a sign times the
*multichoose* coefficient of `r`, which is `(r + n - 1 choose n)`. This file takes the last step
and expands that coefficient by the Chu--Vandermonde identity, so that `(-r choose n)` becomes an
integer combination of the coefficients `(r choose k)` for `k ≤ n`, with the ordinary binomial
coefficients of `n - 1` as its weights.

The consequence, `TauCeti.Ring.choose_neg_mem`, is the form a consumer uses: an additive subgroup
containing
`(r choose k)` for every `k ≤ n` contains `(-r choose n)` as well. That is what makes the Cartan
generators of a Kostant integral form stable under the antipode of an enveloping algebra, since
the antipode negates each Cartan vector.

The file also records a weighted form of Pascal's identity. Its two terms are exactly the
adjacent coefficients that arise when one more raising operator is moved through a rank-one
Kostant normal-ordering sum: the first keeps the summation index and the second increments it.
The identity combines them without division, which is the integral step needed in the induction.

## Main results

* `TauCeti.Ring.choose_neg_succ_eq_sum`: the expansion of `(-r choose (n + 1))` as a signed
  Chu--Vandermonde sum of the coefficients `(r choose k)`.
* `TauCeti.Ring.choose_neg_mem`: an additive subgroup containing the coefficients of `r` up to
  degree `n` contains the degree-`n` coefficient of `-r`.
* `TauCeti.ringChooseSpan_neg`: negation leaves the integral span unchanged.
* `TauCeti.Ring.mul_weighted_choose_add_mul_choose`: a scalar-weighted Pascal identity.

## References

* J. Elliott, *Binomial rings, integer-valued polynomials, and λ-rings*, J. Pure Appl. Algebra
  **207** (2006), 165–185.
* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, §26.2, for the
  rank-one Kostant normal-ordering formula that consumes the weighted identity.
-/

namespace Ring

open Finset

/-! ## Weighted Pascal identities -/

section WeightedPascal

variable {R : Type*} [NonAssocRing R] [Pow R ℕ] [NatPowAssoc R] [BinomialRing R]

/-- A scalar-weighted form of Pascal's identity:

```text
c (r - 1 choose k + 1) + (r + c) (r - 1 choose k)
  = c (r choose k + 1) + (k + 1) (r choose k + 1).
```

No commutativity between `c` and `r` is needed: every occurrence of `c` is on the left. -/
@[simp]
theorem mul_weighted_choose_add_mul_choose (r c : R) (k : ℕ) :
    c * _root_.Ring.choose (r - 1) (k + 1) +
        (r + c) * _root_.Ring.choose (r - 1) k =
      c * _root_.Ring.choose r (k + 1) +
        (k + 1) • _root_.Ring.choose r (k + 1) := by
  have hmul :
      (k + 1) • _root_.Ring.choose r (k + 1) =
        r * _root_.Ring.choose (r - 1) k := by
    simpa [Nat.choose_one_right] using
      _root_.Ring.choose_smul_choose r (n := k + 1) (k := 1) (by omega)
  rw [add_mul, ← hmul]
  have hpascal : _root_.Ring.choose r (k + 1) =
      _root_.Ring.choose (r - 1) k + _root_.Ring.choose (r - 1) (k + 1) := by
    simpa only [sub_add_cancel] using _root_.Ring.choose_succ_succ (r - 1) k
  rw [hpascal]
  rw [mul_add]
  abel

end WeightedPascal

/-! ## Negating the argument -/

variable {R : Type*} [Ring R] [BinomialRing R]

/-- Negating the argument of a generalized binomial coefficient of positive degree expands, by
Chu--Vandermonde, into a signed sum of the coefficients of the original argument weighted by
ordinary binomial coefficients of `n`.

The degree is written as `n + 1` because the multichoose shift `r + n - 1` of
`Ring.choose_neg` is a natural-number translate of `r` only in positive degree. Degree zero is
`Ring.choose_zero_right` on both sides. -/
theorem choose_neg_succ_eq_sum (r : R) (n : ℕ) :
    _root_.Ring.choose (-r) (n + 1) = Int.negOnePow (n + 1) •
      ∑ ij ∈ antidiagonal (n + 1),
        _root_.Ring.choose r ij.1 * (n.choose ij.2 : R) := by
  rw [_root_.Ring.choose_neg]
  congr 1
  have hshift : r + ((n + 1 : ℕ) : R) - 1 = r + (n : R) := by push_cast; abel
  rw [hshift, _root_.Ring.add_choose_eq _ (Nat.cast_commute n r).symm]
  exact sum_congr rfl fun ij _ => by rw [_root_.Ring.choose_natCast]

/-- An additive subgroup-like set containing the generalized binomial coefficients of `r` up to
degree `n` contains the degree-`n` coefficient of `-r`. -/
theorem choose_neg_mem {G : Type*} [SetLike G R] [AddSubgroupClass G R]
    {A : G} {r : R} {n : ℕ} (hr : ∀ k ≤ n, _root_.Ring.choose r k ∈ A) :
    _root_.Ring.choose (-r) n ∈ A := by
  rw [_root_.Ring.choose_neg, Units.smul_def]
  refine zsmul_mem ?_ _
  have hshift : r + (n : R) - 1 = r + (((n : ℤ) - 1 : ℤ) : R) := by
    push_cast
    abel
  rw [hshift]
  exact choose_add_intCast_mem hr _

end Ring

/-- Negation leaves the integral span of the generalized binomial coefficients unchanged. -/
@[simp]
theorem ringChooseSpan_neg [Ring R] [BinomialRing R] (r : R) :
    ringChooseSpan (-r) = ringChooseSpan r := by
  apply le_antisymm
  · rw [ringChooseSpan_le_iff]
    exact fun n => Ring.choose_neg_mem fun k _ => ringChoose_mem_ringChooseSpan r k
  · rw [ringChooseSpan_le_iff]
    intro n
    have h := Ring.choose_neg_mem (A := ringChooseSpan (-r)) (r := -r) (n := n)
      fun k _ => ringChoose_mem_ringChooseSpan (-r) k
    simpa using h

/-!
# Integral interpolation on an initial segment

The generalized binomial coefficients are the integrally interpolating family: prescribing
arbitrary integer values on `0, 1, …, N` is always solvable in *integer* coefficients, even
though the interpolating polynomial itself has non-integral coefficients. This is Newton's
forward-difference formula, and it is what lets integral combinations of the binomial
coefficients `(h choose k)` of a Cartan vector separate the integer weights of a
representation, one weight at a time.
-/

/-- **Integral interpolation by binomial coefficients.** Arbitrary integer values on the initial
segment `0, 1, …, N` are attained by an integral combination of the binomial coefficients
`(· choose k)` for `k ≤ N`.

The matrix `(j choose k)` is lower unitriangular, so the coefficients are read off one at a time:
the induction step solves for `c (N + 1)` using `(N + 1 choose N + 1) = 1`, and the added term
does not disturb the smaller values because `(j choose N + 1) = 0` for `j ≤ N`. -/
theorem exists_forall_sum_mul_choose_eq (N : ℕ) (g : ℕ → ℤ) :
    ∃ c : ℕ → ℤ, ∀ j ≤ N, ∑ k ∈ range (N + 1), c k * (j.choose k : ℤ) = g j := by
  induction N with
  | zero => exact ⟨fun _ => g 0, fun j hj => by simp [Nat.le_zero.1 hj]⟩
  | succ N ih =>
    obtain ⟨c, hc⟩ := ih
    classical
    refine ⟨Function.update c (N + 1)
      (g (N + 1) - ∑ i ∈ range (N + 1), c i * ((N + 1).choose i : ℤ)), fun j hj => ?_⟩
    have hrestrict : ∀ k ∈ range (N + 1),
        Function.update c (N + 1)
            (g (N + 1) - ∑ i ∈ range (N + 1), c i * ((N + 1).choose i : ℤ)) k *
          (j.choose k : ℤ) = c k * (j.choose k : ℤ) := fun k hk => by
      rw [Function.update_of_ne (Nat.ne_of_lt (mem_range.1 hk))]
    rw [Finset.sum_range_succ, Finset.sum_congr rfl hrestrict, Function.update_self]
    rcases eq_or_lt_of_le hj with rfl | hjN
    · rw [Nat.choose_self, Nat.cast_one, mul_one]
      ring
    · rw [Nat.choose_eq_zero_of_lt hjN, Nat.cast_zero, mul_zero, add_zero]
      exact hc j (Nat.lt_succ_iff.1 hjN)

end TauCeti
